Precompute twiddles
starkware-libs/stwo pull request #401
Opened 2024-02-25 08:33 UTC by spapinistarkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo/401)

2024-03-11 11:24 UTC, shaharsamocha7 requested changes
> Reviewed 2 of 6 files at r1, 3 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 6 of 9 files reviewed, 15 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/circle.rs` line 373 at r2](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsOZpFb7-HKDFgHva1t:-NsOZpFb7-HKDFgHva1u:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/30e1f97c6368be1f56fbd37e1183b7d83676a219/src/core/circle.rs#L373)):*
> ```XML
> 
>     pub fn repeated_double(&self, n_doubles: u32) -> Self {
>         (0..n_doubles).fold(*self, |c, _| c.double())
> ```

?



_Suggestion:_
```XML
coset
```
___
*[`src/core/backend/avx512/circle.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshDlC037utgDXPIhbG:-NshDlC1AWXab9DAZtjp:b4s196) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/avx512/circle.rs#L148)):*
> ```XML
>     }
> 
>     type Twiddles = ();
> ```

I saw that in the next pr this going to be Vec<i32>.
?



_Code quote:_
```XML
type Twiddles = ();
```
___
*[`src/core/backend/cpu/circle.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshECyABGGQzYyjMr7k:-NshECyABGGQzYyjMr7l:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L39)):*
> ```XML
>         let mut values = eval.values;
> 
>         let twiddle_buffer = &twiddles.itwiddles;
> ```





_Suggestion:_
```XML
itwiddle_buffer
```
___
*[`src/core/backend/cpu/circle.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshELkdBUtHd_WEJWaV:-NshELkdBUtHd_WEJWaW:buyyvtf) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L40)):*
> ```XML
> 
>         let twiddle_buffer = &twiddles.itwiddles;
>         let mut x_twiddles = (0..eval.domain.half_coset.log_size())
> ```

Are those the line_twiddles?



_Code quote:_
```XML
x_twiddles
```
___
*[`src/core/backend/cpu/circle.rs` line 55 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEV041ptSedui47tn:-NshEV041ptSedui47to:b-i1hfk) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L55)):*
> ```XML
>                 eval.domain.half_coset.initial.y.inverse(),
>             );
>             let inv = BaseField::from_u32_unchecked(2).inverse();
> ```

Can those inverses be also precomputed?



_Code quote:_
```XML
                eval.domain.half_coset.initial.y.inverse(),
            );
            let inv = BaseField::from_u32_unchecked(2).inverse();
```
___
*[`src/core/backend/cpu/circle.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEZAP4mEN6y5R8JkI:-NshEZAQ6DCvRekhOyfO:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L60)):*
> ```XML
>         };
> 
>         // [x,y] => [y,-y,-x,x]
> ```

Document



_Code quote:_
```XML
// [x,y] => [y,-y,-x,x]
```
___
*[`src/core/backend/cpu/circle.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEgiJ5vs7FuV74vL9:-NshEgiJ5vs7FuV74vLA:b-w9tzia) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L77)):*
> ```XML
>         };
> 
>         for (h, t) in y_twiddles.enumerate() {
> ```

circle_twiddles



_Code quote:_
```XML
y_twiddles
```
___
*[`src/core/backend/cpu/circle.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshFC5FAVSQSvMLJ2Ep:-NshFC5FAVSQSvMLJ2Eq:bv76ult) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L115)):*
> ```XML
>     }
> 
>     fn evaluate(
> ```

This function is very similiar to the interpolate function
Do we want to share some code between them?



_Code quote:_
```XML
fn evaluate(
```
___
*[`src/core/poly/twiddles.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsO_ILGAMpCfETemUtP:-NsO_ILGAMpCfETemUtQ:bnugx5f) ([raw file](https://github.com/starkware-libs/stwo/blob/30e1f97c6368be1f56fbd37e1183b7d83676a219/src/core/poly/twiddles.rs#L32)):*
> ```XML
> /// Precomputed twiddles for a specific coset tower.
> /// A coset tower is every repeated doubling of a root coset
> pub struct TwiddleTree<B: PolyOps<F>, F: ExtensionOf<BaseField>> {
> ```

Aren't twiddles always from basefield?



_Code quote:_
```XML
F: ExtensionOf<BaseField>
```
___
*[`src/core/poly/twiddles.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshAkvTD1sirdETpy8I:-NshAkvTD1sirdETpy8J:b-1yxqvd) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L12)):*
> ```XML
> pub struct TwiddleBank<B: PolyOps<F>, F: ExtensionOf<BaseField>> {
>     trees: Vec<TwiddleTree<B, F>>,
> }
> ```

Do we need this now?
Should this bank contain twiddles for both evaluation, commitment cosets?



_Code quote:_
```XML
pub struct TwiddleBank<B: PolyOps<F>, F: ExtensionOf<BaseField>> {
    trees: Vec<TwiddleTree<B, F>>,
}
```
___
*[`src/core/poly/twiddles.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshB5Ue1vHiTTgf0LEn:-NshB5Ue1vHiTTgf0LEo:b-nfb0de) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L31)):*
> ```XML
> 
> /// Precomputed twiddles for a specific coset tower.
> /// A coset tower is every repeated doubling of a root coset
> ```

The root_coset is the largest one of the tower?



_Suggestion:_
```XML
`root_coset`
```
___
*[`src/core/poly/twiddles.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshBvqY04knfqRESMQG:-NshBvqY04knfqRESMQH:b-916cb4) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L36)):*
> ```XML
>     // TODO(spapini): Represent a slice, and grabbing, in a generic way
>     pub twiddles: B::Twiddles,
>     pub itwiddles: B::Twiddles,
> ```

Do we always need both twiddles, itwiddles?
Couldn't we have a coset that is needed only for evaluate?



_Code quote:_
```XML
    pub twiddles: B::Twiddles,
    pub itwiddles: B::Twiddles,
```
___
*[`src/core/poly/circle/evaluation.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshC6Ta6svXQCiXa8NV:-NshC6Ta6svXQCiXa8NW:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/evaluation.rs#L86)):*
> ```XML
>     /// Computes a minimal [CirclePoly] that evaluates to the same values as this evaluation, using
>     /// preconditioned twiddles.
>     pub fn interpolate_with_twiddles(self, twiddles: &TwiddleBank<B, F>) -> CirclePoly<B, F> {
> ```





_Suggestion:_
```XML
twiddle_bank
```
___
*[`src/core/poly/circle/ops.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshChJB0OhUjO9MHBhP:-NshChJB0OhUjO9MHBhQ:b-es19l1) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/ops.rs#L39)):*
> ```XML
>     ) -> CircleEvaluation<Self, F, BitReversedOrder>;
> 
>     type Twiddles;
> ```

move up before function declarations



_Code quote:_
```XML
type Twiddles;
```
___
*[`src/core/poly/circle/poly.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshD2mO1tgpTjZEOJOO:-NshD2mPE3FzyiQT6vS9:b-17zuab) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/poly.rs#L60)):*
> ```XML
>         twiddles: &TwiddleBank<B, F>,
>     ) -> CircleEvaluation<B, F, BitReversedOrder> {
>         B::evaluate(self, domain, twiddles.get_tree(dom [...]

2024-03-12 13:30 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshECyABGGQzYyjMr7k:-NsmMop68kSVKGtvB8Bo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L39)):*
> ```XML
>         let mut values = eval.values;
> 
>         let twiddle_buffer = &twiddles.itwiddles;
> ```

Done.
___
*[`src/core/backend/cpu/circle.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEZAP4mEN6y5R8JkI:-NsmqX740h9s0drIdabA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEgiJ5vs7FuV74vL9:-NsmqXXb2QL1hy57SZZC:b-jk0yvb) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

circle_twiddles
</blockquote></details>

I think y is better.
___
*[`src/core/poly/twiddles.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsO_ILGAMpCfETemUtP:-NsmpfHz2EpDos_rJKly:bb77ufg) ([raw file](https://github.com/starkware-libs/stwo/blob/30e1f97c6368be1f56fbd37e1183b7d83676a219/src/core/poly/twiddles.rs#L32)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Aren't twiddles always from basefield?
</blockquote></details>

Yes.
___
*[`src/core/poly/twiddles.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshB5Ue1vHiTTgf0LEn:-NsmpehS0hoe1jBs_HVX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L31)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The root_coset is the largest one of the tower?
</blockquote></details>

Done.
___
*[`src/core/poly/twiddles.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshBvqY04knfqRESMQG:-NsmpiV7B8myAmqHqRIG:b-t2xx6) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L36)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we always need both twiddles, itwiddles?
Couldn't we have a coset that is needed only for evaluate?
</blockquote></details>

The biggest domains are for the comopsition, and we need both evaluation and interpolation for them
___
*[`src/core/poly/circle/evaluation.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshC6Ta6svXQCiXa8NV:-Nsmpw0bAWT5qpGD6a0M:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/evaluation.rs#L86)):*
> ```XML
>     /// Computes a minimal [CirclePoly] that evaluates to the same values as this evaluation, using
>     /// preconditioned twiddles.
>     pub fn interpolate_with_twiddles(self, twiddles: &TwiddleBank<B, F>) -> CirclePoly<B, F> {
> ```

Done.
___
*[`src/core/poly/circle/ops.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshChJB0OhUjO9MHBhP:-NsmqNyiEAvsthE-I10O:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/ops.rs#L39)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move up before function declarations
</blockquote></details>

Done.
___
*[`src/core/poly/circle/poly.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshD2mO1tgpTjZEOJOO:-NsmqQ4Z1hO5RwyiyvCe:bw5ztd9) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/poly.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you explain here why you only need the twiddles for half_coset here?
</blockquote></details>

The y twiddles are derived from the x twiddles.


<!-- Sent from Reviewable.io -->

2024-03-12 14:00 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 3 of 9 files reviewed, 14 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmuMeQ3vDIMbUIg-D2:-NsmuMeQ3vDIMbUIg-D3:b-y7puc8) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/avx512/circle.rs#L79)):*
> ```XML
>         mappings.reverse();
> 
>         if poly.log_size() as usize > CACHED_FFT_LOG_SIZE {
> ```

I know this code was already merged but can you remind what is this if?
Maybe we can add a comment :)



_Code quote:_
```XML
if poly.log_size() as usize > CACHED_FFT_LOG_SIZE {
```
___
*[`src/core/backend/cpu/circle.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEgiJ5vs7FuV74vL9:-Nsmw8Gf0-fHWysJ08so:by6hpfi) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L77)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think y is better.
</blockquote></details>

I thought that circle/line_twiddles is more straightforward, no?
___
*[`src/core/backend/cpu/circle.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmwK-d5B3QIMrrB3Ko:-NsmwK-d5B3QIMrrB3Kp:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L63)):*
> ```XML
>             fft_loop(&mut values, 0, h, t, ibutterfly);
>         }
>         for (i, layer_twiddles) in x_twiddles.into_iter().enumerate() {
> ```





_Suggestion:_
```XML
layer
```
___
*[`src/core/backend/cpu/circle.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsmwcn84-8oR1MKKH9j:-Nsmwcn84-8oR1MKKH9k:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L131)):*
> ```XML
>     }
> 
>     fn precompute_twiddles(mut coset: Coset) -> TwiddleTree<Self> {
> ```

Document



_Code quote:_
```XML
fn precompute_twiddles(mut coset: Coset) -> TwiddleTree<Self> {
```
___
*[`src/core/backend/cpu/circle.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmwZFu5sdxrKlUaYDu:-NsmwZFv8unCxNy78dpg:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L159)):*
> ```XML
> }
> 
> /// Computes the twiddles for a [CircleDomain] from the precomputed twiddles tree.
> ```





_Suggestion:_
```XML
line twiddles
```
___
*[`src/core/backend/cpu/circle.rs` line 173 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmwsFQ-9U1ikop_xSp:-NsmwsFQ-9U1ikop_xSq:b-wx76qv) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L173)):*
> ```XML
> }
> 
> fn fft_loop(
> ```

this only does 1 layer of the fft, right?
maybe rename to fft_layer_loop?

Document



_Code quote:_
```XML
fft_loop
```
___
*[`src/core/backend/cpu/circle.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxR5q9YU9j42s7h5u:-NsmxR5q9YU9j42s7h5v:bbueclt) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L193)):*
> ```XML
>     // The twiddles for layer 0 can be computed from the twiddles for layer 1:
>     // A circle coset of size 4 in bit reversed order looks like this:
>     //   [(x, y), (-x, -y), (y, -x), (-y, x)]
> ```

Can this example be expanded to 8 points? or that would be too detailed?



_Code quote:_
```XML
[(x, y), (-x, -y), (y, -x), (-y, x)]
```
___
*[`src/core/backend/cpu/circle.rs` line 195 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxeHs4oDeD7Iar_RO:-NsmxeHs4oDeD7Iar_RP:bdr9s2h) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L195)):*
> ```XML
>     //   [(x, y), (-x, -y), (y, -x), (-y, x)]
>     // Note: This is related to the choice of M31_CIRCLE_GEN, and the fact the a quarter rotation
>     //   is (0,-1) and not (0,1). This would cause another relation.
> ```

I can't compile this sentence



_Code quote:_
```XML
    // Note: This is related to the choice of M31_CIRCLE_GEN, and the fact the a quarter rotation
    //   is (0,-1) and not (0,1). This would cause another relation.
```
___
*[`src/core/backend/cpu/circle.rs` line 200 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxhC51Rx5emS1jJjm:-NsmxhC6DtCWruDl_bPH:b-3n3oed) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L200)):*
> ```XML
>     // The twiddles for layer 1 in bit reversed order are the x coordinates:
>     //   [x, y]
>     // Works also for inverse of the twiddles.
> ```

Do we want this here?



_Code quote:_
```XML
// Works also for inverse of the twiddles.
```


<!-- Sent from Reviewable.io -->

2024-03-12 14:13 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 3 of 10 files reviewed, 14 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/circle.rs` line 79 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmuMeQ3vDIMbUIg-D2:-NsmyY4t8MSS8sHCAlKl:b-5c6cf) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/avx512/circle.rs#L79)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I know this code was already merged but can you remind what is this if?
Maybe we can add a comment :)
</blockquote></details>

When the entire fft fits in cache, we don't tranpose in the middle of the fft.
___
*[`src/core/backend/cpu/circle.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshEgiJ5vs7FuV74vL9:-Nsmz8SI-N10PSILuQ0O:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/backend/cpu/circle.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought that circle/line_twiddles is more straightforward, no?
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmwK-d5B3QIMrrB3Ko:-NsmzDXv2pZV9YygDuT3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L63)):*
> ```XML
>             fft_loop(&mut values, 0, h, t, ibutterfly);
>         }
>         for (i, layer_twiddles) in x_twiddles.into_iter().enumerate() {
> ```

Done.
___
*[`src/core/backend/cpu/circle.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsmwcn84-8oR1MKKH9j:-NsmzHNS6_YLcLCftS_h:b-fgywsg) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L131)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

I'm implementing a trait that is already documented. Putting my mouse over thsi function shows the trait doc.
___
*[`src/core/backend/cpu/circle.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmwZFu5sdxrKlUaYDu:-NsmzTi87IwP5fvt5sqJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L159)):*
> ```XML
> }
> 
> /// Computes the twiddles for a [CircleDomain] from the precomputed twiddles tree.
> ```

Done.
___
*[`src/core/backend/cpu/circle.rs` line 173 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmwsFQ-9U1ikop_xSp:-NsmzWiW8D4NxABzJWmX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L173)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

this only does 1 layer of the fft, right?
maybe rename to fft_layer_loop?

Document
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxR5q9YU9j42s7h5u:-Nsmzizq2kS4THFwer_r:b-k2gb2j) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L193)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can this example be expanded to 8 points? or that would be too detailed?
</blockquote></details>

It's not really an example, but an explanation of the general case.
Every circle domain is composed of a sequence of size-4 circle domains.

An example of 8 points will include (x/sqrt(2)-y/sqrt(2),-x/sqrt(2)-y/sqrt(2)), and I think will only make this more complicated.
___
*[`src/core/backend/cpu/circle.rs` line 195 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxeHs4oDeD7Iar_RO:-Nsn-LqmEN1hPgtyeaL_:bf2h817) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L195)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I can't compile this sentence
</blockquote></details>

The reason that rthe previous form is correct "[(x, y), (-x, -y), (y, -x), (-y, x)]" is related to the choice of M31_CIRCLE_GEN.
If instead, we would choose -M31_CIRCLE_GEN, then the relation would be a bit different:
"[(x, y), (-x, -y), (-y, x), (y, -x)]"
___
*[`src/core/backend/cpu/circle.rs` line 200 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxhC51Rx5emS1jJjm:-Nsmze6l78UeAElO5HH4:b-4hk6ah) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L200)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want this here?
</blockquote></details>

Yes, since this function is also used for the inverses.


<!-- Sent from Reviewable.io -->

2024-03-12 14:43 UTC, shaharsamocha7 requested changes
> Reviewed 2 of 7 files at r4, 2 of 4 files at r6, 2 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 9 of 11 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsmwcn84-8oR1MKKH9j:-Nsn43yJ6fA0ogRFMRRu:b-1bqod5) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L131)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm implementing a trait that is already documented. Putting my mouse over thsi function shows the trait doc.
</blockquote></details>

missed that.
___
*[`src/core/backend/cpu/circle.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxR5q9YU9j42s7h5u:-Nsn4G6U9Cs5v8nzQNaW:b4utlon) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L193)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not really an example, but an explanation of the general case.
Every circle domain is composed of a sequence of size-4 circle domains.

An example of 8 points will include (x/sqrt(2)-y/sqrt(2),-x/sqrt(2)-y/sqrt(2)), and I think will only make this more complicated.
</blockquote></details>

I thought about
`[(x0,y0), ...(-y0, x0), (x1,y1), ..., (-y1,-x1)]`
___
*[`src/core/backend/cpu/circle.rs` line 195 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxeHs4oDeD7Iar_RO:-Nsn552K23GRV5JanYSk:bhcajlh) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L195)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The reason that rthe previous form is correct "[(x, y), (-x, -y), (y, -x), (-y, x)]" is related to the choice of M31_CIRCLE_GEN.
If instead, we would choose -M31_CIRCLE_GEN, then the relation would be a bit different:
"[(x, y), (-x, -y), (-y, x), (y, -x)]"
</blockquote></details>

What is the form of the circle gen in this sense?
we have (2, 1268011823).

I'm still not sure I follow the doc, e.g. why you call those "y coordinated"?

    // The twiddles for layer 0 are the y coordinates:
    //   [y, -y, -x, x]
___
*[`src/core/poly/twiddles.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshBvqY04knfqRESMQG:-Nsn63q16IEtmJmyJea2:b-uhzte5) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L36)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The biggest domains are for the comopsition, and we need both evaluation and interpolation for them
</blockquote></details>

is this true?
You are going to evaluate the CP on {size + blowup, size + constraint_deg}
and you don't need to ifft on those sizes. or where do I get this wrong?
___
*[`src/core/poly/circle/evaluation.rs` line 85 at r7](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsn39b43c4DX4AqGQKj:-Nsn39b43c4DX4AqGQKk:basxvv) ([raw file](https://github.com/starkware-libs/stwo/blob/24220eda545200bffbdcc57ea4cdf86ed9418f96/src/core/poly/circle/evaluation.rs#L85)):*
> ```XML
> 
>     /// Computes a minimal [CirclePoly] that evaluates to the same values as this evaluation, using
>     /// preconditioned twiddles.
> ```

precomputed



_Code quote:_
```XML
preconditioned
```
___
*[`src/core/poly/circle/ops.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsn3XQTBO9jRxjyhXM1:-Nsn3XQTBO9jRxjyhXM2:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/24220eda545200bffbdcc57ea4cdf86ed9418f96/src/core/poly/circle/ops.rs#L10)):*
> ```XML
> /// Operations on BaseField polynomials.
> pub trait PolyOps: FieldOps<BaseField> + Sized {
>     // TODO(spapini): Use a colum instead of this type.
> ```





_Suggestion:_
```XML
// TODO(spapini): Use a column instead of this type.
```
___
*[`src/core/poly/circle/poly.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshD2mO1tgpTjZEOJOO:-Nsn3hRE65CcV5HW4zGe:bwv757d) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/poly.rs#L60)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The y twiddles are derived from the x twiddles.
</blockquote></details>

Yeah, I meant in a comment


<!-- Sent from Reviewable.io -->

2024-03-12 15:14 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 195 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxeHs4oDeD7Iar_RO:-NsnD6vX7_TANwFfuwmr:b-c6eu44) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L195)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What is the form of the circle gen in this sense?
we have (2, 1268011823).

I'm still not sure I follow the doc, e.g. why you call those "y coordinated"?

    // The twiddles for layer 0 are the y coordinates:
    //   [y, -y, -x, x]
</blockquote></details>

I think we nede to discuss this f2f:)
___
*[`src/core/poly/twiddles.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshBvqY04knfqRESMQG:-NsnDGjoEBKZVx7iwmUs:b-fv4wfb) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L36)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

is this true?
You are going to evaluate the CP on {size + blowup, size + constraint_deg}
and you don't need to ifft on those sizes. or where do I get this wrong?
</blockquote></details>

you're righ.t
Anyway, don't think it's worth the effort.
___
*[`src/core/poly/circle/evaluation.rs` line 85 at r7](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsn39b43c4DX4AqGQKj:-NsnDX6O2jz8fUrl7c9F:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24220eda545200bffbdcc57ea4cdf86ed9418f96/src/core/poly/circle/evaluation.rs#L85)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

precomputed
</blockquote></details>

Done.
___
*[`src/core/poly/circle/ops.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsn3XQTBO9jRxjyhXM1:-NsnDbA81XxLVNTVbcaq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24220eda545200bffbdcc57ea4cdf86ed9418f96/src/core/poly/circle/ops.rs#L10)):*
> ```XML
> /// Operations on BaseField polynomials.
> pub trait PolyOps: FieldOps<BaseField> + Sized {
>     // TODO(spapini): Use a colum instead of this type.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-13 07:53 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 193 at r6](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsmxR5q9YU9j42s7h5u:-Nsqmlko5KG1GTSB-MH_:b-bjpj7a) ([raw file](https://github.com/starkware-libs/stwo/blob/0b604910c6c9c61c06fbac929bbb0be2113a5a28/src/core/backend/cpu/circle.rs#L193)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought about
`[(x0,y0), ...(-y0, x0), (x1,y1), ..., (-y1,-x1)]`
</blockquote></details>

Better?
___
*[`src/core/poly/circle/poly.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshD2mO1tgpTjZEOJOO:-Nsqmc22-XP9Rb4g60PW:btsongh) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/circle/poly.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Yeah, I meant in a comment
</blockquote></details>

I think it's unnecessary here without the bank, right?


<!-- Sent from Reviewable.io -->

2024-03-13 09:29 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/poly/twiddles.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshBvqY04knfqRESMQG:-Nsr88-DEza75HouzdEo:bxtbi6b) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L36)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

you're righ.t
Anyway, don't think it's worth the effort.
</blockquote></details>

Right.
Should we add it to a further optimizations doc?


<!-- Sent from Reviewable.io -->

2024-03-13 09:44 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 199 at r10](https://reviewable.io/reviews/starkware-libs/stwo/401#-Nsr9bnuANDiP49N32Of:-NsrBT0k6A-inpChFwYW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/07065a83f9e8bb2ed74f815a1e15f8e95f707a10/src/core/backend/cpu/circle.rs#L199)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do you think that this is more straight-forward?
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 202 at r10](https://reviewable.io/reviews/starkware-libs/stwo/401#-NsrA80O2WIUUJME-Gc9:-NsrBYZk0daunYQrWaki:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/07065a83f9e8bb2ed74f815a1e15f8e95f707a10/src/core/backend/cpu/circle.rs#L202)):*
> ```XML
>     // The twiddles for layer 0 are the y coordinates:
>     //   [y, -y, -x, x]
>     // The twiddles for layer 1 in bit reversed order are the x coordinates:
> ```

Done.
___
*[`src/core/poly/twiddles.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/stwo/401#-NshBvqY04knfqRESMQG:-NsrB_hX6kpxJEUziy15:b-kexjwg) ([raw file](https://github.com/starkware-libs/stwo/blob/86da9519c00ade8fee4f1690f51ac840ca535c77/src/core/poly/twiddles.rs#L36)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Right.
Should we add it to a further optimizations doc?
</blockquote></details>

No. It's really not worth it.


<!-- Sent from Reviewable.io -->

2024-03-13 11:10 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/401#-:-NsrVJWP3RaNt9moWfqk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-03-13 11:31 UTC, merged