evaluate_on_group
starkware-libs/stwo pull request #421
Opened 2024-03-01 17:12 UTC by spapinistarkware

2024-03-01 17:12 UTC, spapinistarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/421?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#421** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/421?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#420** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/420?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/421?utm_source=stack-comment).

2024-03-10 05:32 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsac-iK29umiik_nadW:-Nsac-iK29umiik_nadX:b-xyfgi5) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L162)):*
> ```XML
> // =========
> // Recall that a canonic line domain is the projection of only the ood points of a group. This is
> // used in the canonic fft. It is ordered as the bit-reverse of
> ```

"It is ordered as the bit-reverse of" this is referring to the order of C_n?
___
*[`src/core/backend/cpu/circle.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsabia56hSfVfJisAj3:-Nsabia56hSfVfJisAj4:b-ihq74w) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L163)):*
> ```XML
> // Recall that a canonic line domain is the projection of only the ood points of a group. This is
> // used in the canonic fft. It is ordered as the bit-reverse of
> //   ((4k+1)G_{n+2}).x for k=0..2^n .
> ```

((4k+1)G_{2^(n+2)}).x for k=0..2^n .?
___
*[`src/core/backend/cpu/circle.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsafDcsBTReB6cyFwIv:-NsafDcsBTReB6cyFwIw:bqzxch) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L186)):*
> ```XML
> // This transforms the evaluation buffer to:
> //   1, 0, C_1, C_2, ..., C_{n-1}, C_n
> // and stores the evaluation on -1 instead of the las evaluation.
> ```

What does this mean "and stores the evaluation on -1 instead of the las evaluation"?
___
*[`src/core/backend/cpu/circle.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsaiPVk8iMLIIOaiE5u:-NsaiPVk8iMLIIOaiE5v:b52q6em) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L249)):*
> ```XML
>                 // get an array.
>                 let (mut x, mut y) = (values[idx], values[idx + (1 << i)]);
>                 let twid = twiddles[h_point << 1];
> ```

Can we use full names for variables `twiddle`
___
*[`src/core/poly/circle/group.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsakj-aE6Aobyy4za6n:-Nsakj-aE6Aobyy4za6o:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/poly/circle/group.rs#L17)):*
> ```XML
>     }
> 
>     /// Gets the full coset represented G_{2n} + <G_n>.
> ```





_Suggestion:_
```XML
/// Gets the full coset represented <G_n>.
```
___
*[`src/core/poly/circle/group.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsakYr27L1AcqXY1uc8:-NsakYr27L1AcqXY1uc9:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/poly/circle/group.rs#L22)):*
> ```XML
>     }
> 
>     /// Returns the log size of the coset.
> ```





_Suggestion:_
```XML
/// Returns the log size of the group.
```
___
*[`src/core/poly/circle/group.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsakVq50QuBsjKWYK5G:-NsakVq50QuBsjKWYK5H:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/poly/circle/group.rs#L27)):*
> ```XML
>     }
> 
>     /// Returns the size of the coset.
> ```





_Suggestion:_
```XML
/// Returns the size of the group.
```
___
*[`src/core/utils.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsO7TaZBNcYiFE24J4I:-NsO7Ta_32sHac4ze7o2:b-76vc84) ([raw file](https://github.com/starkware-libs/stwo/blob/4119b026b99ab4b9a379d513861cd6596148b32f/src/core/utils.rs#L14)):*
> ```XML
> pub(crate) fn bit_reverse_index(i: usize, log_size: u32) -> usize {
>     if log_size == 0 {
>         return i;
> ```

Can this branch be in bit_reverse instead?


<!-- Sent from Reviewable.io -->

2024-03-10 06:25 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsac-iK29umiik_nadW:-Nsb-EJB7JaHmUkHn36V:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L162)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

"It is ordered as the bit-reverse of" this is referring to the order of C_n?
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsabia56hSfVfJisAj3:-Nsb-Phc98TkFkNRNDkS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L163)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

((4k+1)G_{2^(n+2)}).x for k=0..2^n .?
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsafDcsBTReB6cyFwIv:-Nsb0Edk5yDfAuomkFG3:b-bjpj7a) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L186)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

What does this mean "and stores the evaluation on -1 instead of the las evaluation"?
</blockquote></details>

Better?
___
*[`src/core/backend/cpu/circle.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsaiPVk8iMLIIOaiE5u:-Nsb0M053A4-gBkejSs8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L249)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can we use full names for variables `twiddle`
</blockquote></details>

Done.
___
*[`src/core/poly/circle/group.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsakj-aE6Aobyy4za6n:-Nsb103v4GAvySPyFa0X:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/poly/circle/group.rs#L17)):*
> ```XML
>     }
> 
>     /// Gets the full coset represented G_{2n} + <G_n>.
> ```

Done.
___
*[`src/core/poly/circle/group.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsakYr27L1AcqXY1uc8:-Nsb151iDuwFn_41OOTO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/poly/circle/group.rs#L22)):*
> ```XML
>     }
> 
>     /// Returns the log size of the coset.
> ```

Done.
___
*[`src/core/poly/circle/group.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsakVq50QuBsjKWYK5G:-Nsb14Gk0qEOKnTTEUEQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/poly/circle/group.rs#L27)):*
> ```XML
>     }
> 
>     /// Returns the size of the coset.
> ```

Done.
___
*[`src/core/utils.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsO7TaZBNcYiFE24J4I:-Nsb1AJhE26EEhm2oU47:b-3shywx) ([raw file](https://github.com/starkware-libs/stwo/blob/4119b026b99ab4b9a379d513861cd6596148b32f/src/core/utils.rs#L14)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can this branch be in bit_reverse instead?
</blockquote></details>

bit_reverse_index(i,0) should be supported. It makes sense. The only issue is that clippy gives a warning here.


<!-- Sent from Reviewable.io -->

2024-03-10 13:45 UTC, andrewmilson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421#-:-Nscb-Uo5__IWVv_VL-J:bnfp4nl)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsabia56hSfVfJisAj3:-Nsc_2QB6fSdRUF0DDLY:bka27zk) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L163)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Isn't it `G_{2^(n+2)}`?
___
*[`src/core/poly/circle/group_eval.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nscahv92Mwmy9ui7Y7K:-Nscahv92Mwmy9ui7Y7L:bhk0anu) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/poly/circle/group_eval.rs#L12)):*
> ```XML
> pub struct CircleGroupEvaluation<B: FieldOps<BaseField>> {
>     pub domain: Group,
>     pub values: Col<B, BaseField>,
> ```

Can these fields be private to not breaks the assumption domain and values have the same size.


<!-- Sent from Reviewable.io -->

2024-03-10 13:52 UTC, shaharsamocha7 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nscbusn9WRbJzHx9CU5:-Nscbusn9WRbJzHx9CU6:b32vww) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/backend/cpu/circle.rs#L147)):*
> ```XML
> // Group line domains:
> // =============
> // The line domain is formed by the x-projection of a size 2^(n+1) group. Itt is a set of 2^n + 1
> ```

It



_Code quote:_
```XML
Itt
```
___
*[`src/core/backend/cpu/circle.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsccXMi4h4sbpjgwJSo:-NsccXMi4h4sbpjgwJSp:b-hx5a1a) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/backend/cpu/circle.rs#L229)):*
> ```XML
>     poly: &CirclePoly<CPUBackend, BaseField>,
>     group: Group,
> ) -> CircleGroupEvaluation<CPUBackend> {
> ```

Does it mean that the FRI should be able to also get CircleGroupEvaluations?
Could it work if it has both CircleEvaluation of the same size?



_Code quote:_
```XML
CircleGroupEvaluation<CPUBackend>
```


<!-- Sent from Reviewable.io -->

2024-03-10 15:50 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nsabia56hSfVfJisAj3:-Nsd16xTDQe7RF7XWrJc:b7jc2no) ([raw file](https://github.com/starkware-libs/stwo/blob/314283680701a1c6cd201e74724d8b2c2befcc66/src/core/backend/cpu/circle.rs#L163)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Isn't it `G_{2^(n+2)}`?
</blockquote></details>

I changed all the definition in the code to state that G_n is a generator of order 2^n.
___
*[`src/core/backend/cpu/circle.rs` line 147 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nscbusn9WRbJzHx9CU5:-Nsd0zVb3pjJu8jnvT_z:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/backend/cpu/circle.rs#L147)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/circle.rs` line 229 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsccXMi4h4sbpjgwJSo:-Nsd1Cdx258DVf2EiIaF:bgromcs) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/backend/cpu/circle.rs#L229)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it mean that the FRI should be able to also get CircleGroupEvaluations?
Could it work if it has both CircleEvaluation of the same size?
</blockquote></details>

No. There are some nasty small details.
___
*[`src/core/poly/circle/group_eval.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nscahv92Mwmy9ui7Y7K:-Nsd1SP235kfvxtdJg2G:b-xl0kzs) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/poly/circle/group_eval.rs#L12)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can these fields be private to not breaks the assumption domain and values have the same size.
</blockquote></details>

The issue I have is that the concrete implementations are at each Backend, and they will want to take values and do something with it (for example, in constraint eval for a specific backend).


<!-- Sent from Reviewable.io -->

2024-03-10 17:15 UTC, shaharsamocha7 requested changes
> Reviewed 2 of 3 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 4 of 6 files reviewed, 12 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-NscnZC-2D6JjxN8jfFR:-NscnZC-2D6JjxN8jfFS:b-fg21g5) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/backend/cpu/circle.rs#L161)):*
> ```XML
> // Ordering:
> // =========
> // Recall that a canonic line domain is the projection of only the ood points of a group. This is
> ```

What do you mean by that?



_Code quote:_
```XML
ood points
```
___
*[`src/core/backend/cpu/circle.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsdKRiQ4hIKsrnCpCFn:-NsdKRiQ4hIKsrnCpCFo:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/d35ecef9afe8d8c2668881541f6e8ccb2ce824b1/src/core/backend/cpu/circle.rs#L193)):*
> ```XML
> // Combine using f(x,y) = f0(x) + y f1(x), where f0,f1 are given as
> // evaluations on L_{n}. Doing a butterfly will compute the evaluations on
> //   (1,+-0),(0,+-1),(1/sqrt(2),+-1/sqrt(2)),...,
> ```

?



_Suggestion:_
```XML
(1, 0)
```
___
*[`src/core/poly/circle/group_eval.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsdM3ej5j4rv6CD7mrN:-NsdM3ej5j4rv6CD7mrO:b-jy9hya) ([raw file](https://github.com/starkware-libs/stwo/blob/d35ecef9afe8d8c2668881541f6e8ccb2ce824b1/src/core/poly/circle/group_eval.rs#L8)):*
> ```XML
> 
> /// An evaluation defined on a [CircleDomain].
> /// The values are ordered according to the group tower ordering
> ```

Is this what you called above 'group circle domain'?



_Code quote:_
```XML
The values are ordered according to the group tower ordering
```


<!-- Sent from Reviewable.io -->

2024-03-11 05:54 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 4 of 6 files reviewed, 11 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/backend/cpu/circle.rs` line 161 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-NscnZC-2D6JjxN8jfFR:-Nsg38Vg7QNcw0xGjifO:bb7phvt) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/backend/cpu/circle.rs#L161)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What do you mean by that?
</blockquote></details>

typo
___
*[`src/core/backend/cpu/circle.rs` line 193 at r4](https://reviewable.io/reviews/starkware-libs/stwo/421#-NsdKRiQ4hIKsrnCpCFn:-Nsg3XHbD0nlXm0cBEYM:bb7lm0m) ([raw file](https://github.com/starkware-libs/stwo/blob/d35ecef9afe8d8c2668881541f6e8ccb2ce824b1/src/core/backend/cpu/circle.rs#L193)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

Is this clearer?


<!-- Sent from Reviewable.io -->

2024-03-12 02:56 UTC, andrewmilson requested changes
> Reviewed 2 of 3 files at r2, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/poly/circle/group_eval.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nscahv92Mwmy9ui7Y7K:-NskYt7d2KGO4jUwbMAe:b-or5mkh) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/poly/circle/group_eval.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The issue I have is that the concrete implementations are at each Backend, and they will want to take values and do something with it (for example, in constraint eval for a specific backend).
</blockquote></details>

Could it have an `into_values(self) -> Col<B, BaseField>` or deref to `Col<B, BaseField>` to achieve those goals?


<!-- Sent from Reviewable.io -->

2024-03-25 07:50 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @andrewmilson, @DavidLevitGurevich, and @shaharsamocha7)

___
*[`src/core/poly/circle/group_eval.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nscahv92Mwmy9ui7Y7K:-Nto_VkR4GSRt20JTclX:b-9zcsg3) ([raw file](https://github.com/starkware-libs/stwo/blob/a1401d6de4f90a102192c7a76c9dc116e696aeca/src/core/poly/circle/group_eval.rs#L12)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Could it have an `into_values(self) -> Col<B, BaseField>` or deref to `Col<B, BaseField>` to achieve those goals?
</blockquote></details>

I could, but it would have the same effect as having this field pub, only more difficult


<!-- Sent from Reviewable.io -->

2024-03-26 04:48 UTC, andrewmilson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r3, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421#-:-Ntt4_qm6bPMQHNaovTP:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @DavidLevitGurevich and @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-03-27 10:52 UTC, DavidLevitGurevich reviewed
> Reviewed 2 of 3 files at r2, 2 of 3 files at r3, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 201 at r5](https://reviewable.io/reviews/starkware-libs/stwo/421#-NtzWxcV9sc8xCk9fnYM:-NtzWxcV9sc8xCk9fnYN:bmulvm7) ([raw file](https://github.com/starkware-libs/stwo/blob/f16b68dc8c83e8773d31354863b9bcc5987b5f25/src/core/backend/cpu/circle.rs#L201)):*
> ```XML
> pub fn ordered_group_line_domain(log_size: u32) -> Vec<CirclePoint<BaseField>> {
>     let mut points = vec![CirclePointIndex::zero().to_point()];
>     for log_size in 0..log_size {
> ```

is this naming conflict intentional?


<!-- Sent from Reviewable.io -->

2024-03-27 13:08 UTC, DavidLevitGurevich reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/421)* status: all files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/cpu/circle.rs` line 214 at r5](https://reviewable.io/reviews/starkware-libs/stwo/421#-Nu-00mq0QcDXznVSaqp:-Nu-00mq0QcDXznVSaqq:bif4h4s) ([raw file](https://github.com/starkware-libs/stwo/blob/f16b68dc8c83e8773d31354863b9bcc5987b5f25/src/core/backend/cpu/circle.rs#L214)):*
> ```XML
>     let mut points = vec![
>         CirclePointIndex::zero().to_point(),
>         CirclePointIndex::subgroup_gen(1).to_point(),
> ```

the doc talks about points on the line, here I see points on the circle, maybe need to add a line of doc next to each function to state explicitly what it does


<!-- Sent from Reviewable.io -->

2025-11-19 11:12 UTC, closed without merging