FRI in Commitment Scheme
starkware-libs/stwo pull request #476
Opened 2024-03-14 08:57 UTC by spapinistarkware

2024-03-14 08:58 UTC, spapinistarkware commented
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-17 12:04 UTC, alonh5 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBHGch37MvwYLHk4G1:-NtBHGciBDO8qsOjIEQc:bvpcc1b) (no related file):*
Can you please split this PR into smaller chunks?

___
___
*[`src/core/mod.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBEQqN4GpPJiyUM_8F:-NtBEQqODA0v2fSxgPfW:bqbymoa) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/mod.rs#L21)):*
> ```XML
> /// A vector of [ColumnVec]s. Each [ColumnVec] relates (by index) to a component in the air.
> #[derive(Debug, Clone)]
> pub struct ComponentVec<T>(pub Vec<ColumnVec<T>>);
> ```

You should rebase over dev this chage is already merged. Also implemented `Deref` and `MutDeref` so you can remove the `.0`'s
___
*[`src/core/commitment_scheme/mod.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBExnHCXSFC8sxMz-t:-NtBExnHCXSFC8sxMz-u:bjav7n0) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/commitment_scheme/mod.rs#L1)):*
> ```XML
> //! Implements a FRI polynomial commitment scheme.
> ```

Specifically you please split the file rename and the changes into separate PRs? It's difficult to review like this.
___
*[`src/core/fields/cm31.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBFU-BEOYhwPNdP3LT:-NtBFU-BEOYhwPNdP3LU:b-c15awp) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/fields/cm31.rs#L37)):*
> ```XML
> }
> 
> impl Debug for CM31 {
> ```

Call display instead of duplicating?
___
*[`src/core/fields/qm31.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBFmayBcH6PGfQB-gG:-NtBFmaz0LWT5BxPr1Km:blm76ua) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/fields/qm31.rs#L46)):*
> ```XML
> }
> 
> impl Display for QM31 {
> ```

Implement also for M31?
___
*[`src/core/prover/mod.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBGW1dCIYyEF-e7W8j:-NtBGW1dCIYyEF-e7W8k:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/prover/mod.rs#L69)):*
> ```XML
>     );
> 
>     // Add composiion poly points.
> ```





_Suggestion:_
```XML
// Add composition poly points.
```


<!-- Sent from Reviewable.io -->

2024-03-17 12:36 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`src/core/mod.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBEQqN4GpPJiyUM_8F:-NtBLthjECuuIYZwkgt0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/mod.rs#L21)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You should rebase over dev this chage is already merged. Also implemented `Deref` and `MutDeref` so you can remove the `.0`'s
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBExnHCXSFC8sxMz-t:-NtBPIyq0yD3FhI7RBu2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/commitment_scheme/mod.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Specifically you please split the file rename and the changes into separate PRs? It's difficult to review like this.
</blockquote></details>

Done.
___
*[`src/core/fields/cm31.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBFU-BEOYhwPNdP3LT:-NtBOj-cDS0PIV96v7sp:b35froi) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/fields/cm31.rs#L37)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Call display instead of duplicating?
</blockquote></details>

Still one line, but adds a hop to the reader. Dont think it's worth it.
___
*[`src/core/fields/qm31.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBFmayBcH6PGfQB-gG:-NtBP47o-IJtveQo-v8e:b-a22r36) ([raw file](https://github.com/starkware-libs/stwo/blob/7ece89bfa706e562012b9eb55c5482588d109f00/src/core/fields/qm31.rs#L46)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Implement also for M31?
</blockquote></details>

I think M31() is a good debug for it. Just printing a number would not distinguish it from a number.


<!-- Sent from Reviewable.io -->

2024-03-17 12:47 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtBHGch37MvwYLHk4G1:-NtBS3zlDLbBhAav7cx1:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you please split this PR into smaller chunks?
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-03-20 09:46 UTC, alonh5 requested changes
> Reviewed 1 of 3 files at r4, 4 of 7 files at r6, 1 of 5 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 8 of 10 files reviewed, 15 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/mod.rs` line 27 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtM3-wMDavEIcT1m2qW:-NtM3-wMDavEIcT1m2qX:bbduuhy) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/mod.rs#L27)):*
> ```XML
> impl<T: Clone> ComponentVec<T> {
>     pub fn flatten(&self) -> ColumnVec<T> {
>         self.iter().flatten().cloned().collect()
> ```

Are we okay with cloning things? What if it's a circle evaluation for example?
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtPvSvz8pE2I-MT77gk:-NtPvSw-3MSW_b_mwwon:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L42)):*
> ```XML
> type ProofChannel = Blake2sChannel;
> 
> /// The prover size of a FRI polynomial commitment scheme. See [self].
> ```





_Suggestion:_
```XML
side
```
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtPvli92FXFO56_LsZz:-NtPvli92FXFO56_Ls_-:b-ane1c4) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L42)):*
> ```XML
> type ProofChannel = Blake2sChannel;
> 
> /// The prover size of a FRI polynomial commitment scheme. See [self].
> ```

What is this supposed to point at?
Same below.



_Code quote:_
```XML
See [self]
```
___
*[`src/core/commitment_scheme/mod.rs` line 65 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtM3vtz8IkT7IVL3zNy:-NtM3vtz8IkT7IVL3zNz:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L65)):*
> ```XML
>     }
> 
>     pub fn polys(&self) -> TreeVec<ColumnVec<&CPUCirclePoly>> {
> ```





_Suggestion:_
```XML
polynomials(&self)
```
___
*[`src/core/commitment_scheme/mod.rs` line 77 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ4Ue17wWVSJv0gnnu:-NtQ4Ue17wWVSJv0gnnv:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L77)):*
> ```XML
>     }
> 
>     pub fn open_values(
> ```





_Suggestion:_
```XML
prove_values
```
___
*[`src/core/commitment_scheme/mod.rs` line 6 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ9LD86Xcy-vbSB0J5:-NtQ9LD86Xcy-vbSB0J6:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L6)):*
> ```XML
> //! Note: This implementation is not really a polynomial commitment scheme, because we are not in
> //! the unique decoding regime. This is enough for a STARK proof though, where we onyl want to imply
> //! the existence of such polynomials, and re ok with having a small decoding list.
> ```





_Suggestion:_
```XML
//! the unique decoding regime. This is enough for a STARK proof though, where we only want to imply
//! the existence of such polynomials, and are ok with having a small decoding list.
```
___
*[`src/core/commitment_scheme/mod.rs` line 152 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ6ZKbCeGKezjljroh:-NtQ6ZKbCeGKezjljroi:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L152)):*
> ```XML
> 
> /// Prover data for a single commitment tree in a commitment scheme. The commitment scheme allows to
> /// commit on a set polynomials at a time. This corresponds to such a set.
> ```





_Suggestion:_
```XML
set of polynomials
```
___
*[`src/core/commitment_scheme/mod.rs` line 227 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ55Y-BXdd8MuLHA7h:-NtQ55Y-BXdd8MuLHA7i:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L227)):*
> ```XML
>     }
> 
>     /// A [TreeVec<ColumnVec] of the log sizes of each column in each commitment tree.
> ```





_Suggestion:_
```XML
TreeVec<ColumnVec>
```
___
*[`src/core/commitment_scheme/mod.rs` line 243 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ5LuZ0WcMYbBvyY3R:-NtQ5LuZ0WcMYbBvyY3S:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L243)):*
> ```XML
>     }
> 
>     pub fn verify_opening(
> ```





_Suggestion:_
```XML
verify_values
```
___
*[`src/core/commitment_scheme/mod.rs` line 251 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ7IxMDxggRLoZd4cU:-NtQ7IxMDxggRLoZd4cV:b-2uc5ym) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L251)):*
> ```XML
>         channel.mix_felts(&proof.opened_values.clone().flatten_cols());
> 
>         // Compute degree bounds for oods quotients without looking at the proof.
> ```

Same below.



_Suggestion:_
```XML
OODS
```
___
*[`src/core/commitment_scheme/mod.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ8eKT9zrsjM9Y9O4N:-NtQ8eKT9zrsjM9Y9O4O:b-82f8uh) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L253)):*
> ```XML
>         // Compute degree bounds for oods quotients without looking at the proof.
>         let bounds = self
>             .column_log_sizes()
> ```

Are you assuming these are ordered?
TAL at how it's done in `quotient_log_bounds()`, and after that it can be removed.



_Code quote:_
```XML
.column_log_sizes()
```
___
*[`src/core/commitment_scheme/mod.rs` line 280 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQBgxV0N5jqyN3rkXJ:-NtQBgxV0N5jqyN3rkXK:b-2uc5ym) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L280)):*
> ```XML
>                 tree.verify(
>                     decommitment,
>                     &fri_query_domains[&(tree.log_sizes[0] + 1)].flatten(),
> ```

Same below.



_Suggestion:_
```XML
 LOG_BLOWUP_FACTOR
```
___
*[`src/core/commitment_scheme/mod.rs` line 328 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQE58vEGSJQDx7TjSe:-NtQE58w9Pl-cwqsuiep:bad60e9) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L328)):*
> ```XML
>     value: SecureField,
> ) -> SparseCircleEvaluation<SecureField> {
>     let queried_values = &mut queried_values.clone().into_iter();
> ```

Is this necessary?



_Code quote:_
```XML
.clone()
```
___
*[`src/core/commitment_scheme/mod.rs` line 341 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQEQAk5988MEackLrt:-NtQEQAk5988MEackLru:bqf94qz) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L341)):*
> ```XML
>             .collect(),
>     );
>     assert!(queried_values.is_empty());
> ```

Add message.



_Code quote:_
```XML
assert!(queried_values.is_empty());
```
___
*[`src/core/prover/mod.rs` line 68 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQEhIk4g49Bbkdy5T0:-NtQEhIk4g49Bbkdy5T1:b-s3o7k) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/prover/mod.rs#L68)):*
> ```XML
>     let mut open_points = TreeVec::new(vec![open_points.flatten()]);
>     // Second tree - composition polynomial.
>     open_points.0.push(vec![vec![oods_point]; 4]);
> ```

Remove whereve [...]

2024-03-20 11:29 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 8 of 10 files reviewed, 10 unresolved discussions (waiting on @alonh5)

___
*[`src/core/mod.rs` line 27 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtM3-wMDavEIcT1m2qW:-NtQYSox-SYNyGerLv4c:b-errpoh) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/mod.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are we okay with cloning things? What if it's a circle evaluation for example?
</blockquote></details>

We're not ok with this, no.
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtPvli92FXFO56_LsZz:-NtQZmVr8jBtyl30TMp6:bra7vp2) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L42)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What is this supposed to point at?
Same below.
</blockquote></details>

The module doc.
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtPvSvz8pE2I-MT77gk:-NtQZoUk7LHUAGfMJdn1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L42)):*
> ```XML
> type ProofChannel = Blake2sChannel;
> 
> /// The prover size of a FRI polynomial commitment scheme. See [self].
> ```

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 6 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ9LD86Xcy-vbSB0J5:-NtQ_kmH1KM4zZ_1VHft:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L6)):*
> ```XML
> //! Note: This implementation is not really a polynomial commitment scheme, because we are not in
> //! the unique decoding regime. This is enough for a STARK proof though, where we onyl want to imply
> //! the existence of such polynomials, and re ok with having a small decoding list.
> ```

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 152 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ6ZKbCeGKezjljroh:-NtQZxyO0KqzMDtOi6Ti:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L152)):*
> ```XML
> 
> /// Prover data for a single commitment tree in a commitment scheme. The commitment scheme allows to
> /// commit on a set polynomials at a time. This corresponds to such a set.
> ```

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 251 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ7IxMDxggRLoZd4cU:-NtQ_3c14UIHQ53yKUH9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L251)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQ8eKT9zrsjM9Y9O4N:-NtQ_Dfs5SlsHLF_d8Ng:blaa9mx) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L253)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are you assuming these are ordered?
TAL at how it's done in `quotient_log_bounds()`, and after that it can be removed.
</blockquote></details>

It's gonna change in a few PRs anyway. I'll gather them up by size.
___
*[`src/core/commitment_scheme/mod.rs` line 280 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQBgxV0N5jqyN3rkXJ:-NtQ_R864j8B33ZjAqKp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L280)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 341 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQEQAk5988MEackLrt:-NtQ_cj3AaTjae-G5z3U:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/commitment_scheme/mod.rs#L341)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add message.
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 68 at r10](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQEhIk4g49Bbkdy5T0:-NtQ_jnZ-8n04uLyHmyg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2b6222fa4eec251478ad3a02fa9bfc2211f5d75/src/core/prover/mod.rs#L68)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove wherever possible.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-20 11:55 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 3 files at r4, 4 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 6 of 11 files reviewed, 16 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/commitment_scheme/mod.rs` line 3 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQg4823IdjqYuCx2we:-NtQg4823IdjqYuCx2wf:b-5l3r8i) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L3)):*
> ```XML
> //! Implements a FRI polynomial commitment scheme.
> //! This is a protocol where the prover can commit on a set of polynomials and then prove their
> //! opening on a set of points.
> ```

Mention that we can open points from the domain



_Code quote:_
```XML
//! This is a protocol where the prover can commit on a set of polynomials and then prove their
//! opening on a set of points.
```
___
*[`src/core/commitment_scheme/mod.rs` line 43 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQh1pb61KIOy-ukEni:-NtQh1pb61KIOy-ukEnj:b-dn65iq) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L43)):*
> ```XML
> 
> /// The prover side of a FRI polynomial commitment scheme. See [self].
> pub struct CommitmentSchemeProver {
> ```

Document.
Commitment of multiple polynomials (could be of different degrees?)



_Code quote:_
```XML
pub struct CommitmentSchemeProver {
```
___
*[`src/core/commitment_scheme/mod.rs` line 105 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQgPKBD5_2DrHZs-t-:-NtQgPKBD5_2DrHZs-t0:b-ayw4rd) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L105)):*
> ```XML
>                     })
>                     .collect_vec()
>             });
> ```

Should this use batch_inverse?



_Code quote:_
```XML
        let quotients = self
            .evaluations()
            .zip_cols(&opened_values)
            .zip_cols(&open_points)
            .map_cols(|((evaluation, values), points)| {
                zip(points, values)
                    .map(|(&point, &value)| {
                        get_pair_oods_quotient(point, value, evaluation).bit_reverse()
                    })
                    .collect_vec()
            });
```
___
*[`src/core/commitment_scheme/mod.rs` line 108 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQgXVD8hmqln8X6XPp:-NtQgXVD8hmqln8X6XPq:b6k4f80) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L108)):*
> ```XML
> 
>         // Run FRI commitment phase on the oods quotients.
>         let fri_config = FriConfig::new(LOG_LAST_LAYER_DEGREE_BOUND, LOG_BLOWUP_FACTOR, N_QUERIES);
> ```

Consider moving configs to the top of the function



_Code quote:_
```XML
        // Run FRI commitment phase on the oods quotients.
        let fri_config = FriConfig::new(LOG_LAST_LAYER_DEGREE_BOUND, LOG_BLOWUP_FACTOR, N_QUERIES);
```
___
*[`src/core/commitment_scheme/mod.rs` line 248 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQhUB47hPXaWROp8yT:-NtQhUB47hPXaWROp8yU:b-v6oc52) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L248)):*
> ```XML
>         proof: CommitmentSchemeProof,
>         channel: &mut ProofChannel,
>     ) -> bool {
> ```

This should return an error?



_Code quote:_
```XML
) -> bool {
```
___
*[`src/core/commitment_scheme/mod.rs` line 321 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQhe7F47r8q_t39VCh:-NtQhe7GCL9JejfzHIbV:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L321)):*
> ```XML
> }
> 
> fn eval_quotients_on_sparse_domain(
> ```

Document



_Code quote:_
```XML
fn eval_quotients_on_sparse_domain(
```


<!-- Sent from Reviewable.io -->

2024-03-20 11:59 UTC, alonh5 requested changes
> Reviewed 3 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 9 of 11 files reviewed, 10 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/mod.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQd3OTDIey7WYSJzY-:-NtQd3OTDIey7WYSJzY0:bov4kku) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/mod.rs#L32)):*
> ```XML
> 
> impl<T> ComponentVec<ColumnVec<T>> {
>     pub fn flatten_all(self) -> Vec<T> {
> ```

For consistency. 



_Suggestion:_
```XML
flatten_cols
```
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtPvli92FXFO56_LsZz:-NtQc_5j2_PIL_wnVpjI:bcr5s31) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L42)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The module doc.
</blockquote></details>

Got it, thanks.
___
*[`src/core/commitment_scheme/mod.rs` line 144 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQezPfBuHoY9ReBGMq:-NtQezPfBuHoY9ReBGMr:b-brnanb) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L144)):*
> ```XML
> 
> pub struct CommitmentSchemeProof {
>     pub opened_values: TreeVec<ColumnVec<Vec<SecureField>>>,
> ```

The `open` notion is a bit confusing to me, can we change it to `prove` everywhere related?
Also maybe add documentation for the fields here.



_Suggestion:_
```XML
pub proved_values: TreeVec<ColumnVec<Vec<SecureField>>>,
```
___
*[`src/core/commitment_scheme/mod.rs` line 283 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQhKo_4eoWSS-KXG3I:-NtQhKo_4eoWSS-KXG3J:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L283)):*
> ```XML
>                 )
>             })
>             .0
> ```




<!-- Sent from Reviewable.io -->

2024-03-20 12:14 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 9 of 11 files reviewed, 10 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/commitment_scheme/mod.rs` line 3 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQg4823IdjqYuCx2we:-NtQm8wn11hHcleknhay:brj4vnr) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Mention that we can open points from the domain
</blockquote></details>

Can't?


<!-- Sent from Reviewable.io -->

2024-03-20 12:25 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/mod.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQd3OTDIey7WYSJzY-:-NtQlkF7EojpcinRKexc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/mod.rs#L32)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

For consistency.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r9](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtPvli92FXFO56_LsZz:-NtQl684BZEgYiW4aGqA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ad97f401f41906a5183c5d112c6b62069ff57226/src/core/commitment_scheme/mod.rs#L42)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Got it, thanks.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 3 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQg4823IdjqYuCx2we:-NtQl5Ya-SzNJ2vCQxf2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Mention that we can open points from the domain
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 43 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQh1pb61KIOy-ukEni:-NtQl8-l9I-iKxvONSNF:b-m0q555) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L43)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document.
Commitment of multiple polynomials (could be of different degrees?)
</blockquote></details>

I doced in the module level, and referenced form here
___
*[`src/core/commitment_scheme/mod.rs` line 105 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQgPKBD5_2DrHZs-t-:-NtQlDZp-zjc62zlo0XC:bvsol1j) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should this use batch_inverse?
</blockquote></details>

Later.
___
*[`src/core/commitment_scheme/mod.rs` line 108 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQgXVD8hmqln8X6XPp:-NtQlJ1U6LgVyefsAWLj:b7vn9wm) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L108)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider moving configs to the top of the function
</blockquote></details>

Noted. This is constructed right before using it => in FRI.
___
*[`src/core/commitment_scheme/mod.rs` line 144 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQezPfBuHoY9ReBGMq:-NtQlVjG8WXsI6-K1AkS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L144)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The `open` notion is a bit confusing to me, can we change it to `prove` everywhere related?
Also maybe add documentation for the fields here.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 248 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQhUB47hPXaWROp8yT:-NtQlWkX2LuwMIIjUfWm:bb77ufg) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L248)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should return an error?
</blockquote></details>

Yes.
___
*[`src/core/commitment_scheme/mod.rs` line 321 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQhe7F47r8q_t39VCh:-NtQle4B5R_cd9U-KI-D:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L321)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-20 12:43 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 7 of 11 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/commitment_scheme/mod.rs` line 3 at r11](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQg4823IdjqYuCx2we:-NtQsu3u5QGq6kz02Z1n:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7a3c8ecc328da89b07f8615fe0307b53c0bc6dab/src/core/commitment_scheme/mod.rs#L3)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-20 13:15 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 10 of 11 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/commitment_scheme/mod.rs` line 293 at r12](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtQtLq564MspkhYJoZL:-NtR-2zZ6fowVefu16Me:b2nhky0) ([raw file](https://github.com/starkware-libs/stwo/blob/3d2e05e835b942eaca024f1769264b843bf4afeb/src/core/commitment_scheme/mod.rs#L293)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do you think all these `collect()`s (in `zip_cols`, `map_cols` etc.) are going be costly? If so maybe add a TODO to consider a refactor of this code chunk?
</blockquote></details>

No.


<!-- Sent from Reviewable.io -->

2024-03-20 14:21 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Non-blocking comments on tests, for next PR.

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476#-:-NtRDvvf2_jY7e4IBaZF:b-gqsm84)* status: all files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/fibonacci/mod.rs` line 165 at r13](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtRBqSD-wB8NN7xUfPH:-NtRBqSD-wB8NN7xUfPI:bqni4bg) ([raw file](https://github.com/starkware-libs/stwo/blob/ee9615850e21b3554d8c5d3a6306a7d21830a158/src/fibonacci/mod.rs#L165)):*
> ```XML
> 
>     #[test]
>     fn test_oods_quotients_are_low_degree() {
> ```

This test was to check the oods quotients are low degree (because when we only excluded one point and not a pair it wasn't), not that the CP is low degree.
___
*[`src/fibonacci/mod.rs` line 226 at r13](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtRCdidDS_4yHQukYJ2:-NtRCdidDS_4yHQukYJ3:b-f99ypb) ([raw file](https://github.com/starkware-libs/stwo/blob/ee9615850e21b3554d8c5d3a6306a7d21830a158/src/fibonacci/mod.rs#L226)):*
> ```XML
>         let trace = fib.get_trace();
>         let trace_poly = trace.interpolate();
>         let _trace = ComponentTrace::new(vec![&trace_poly]);
> ```

You can remove these.
___
*[`src/fibonacci/mod.rs` line 254 at r13](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtRDFSC3EcwJoqcWZFo:-NtRDFSC3EcwJoqcWZFp:b-hf34kt) ([raw file](https://github.com/starkware-libs/stwo/blob/ee9615850e21b3554d8c5d3a6306a7d21830a158/src/fibonacci/mod.rs#L254)):*
> ```XML
>             .commitment_scheme_proof
>             .proved_values
>             .0
> ```

You can now remove these too.



_Code quote:_
```XML
.0
```


<!-- Sent from Reviewable.io -->

2024-03-21 04:58 UTC, shaharsamocha7 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-03-21 07:21 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/476)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/fibonacci/mod.rs` line 165 at r13](https://reviewable.io/reviews/starkware-libs/stwo/476#-NtRBqSD-wB8NN7xUfPH:-NtUpyWuCEBKr9VxAmbn:b-a0es53) ([raw file](https://github.com/starkware-libs/stwo/blob/ee9615850e21b3554d8c5d3a6306a7d21830a158/src/fibonacci/mod.rs#L165)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This test was to check the oods quotients are low degree (because when we only excluded one point and not a pair it wasn't), not that the CP is low degree.
</blockquote></details>

So it should be in oods.rs. I put one there.


<!-- Sent from Reviewable.io -->

2024-03-21 07:27 UTC, merged

2024-03-21 07:27 UTC, spapinistarkware commented
### Merge activity

* **Mar 21, 3:27 AM EDT**: @spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/476).