Get lookup columns.
starkware-libs/stwo pull request #572
Opened 2024-04-09 09:43 UTC by alonh5

2024-04-09 09:44 UTC, alonh5 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-15 08:24 UTC, spapinistarkware requested changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/examples/wide_fibonacci/structs.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvVqjBV-8U8r06i_8kf:-NvVqjBV-8U8r06i_8kg:bsa0l1s) ([raw file](https://github.com/starkware-libs/stwo/blob/8db68f68e872e33b949cf8c692fe80f5516091cf/src/examples/wide_fibonacci/structs.rs#L48)):*
> ```XML
>         let zero_vec = vec![BaseField::zero(); n_rows];
>         let mut dst = vec![zero_vec; LOG_N_ROWS];
>         write_lookup_column(&mut dst[0], trace, 0, alpha, z);
> ```

I don't understand. dst is fo size 2^log_n_rows. Why are you accessing it at 0 and 1?



_Code quote:_
```XML
&mut dst[0]
```
___
*[`src/examples/wide_fibonacci/structs.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvVqcOf66aEVGWeUUQ1:-NvVqcOf66aEVGWeUUQ2:b-x6b1kv) ([raw file](https://github.com/starkware-libs/stwo/blob/8db68f68e872e33b949cf8c692fe80f5516091cf/src/examples/wide_fibonacci/structs.rs#L49)):*
> ```XML
>         let mut dst = vec![zero_vec; LOG_N_ROWS];
>         write_lookup_column(&mut dst[0], trace, 0, alpha, z);
>         write_lookup_column(&mut dst[1], trace, N_COLUMNS - 2, alpha, z);
> ```

Isn't this out of bounds?



_Code quote:_
```XML
N_COLUMNS - 2
```
___
*[`src/examples/wide_fibonacci/trace_gen.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvVqNLfCdo78ZE6-2RB:-NvVqNLfCdo78ZE6-2RC:b-l50m2e) ([raw file](https://github.com/starkware-libs/stwo/blob/8db68f68e872e33b949cf8c692fe80f5516091cf/src/examples/wide_fibonacci/trace_gen.rs#L146)):*
> ```XML
> }
> 
> pub fn write_lookup_column(
> ```

What are these lookup expressions?


<!-- Sent from Reviewable.io -->

2024-04-17 12:58 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/examples/wide_fibonacci/structs.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvVqjBV-8U8r06i_8kf:-Nvg7QbO9ajW_vvejW6H:b-p1bgja) ([raw file](https://github.com/starkware-libs/stwo/blob/8db68f68e872e33b949cf8c692fe80f5516091cf/src/examples/wide_fibonacci/structs.rs#L48)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand. dst is fo size 2^log_n_rows. Why are you accessing it at 0 and 1?
</blockquote></details>

You're right `LOG_N_ROWS` was a mistake, I changed it to 2.
___
*[`src/examples/wide_fibonacci/structs.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvVqcOf66aEVGWeUUQ1:-Nvg7UFZDIPUjcslQqFi:b-x7uec4) ([raw file](https://github.com/starkware-libs/stwo/blob/8db68f68e872e33b949cf8c692fe80f5516091cf/src/examples/wide_fibonacci/structs.rs#L49)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Isn't this out of bounds?
</blockquote></details>

This is the index of the trace column (the first of the two) of which to do a partial products, so it's the second to last index.
___
*[`src/examples/wide_fibonacci/trace_gen.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvVqNLfCdo78ZE6-2RB:-Nvg6x_hC6JU4ODz2NfS:b7e5z52) ([raw file](https://github.com/starkware-libs/stwo/blob/8db68f68e872e33b949cf8c692fe80f5516091cf/src/examples/wide_fibonacci/trace_gen.rs#L146)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What are these lookup expressions?
</blockquote></details>

This is creating two columns of partial products of the first and last two columns respectively.


<!-- Sent from Reviewable.io -->

2024-04-18 08:36 UTC, shaharsamocha7 requested changes
> Reviewed 4 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvkL3230r0YSey_mk8c:-NvkL3244GgcMz6hnD_v:b-gdg1oh) ([raw file](https://github.com/starkware-libs/stwo/blob/52a2d916fe47babd5bedbcbfbe2a607c8a1b6fe0/crates/prover/src/examples/wide_fibonacci/component.rs#L12)):*
> ```XML
> pub const LOG_N_COLUMNS: usize = 8;
> pub const N_COLUMNS: usize = 1 << LOG_N_COLUMNS;
> pub const LOG_N_ROWS: usize = 4;
> ```

Why is it here? Is it only for the test?



_Code quote:_
```XML
pub const LOG_N_ROWS: usize = 4;
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvkL83R497oDBzG4Yvd:-NvkL83S4wZqkjXWRqe_:b-2ibqb1) ([raw file](https://github.com/starkware-libs/stwo/blob/52a2d916fe47babd5bedbcbfbe2a607c8a1b6fe0/crates/prover/src/examples/wide_fibonacci/component.rs#L74)):*
> ```XML
> pub fn lookup_columns(
>     trace: &[Vec<BaseField>],
>     // TODO(AlonH): Change alpha and z to SecureField.
> ```

Are those going to be simulated with 4 base field columns?



_Code quote:_
```XML
    // TODO(AlonH): Change alpha and z to SecureField.
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvkLOT71NVEt8uD0WA-:-NvkLOT89so6zHr2AKIO:b7nucdl) ([raw file](https://github.com/starkware-libs/stwo/blob/01cab65559adcd0a14002fe8da28d4c6abdc1bfe/crates/prover/src/examples/wide_fibonacci/component.rs#L81)):*
> ```XML
>     let zero_vec = vec![BaseField::zero(); n_rows];
>     let mut dst = vec![zero_vec; 2];
>     write_lookup_column(&mut dst[0], trace, 0, alpha, z);
> ```

Maybe this function should declare and return dst, instead of getting a pointer



_Code quote:_
```XML
write_lookup_column(&mut dst[0], trace, 0, alpha, z);
```


<!-- Sent from Reviewable.io -->

2024-04-18 09:06 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvkL3230r0YSey_mk8c:-NvkPNQV5wVPlUVPjNcT:b32n8ta) ([raw file](https://github.com/starkware-libs/stwo/blob/52a2d916fe47babd5bedbcbfbe2a607c8a1b6fe0/crates/prover/src/examples/wide_fibonacci/component.rs#L12)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is it here? Is it only for the test?
</blockquote></details>

Removed it.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvkL83R497oDBzG4Yvd:-NvkPRmF1BezcCyYKk8f:b-o6b981) ([raw file](https://github.com/starkware-libs/stwo/blob/52a2d916fe47babd5bedbcbfbe2a607c8a1b6fe0/crates/prover/src/examples/wide_fibonacci/component.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Are those going to be simulated with 4 base field columns?
</blockquote></details>

Yes I think so.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvkLOT71NVEt8uD0WA-:-NvkS9lVDk0RI0o5J9TA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/01cab65559adcd0a14002fe8da28d4c6abdc1bfe/crates/prover/src/examples/wide_fibonacci/component.rs#L81)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe this function should declare and return dst, instead of getting a pointer
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 14:36 UTC, shaharsamocha7 reviewed
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-04-21 06:09 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzFuNF5jQ2l7Wid8pN:-NvzFuNF5jQ2l7Wid8pO:b7uxeaa) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L40)):*
> ```XML
>     pub fn assert_constraints_on_lookup_column(
>         column: &[BaseField],
>         input_trace: &[Vec<BaseField>],
> ```

Can you add an assert that the column is of the same length of the trace?



_Code quote:_
```XML
        column: &[BaseField],
        input_trace: &[Vec<BaseField>],
```
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzGKj57V615MqaR9le:-NvzGKj6C5bv1RBbKvBq:btnrx0u) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L66)):*
> ```XML
>                     / (input_trace[0][0] + alpha * input_trace[1][0] - z)),
>             BaseField::one()
>         );
> ```

I'm a bit confused, can you explain this assert?



_Code quote:_
```XML
        assert_eq!(
            column[column_length - 1]
                * ((input_trace[n_columns - 2][column_length - 1]
                    + alpha * input_trace[n_columns - 1][column_length - 1]
                    - z)
                    / (input_trace[0][0] + alpha * input_trace[1][0] - z)),
            BaseField::one()
        );
```
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzFH8pA1DVoGwZO7uf:-NvzFH8pA1DVoGwZO7ug:baxo6yx) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L91)):*
> ```XML
>     fn test_lookup_column_constraints() {
>         let wide_fib = WideFibComponent {
>             log_fibonacci_size: 4 + LOG_N_COLUMNS as u32,
> ```

What's the +4 here?
and should we change it to have more than 1 instance?



_Code quote:_
```XML
log_fibonacci_size: 4 + LOG_N_COLUMNS as u32,
```
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzExt05Kc7vGKJ3SBD:-NvzExt19PxLMsGf7S_A:bxxfpsf) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L35)):*
> ```XML
>     (0..n_rows)
>         .map(|i| {
>             let numerator = input_trace[0][i] + alpha * input_trace[1][i] - z;
> ```

Can you move this logic to a separated function?



_Code quote:_
```XML
input_trace[0][i] + alpha * input_trace[1][i] - z;
```


<!-- Sent from Reviewable.io -->

2024-04-24 08:34 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEE9VEAPMU8B9Jygeu:-NwEE9VEAPMU8B9Jygev:bjhazkc) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/mod.rs#L52)):*
> ```XML
>                 *cell,
>                 ((combine(input_trace[0][i], input_trace[1][i], alpha, z))
>                     / (combine(
> ```

Multiply both sides by the denominator, to avoid division in the check.
Below as well.


<!-- Sent from Reviewable.io -->

2024-04-24 08:34 UTC, spapinistarkware reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: all files reviewed, 8 unresolved discussions (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2024-04-25 08:47 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: all files reviewed, 9 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEDifc9Nx6-7szT9Tc:-NwJQzhq-u6JJGAYA1c9:byslwfu) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L42)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think this might hurt the performance of wide fib. Perhaps we should use batch inverse here.
@shaharsamocha7  wdyt?
</blockquote></details>

Agree, but this can done in another pr.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwJQwPV8hhHubUebqPZ:-NwJQwPWE84872LQEQ6e:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
> ```XML
> }
> 
> pub fn combine(
> ```

Document



_Code quote:_
```XML
pub fn combine(
```


<!-- Sent from Reviewable.io -->

2024-04-25 11:50 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: all files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzFuNF5jQ2l7Wid8pN:-Nvzhtyz69yNKx_0f8Ha:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L40)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add an assert that the column is of the same length of the trace?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzGKj57V615MqaR9le:-NvznbXx8OtzD-Z-46nr:bm57rft) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm a bit confused, can you explain this assert?
</blockquote></details>

I made it clearer and added documentation.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzFH8pA1DVoGwZO7uf:-NvziwQy9Zh2wImMR2M1:b-n4soie) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L91)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's the +4 here?
and should we change it to have more than 1 instance?
</blockquote></details>

We talked about only supporting one long instance or multiple short (one row length) instances. We can add support to multiple long instances later with the other type of lookup you suggested.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzExt05Kc7vGKJ3SBD:-NvzjaOuDWbvk-QOB_Sd:bmiskcq) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L35)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you move this logic to a separated function?
</blockquote></details>

Yes, good idea.


<!-- Sent from Reviewable.io -->

2024-04-25 12:44 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzGKj57V615MqaR9le:-NwKGyL5CkSMWQ76Yafx:b-d2bkt5) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L66)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I made it clearer and added documentation.
</blockquote></details>

Ty.
Can you multiply to avoid division?


<!-- Sent from Reviewable.io -->

2024-04-30 08:31 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/stwo/572#-NvzGKj57V615MqaR9le:-NwKKWTKDIhVZQjsJ7Gx:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ddb9e2e68d430100bdfabde87f183b8b41f007a/crates/prover/src/examples/wide_fibonacci/mod.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Ty.
Can you multiply to avoid division?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEE9VEAPMU8B9Jygeu:-NwKKLax79e9dciPvR76:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/mod.rs#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Multiply both sides by the denominator, to avoid division in the check.
Below as well.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwECLkIBUX_I1ho67-A:-NwKR4Vh005R8fWvoWNM:b4t3ki) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What's stopping you from doing it now?
</blockquote></details>

It adds complexities that I'd rather take care of separately. The traces until now are of the base field, so computing the CP will have to change for example.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEDifc9Nx6-7szT9Tc:-NwKKhFnDWq7FpBWYx5Z:b-7yd1q4) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L42)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Agree, but this can done in another pr.
</blockquote></details>

Added a TODO.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEDtDpATIyPR4BDvyq:-Nwi2E6SEjHRejv0dUyk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Perhaps this should be a common utility function (not just for fib).
Gets alpha, z, vals: &[BaseField], and combines.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwJQwPV8hhHubUebqPZ:-Nwi2EGu19CiwxGCMdNT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 08:57 UTC, shaharsamocha7 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r8](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwiCSOH5jyO5-u19hNn:-NwiCSOH5jyO5-u19hNo:b4zzqsj) ([raw file](https://github.com/starkware-libs/stwo/blob/e5265a718f9aba965c4778cf9c0af4e587a0fa16/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
> ```XML
> }
> 
> /// Randomly combines the given values using the given random alpha and z.
> ```

Consider to add more info to this documentation
Maybe also add something like
(\sum_i (\alpha^{n-i} * a_i) - z



_Suggestion:_
```XML
/// Securely combines the given values using the given random alpha and z.
/// Alpha and z should be secure field elements for soundness
```


<!-- Sent from Reviewable.io -->

2024-04-30 09:47 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r8](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwiCSOH5jyO5-u19hNn:-NwiDgTG5uGKer7rvBzm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e5265a718f9aba965c4778cf9c0af4e587a0fa16/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to add more info to this documentation
Maybe also add something like
(\sum_i (\alpha^{n-i} * a_i) - z
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 12:09 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572#-:-NwiuHROEBXrEOu4yR50:bnfp4nl)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-05-01 14:06 UTC, spapinistarkware requested changes
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwECLkIBUX_I1ho67-A:-NwoTQqT4EATFelG2t1d:b-blluc5) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It adds complexities that I'd rather take care of separately. The traces until now are of the base field, so computing the CP will have to change for example.
</blockquote></details>

Just break it to 4 columns, don't do any interface change


<!-- Sent from Reviewable.io -->

2024-05-01 14:07 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEDtDpATIyPR4BDvyq:-NwoTiQoESTks7FlDTrV:b-x7uhct) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Move it to a common place.


<!-- Sent from Reviewable.io -->

2024-05-07 14:04 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwECLkIBUX_I1ho67-A:-NwoWtHg-yWnMpIvs7NA:b-f22b20) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Just break it to 4 columns, don't do any interface change
</blockquote></details>

Is it okay if I do it separately later on? I think it's a good way to split the work
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwEDtDpATIyPR4BDvyq:-NwoWmqv-cjVz17LP1He:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L49)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Move it to a common place.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 06:53 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/utils.rs` line 92 at r10](https://reviewable.io/reviews/starkware-libs/stwo/572#-NxR79pP1gdu4TwHOokQ:-NxR79pP1gdu4TwHOokR:b-gqozkl) ([raw file](https://github.com/starkware-libs/stwo/blob/6c6632650aef931a5bd8d656cc5cda34e0bcdb3f/crates/prover/src/core/utils.rs#L92)):*
> ```XML
> /// Securely combines the given values using the given random alpha and z.
> /// Alpha and z should be secure field elements for soundness.
> pub fn combine(values: &[BaseField], alpha: BaseField, z: BaseField) -> BaseField {
> ```

Give this a more indicative name



_Code quote:_
```XML
combine
```


<!-- Sent from Reviewable.io -->

2024-05-09 07:01 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwECLkIBUX_I1ho67-A:-NxR8vXk2atjsXY37zXg:bsbqi76) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is it okay if I do it separately later on? I think it's a good way to split the work
</blockquote></details>

Let's first think of how this will look liek with Secure, and then decide


<!-- Sent from Reviewable.io -->

2024-05-16 12:32 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 92 at r10](https://reviewable.io/reviews/starkware-libs/stwo/572#-NxR79pP1gdu4TwHOokQ:-Ny0N7cw5HX0hsVlipH3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6c6632650aef931a5bd8d656cc5cda34e0bcdb3f/crates/prover/src/core/utils.rs#L92)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Give this a more indicative name
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 27 at r6](https://reviewable.io/reviews/starkware-libs/stwo/572#-NwECLkIBUX_I1ho67-A:-Ny0N8aM6ynAzPgJG9OG:bk6t5au) ([raw file](https://github.com/starkware-libs/stwo/blob/6183758ba05a44ed6aecd70aa95eff9580670f0e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Let's first think of how this will look liek with Secure, and then decide
</blockquote></details>

I think it will only make the interaction trace a secure poly, and then change the log degree bounds, mask etc. to 4 values instead of 1. I don't think it will be a lot of work to do it after.


<!-- Sent from Reviewable.io -->

2024-05-16 12:56 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/utils.rs` line 92 at r10](https://reviewable.io/reviews/starkware-libs/stwo/572#-NxR79pP1gdu4TwHOokQ:-Ny0T3370t3atiNH2Bmc:b-9luw9w) ([raw file](https://github.com/starkware-libs/stwo/blob/6c6632650aef931a5bd8d656cc5cda34e0bcdb3f/crates/prover/src/core/utils.rs#L92)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not indicative enough.
This doesn't just do a random linear combination. It's a random shift as well.
Maybe make this function only do the random linear combination, and do the shift (z-) outside?


<!-- Sent from Reviewable.io -->

2024-05-16 13:12 UTC, spapinistarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/572#-:-Ny0X0dG522-WK8WwjvW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2024-05-16 14:02 UTC, alonh5 commented
### Merge activity

* **May 16, 10:02 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/572).

2024-05-16 14:03 UTC, merged