Add batch GKR prover and verifier
starkware-libs/stwo pull request #581
Opened 2024-04-17 00:18 UTC by andrewmilson

2024-04-17 13:45 UTC, spapinistarkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/lookups/gkr.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/stwo/581#-NvgEs2GBzQITkbvbgbP:-NvgEs2GBzQITkbvbgbQ:bt2g4he) ([raw file](https://github.com/starkware-libs/stwo/blob/0e3b3571ef787307863dc46c4a4f80e759c14be2/src/core/lookups/gkr.rs#L81)):*
> ```XML
>     ///
>     /// [`sumcheck::prove_batch()`]: crate::core::lookups::sumcheck::prove_batch
>     fn into_sumcheck_oracle(
> ```

How about something like this?
"Represents this GKR layer evaluation as a multivariate polynomial which uses the previous GKR layer as input."



_Suggestion:_
```XML
into_multivariate_poly
```
___
*[`src/core/lookups/gkr.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/581#-NvgF7oM8w6u4D78vX8q:-NvgF7oM8w6u4D78vX8r:b2ni1ar) ([raw file](https://github.com/starkware-libs/stwo/blob/0e3b3571ef787307863dc46c4a4f80e759c14be2/src/core/lookups/gkr.rs#L83)):*
> ```XML
>     fn into_sumcheck_oracle(
>         self,
>         lambda: SecureField,
> ```

doc



_Code quote:_
```XML
lambda: SecureField,
```


<!-- Sent from Reviewable.io -->

2024-04-18 13:14 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/lookups/gkr.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/stwo/581#-NvgEs2GBzQITkbvbgbP:-Nvgh0G39ZevoLq_kE48:bmgar0w) ([raw file](https://github.com/starkware-libs/stwo/blob/0e3b3571ef787307863dc46c4a4f80e759c14be2/src/core/lookups/gkr.rs#L81)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

How about something like this?
"Represents this GKR layer evaluation as a multivariate polynomial which uses the previous GKR layer as input."
</blockquote></details>

Sounds good but I think "Represents the next GKR layer as a multivariate polynomial which uses this GKR layer as input." might be more accurate. WDYT?
___
*[`src/core/lookups/gkr.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/581#-NvgF7oM8w6u4D78vX8q:-NvlK7Zj2rk6kKH7u4no:b1pc8kv) ([raw file](https://github.com/starkware-libs/stwo/blob/0e3b3571ef787307863dc46c4a4f80e759c14be2/src/core/lookups/gkr.rs#L83)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Updated. WDYT?


<!-- Sent from Reviewable.io -->

2024-04-24 08:38 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/lookups/gkr.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwEFO7v48ORQqJE4BGi:-NwEFO7v48ORQqJE4BGj:bi49hii) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L232)):*
> ```XML
> /// the OOD point. These evaluations are not checked by this function - hence partial verification.
> pub fn partially_verify_batch(
>     circuit_unit_by_component: Vec<&dyn GkrBinaryCircuitUnit>,
> ```

Why does this assume a binary circuit, and the prove does not? (Gets a GkrLayer)
___
*[`src/core/lookups/gkr.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/stwo/581#-NvgEs2GBzQITkbvbgbP:-NwEEhxyChKEXL3Hdwqo:b2nic6t) ([raw file](https://github.com/starkware-libs/stwo/blob/0e3b3571ef787307863dc46c4a4f80e759c14be2/src/core/lookups/gkr.rs#L81)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Sounds good but I think "Represents the next GKR layer as a multivariate polynomial which uses this GKR layer as input." might be more accurate. WDYT?
</blockquote></details>

sg.


<!-- Sent from Reviewable.io -->

2024-04-30 14:02 UTC, shaharsamocha7 reviewed
> Reviewed 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/utils.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjEtAu2R-Z8ZPY-dOV:-NwjEtAu2R-Z8ZPY-dOW:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/utils.rs#L178)):*
> ```XML
>     assert_eq!(x.len(), y.len());
>     zip(x, y)
>         .map(|(&xi, &wi)| xi * wi + (F::one() - xi) * (F::one() - wi))
> ```





_Suggestion:_
```XML
    zip(x, y)
        .map(|(&xi, &yi)| xi * yi + (F::one() - yi) * (F::one() - yi))
```
___
*[`crates/prover/src/core/lookups/gkr.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjFuYP8Nwlvd-NqKCM:-NwjFuYP8Nwlvd-NqKCN:b-fyludl) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L21)):*
> ```XML
> pub trait GkrOps: MleOps<SecureField> {
>     /// Returns the evaluations of [`eq(x, y)`] for all values of `x = (x_0, ..., x_{n-1})` where
>     /// `x_0 = 0` and `x_1, ..., x_{n-1}` in `{0, 1}`.
> ```

Consider writing the comment as follow, not sure if it's better



_Suggestion:_
```XML
    /// Returns the evaluations of [`eq(x, y)`] for all the boolean hypercube points of the form `x = (0, x_1, ..., x_{n-1})`.
```
___
*[`crates/prover/src/core/lookups/gkr.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjI8iB98tCfwJvoXjw:-NwjI8iB98tCfwJvoXjx:bjlyw8) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L43)):*
> ```XML
>         let y = y.to_vec();
>         let evals = B::gen_eq_evals(&y);
>         assert_eq!(evals.len(), 1 << y.len().saturating_sub(1));
> ```

Why do you need this assert?



_Code quote:_
```XML
        assert_eq!(evals.len(), 1 << y.len().saturating_sub(1));
```


<!-- Sent from Reviewable.io -->

2024-04-30 14:03 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/gkr.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjJLJJ8YyE5LEzjno6:-NwjJLJJ8YyE5LEzjno7:b-witi0q) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L76)):*
> ```XML
>     ///
>     /// Layers can contain multiple columns `c_0, ..., c_{n-1}` with multivariate polynomial `g_i`
>     /// representing `c_i` in the next layer. These polynomials must must be combined with `lambda`
> ```

Duplicate



_Suggestion:_
```XML
These polynomial must be combined with `lambda`
```


<!-- Sent from Reviewable.io -->

2024-05-01 19:22 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/utils.rs` line 178 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjEtAu2R-Z8ZPY-dOV:-Nwp56OC4uxGUq4VFWPp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/utils.rs#L178)):*
> ```XML
>     assert_eq!(x.len(), y.len());
>     zip(x, y)
>         .map(|(&xi, &wi)| xi * wi + (F::one() - xi) * (F::one() - wi))
> ```

Done.
___
*[`crates/prover/src/core/lookups/gkr.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjI8iB98tCfwJvoXjw:-Nwp0wKz4eDwNLgY5dbH:bq8jhuf) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L43)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you need this assert?
</blockquote></details>

Just a sanity check to make sure the backend returns the expected amount of evaluations
___
*[`crates/prover/src/core/lookups/gkr.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwjJLJJ8YyE5LEzjno6:-NwpAesvASIKJnBnyXXZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L76)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Duplicate
</blockquote></details>

Done.
___
*[`crates/prover/src/core/lookups/gkr.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/stwo/581#-NwEFO7v48ORQqJE4BGi:-NwpAUQiDIJp5Lm7ZIm0:b-9bny5r) ([raw file](https://github.com/starkware-libs/stwo/blob/65846a2e0d49e379c9e0606ab7f13e7c43629b41/crates/prover/src/core/lookups/gkr.rs#L232)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why does this assume a binary circuit, and the prove does not? (Gets a GkrLayer)
</blockquote></details>

Changed `GkrLayer` to `GkrBinaryLayer`


<!-- Sent from Reviewable.io -->

2024-05-05 22:22 UTC, andrewmilson commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-08 15:53 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`src/core/lookups/gkr.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/stwo/581#-NvgEs2GBzQITkbvbgbP:-NxNu2qP9Qy5M6y6YDz6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0e3b3571ef787307863dc46c4a4f80e759c14be2/src/core/lookups/gkr.rs#L81)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

sg.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 07:41 UTC, spapinistarkware requested changes
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`clippy.toml` line 1 at r7](https://reviewable.io/reviews/starkware-libs/stwo/581#-NxRFr3A3afSTyXpSdCA:-NxRFr3B9gt0kkuOjysf:b9aq64g) ([raw file](https://github.com/starkware-libs/stwo/blob/30ca27c65fd9122ae6ecf77e5b6af261cf470703/clippy.toml#L1)):*
> ```TOML
> # upper-case-acronyms-aggressive = true
> ```

What's this? Did you mean to commity it?
___
*[`crates/prover/src/core/lookups/gkr.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/stwo/581#-NxRHzfk56_017sjjfm2:-NxRHzfk56_017sjjfm3:brskivr) ([raw file](https://github.com/starkware-libs/stwo/blob/30ca27c65fd9122ae6ecf77e5b6af261cf470703/crates/prover/src/core/lookups/gkr.rs#L69)):*
> ```XML
>     type Backend: GkrOps + MleOps<SecureField>;
> 
>     type MultivariatePolyOracle<'a>: GkrMultivariatePolyOracle<Backend = Self::Backend>;
> ```

I don't understand what this type does. the trait doesn't look like a multiovariate poly, or I dont understand what this trait does.



_Code quote:_
```XML
MultivariatePolyOracle<'a>: GkrMultivariatePolyOracle<Backend = Self::Backend>
```


<!-- Sent from Reviewable.io -->

2024-05-11 01:33 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`clippy.toml` line 1 at r7](https://reviewable.io/reviews/starkware-libs/stwo/581#-NxRFr3A3afSTyXpSdCA:-Nx_4rbA65PZDkWLaJeb:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/30ca27c65fd9122ae6ecf77e5b6af261cf470703/clippy.toml#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What's this? Did you mean to commity it?
</blockquote></details>

Removed.
___
*[`crates/prover/src/core/lookups/gkr.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/stwo/581#-NxRHzfk56_017sjjfm2:-NxZPJ6222G_LPzDdc2E:b-uim771) ([raw file](https://github.com/starkware-libs/stwo/blob/30ca27c65fd9122ae6ecf77e5b6af261cf470703/crates/prover/src/core/lookups/gkr.rs#L69)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand what this type does. the trait doesn't look like a multiovariate poly, or I dont understand what this trait does.
</blockquote></details>

The type is of the multivariate polynomial used with sumcheck.
It extends trait MultivariatePolyOracle to enable getting the mask values.


<!-- Sent from Reviewable.io -->

2024-05-16 03:21 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr.rs` line 69 at r7](https://reviewable.io/reviews/starkware-libs/stwo/581#-NxRHzfk56_017sjjfm2:-NxzPjPH6ENYnCt8Xaff:bkvcpa2) ([raw file](https://github.com/starkware-libs/stwo/blob/30ca27c65fd9122ae6ecf77e5b6af261cf470703/crates/prover/src/core/lookups/gkr.rs#L69)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

The type is of the multivariate polynomial used with sumcheck.
It extends trait MultivariatePolyOracle to enable getting the mask values.
</blockquote></details>

Updated the comments of try_into_mask so it makes more sense now.


<!-- Sent from Reviewable.io -->

2024-06-10 10:05 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 6 files at r4, 1 of 1 files at r6, 1 of 2 files at r8, 1 of 3 files at r10, 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr.rs` line 19 at r11](https://reviewable.io/reviews/starkware-libs/stwo/581#-O--wIknEZt3t-YdWPAh:-O--wIko0ES4RX_ZwA43:bup4u43) ([raw file](https://github.com/starkware-libs/stwo/blob/8cd2fd480e4e3796bf38d5d66ce340ee48b0cdc4/crates/prover/src/core/lookups/gkr.rs#L19)):*
> ```XML
> 
> pub trait GkrOps: MleOps<SecureField> {
>     /// Returns evaluations `eq(x, y) * v` for all `x` in `{0, 1}^n`.
> ```

Does it return in regular order?



_Code quote:_
```XML
/// Returns evaluations `eq(x, y) * v` for all `x` in `{0, 1}^n`.
```
___
*[`crates/prover/src/core/lookups/gkr.rs` line 169 at r11](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-0_T037O2J_DHnesgK:-O-0_T037O2J_DHnesgL:bbytnvu) ([raw file](https://github.com/starkware-libs/stwo/blob/8cd2fd480e4e3796bf38d5d66ce340ee48b0cdc4/crates/prover/src/core/lookups/gkr.rs#L169)):*
> ```XML
> pub trait GkrBinaryGate {
>     /// Returns the output row after applying the gate to the provided input rows.
>     fn eval(&self, row0: &[SecureField], row1: &[SecureField]) -> Vec<SecureField>;
> ```

Why does the inputs called row?



_Code quote:_
```XML
fn eval(&self, row0: &[SecureField], row1: &[SecureField]) -> Vec<SecureField>;
```


<!-- Sent from Reviewable.io -->

2024-06-10 10:48 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr.rs` line 519 at r11](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-0knQa6eQp26G9wg2e:-O-0knQbER4AZACmsL47:b-r6yjy6) ([raw file](https://github.com/starkware-libs/stwo/blob/8cd2fd480e4e3796bf38d5d66ce340ee48b0cdc4/crates/prover/src/core/lookups/gkr.rs#L519)):*
> ```XML
> /// * `k` is zero or greater than the length of `y`.
> /// * `z_0` is zero.
> pub fn correct_sum_as_poly_in_first_variable(
> ```

Remove from this pr as discussed.



_Code quote:_
```XML
pub fn correct_sum_as_poly_in_first_variable(
```


<!-- Sent from Reviewable.io -->

2024-06-13 06:53 UTC, shaharsamocha7 requested changes
> Reviewed 3 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 19 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FLzF_0OpRSjKXKdwb:-O-FLzFaALH21yC5YAYH:bup4u43) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L19)):*
> ```XML
> 
> pub trait GkrOps: MleOps<SecureField> {
>     /// Returns evaluations `eq(x, y) * v` for all `x` in `{0, 1}^n`.
> ```

Does it return in regular order?



_Code quote:_
```XML
    /// Returns evaluations `eq(x, y) * v` for all `x` in `{0, 1}^n`.
```
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 109 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FLjCm4EOqIeFfmR_K:-O-FLjCn-BT5MlcUhvuG:bb5a0gr) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L109)):*
> ```XML
>     fn is_output_layer(&self) -> bool {
>         self.n_variables() == 0
>     }
> ```

Does it assumes that we only have one output?



_Code quote:_
```XML
    fn is_output_layer(&self) -> bool {
        self.n_variables() == 0
    }
```
___
*[`crates/prover/src/core/lookups/utils.rs` line 173 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FMaG75ZoOkn4_leg7:-O-FMaG75ZoOkn4_leg8:b1mnjc2) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/utils.rs#L173)):*
> ```XML
> 
> /// Returns `v_0 + alpha * v_1 + ... + alpha^(n-1) * v_{n-1}`.
> pub fn random_linear_combination(v: &[SecureField], alpha: SecureField) -> SecureField {
> ```

Can you check if we already have this util func somewhere in the code?



_Code quote:_
```XML
random_linear_combination
```


<!-- Sent from Reviewable.io -->

2024-06-13 15:28 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 19 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FLzF_0OpRSjKXKdwb:-O-H2AMuEW7u9pAh-OHA:bi85wcc) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it return in regular order?
</blockquote></details>

Mle stores values in bit-reversed order
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 109 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FLjCm4EOqIeFfmR_K:-O-H2Iha2OWpW6zIn3F0:b-5entkn) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L109)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it assumes that we only have one output?
</blockquote></details>

Yes, assumes each column has a single value since it's just for lookups
___
*[`crates/prover/src/core/lookups/utils.rs` line 173 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FMaG75ZoOkn4_leg7:-O-HCbbg8JU9H8QJbIQM:b-4pmftq) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/utils.rs#L173)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you check if we already have this util func somewhere in the code?
</blockquote></details>

Couldn't find an existing function for it
___
*[`crates/prover/src/core/lookups/gkr.rs` line 169 at r11](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-0_T037O2J_DHnesgK:-O-H2_y4Cz6M8LjVVf9B:b-onmvme) ([raw file](https://github.com/starkware-libs/stwo/blob/8cd2fd480e4e3796bf38d5d66ce340ee48b0cdc4/crates/prover/src/core/lookups/gkr.rs#L169)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why does the inputs called row?
</blockquote></details>

Updated to take mask
___
*[`crates/prover/src/core/lookups/gkr.rs` line 519 at r11](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-0knQa6eQp26G9wg2e:-O-H2dPD409CFJHCvUyy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8cd2fd480e4e3796bf38d5d66ce340ee48b0cdc4/crates/prover/src/core/lookups/gkr.rs#L519)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove from this pr as discussed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-17 11:02 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 19 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FLzF_0OpRSjKXKdwb:-O-_qUdx0MmP999815AW:b-nypyuc) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L19)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Mle stores values in bit-reversed order
</blockquote></details>

consider to document here.
___
*[`crates/prover/src/core/lookups/utils.rs` line 173 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FMaG75ZoOkn4_leg7:-O-_r1Vv4Owxf98DSb79:bgk3igv) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/utils.rs#L173)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Couldn't find an existing function for it
</blockquote></details>

you have that one:
https://github.com/starkware-libs/stwo/blob/9259c07ab65d09803f3b496fad16eba536406f89/crates/prover/src/core/utils.rs#L92


<!-- Sent from Reviewable.io -->

2024-06-18 09:58 UTC, spapinistarkware requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 51 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-el4waA1w1RGUwbBA_:-O-el4waA1w1RGUwbBAa:b2v4t5w) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L51)):*
> ```XML
> 
> impl<B: GkrOps> EqEvals<B> {
>     pub fn new(y: &[SecureField]) -> Self {
> ```

When calling `new`, it is clear that there is a significant amount of work being done. Rename it to something that does convey that



_Code quote:_
```XML
new
```
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 85 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-elh2jAAuvWU7cbNa8:-O-elh2k2tLJeilpHfrs:b-amym8p) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L85)):*
> ```XML
> /// [LogUp]: https://eprint.iacr.org/2023/1284.pdf
> pub enum Layer<B: GkrOps> {
>     _LogUp(B),
> ```

Why Does it have a B value? Sounds a bit weird



_Code quote:_
```XML
B
```
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 156 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-elyVK3CNICKcRn4t5:-O-elyVK3CNICKcRn4t6:b-n2urrw) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L156)):*
> ```XML
> 
> /// A multivariate polynomial expressed in the multilinear poly columns of a [`Layer`].
> pub enum GkrMultivariatePolyOracle {
> ```

Is this different than the Layer enum? Can they ever diverge?


<!-- Sent from Reviewable.io -->

2024-06-18 10:02 UTC, spapinistarkware reviewed
> Reviewed 1 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-06-18 10:50 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 196 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-exIraDly1z4DPBrkZ:-O-exIraDly1z4DPBrk_:bws3t5c) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L196)):*
> ```XML
> pub struct NotConstantPolyError;
> 
> // GKR algorithm: <https://people.cs.georgetown.edu/jthaler/ProofsArgsAndZK.pdf> (page 64)
> ```

Add a doc about soundness assumptions.
For example, the input layer have been committed to the channel.
___
*[`crates/prover/src/core/lookups/gkr_verifier.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-exiYa4Kc3GqKUXnrt:-O-exiYa4Kc3GqKUXnru:bn65gtx) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_verifier.rs#L170)):*
> ```XML
> ///
> /// [Thaler13]: https://eprint.iacr.org/2013/351.pdf
> pub enum Gate {
> ```

It's the third time we have this enum. Do they need to be separated?
___
*[`crates/prover/src/core/lookups/gkr_verifier.rs` line 188 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-ey21053zqw37ouMzr:-O-ey21053zqw37ouMzs:bk6bbxj) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_verifier.rs#L188)):*
> ```XML
> impl From<InvalidNumMaskColumnsError> for GkrError {
>     fn from(_: InvalidNumMaskColumnsError) -> Self {
>         Self::MalformedProof
> ```

This is losing information, right? Perhaps we want to keep it?


<!-- Sent from Reviewable.io -->

2024-06-18 10:58 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/gkr_verifier.rs` line 188 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-ey21053zqw37ouMzr:-O-ezkdw4Rchv1LzmD7t:b-rere9d) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_verifier.rs#L188)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is losing information, right? Perhaps we want to keep it?
</blockquote></details>

I mean, perhaps encapsulate this type inside GkrError


<!-- Sent from Reviewable.io -->

2024-06-18 11:26 UTC, spapinistarkware reviewed
> Reviewed 3 of 6 files at r4, 1 of 2 files at r8, 5 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: all files reviewed, 8 unresolved discussions (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-06-19 03:19 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 51 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-el4waA1w1RGUwbBA_:-O-iNPzF7ioZB8uDN0Uy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L51)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

When calling `new`, it is clear that there is a significant amount of work being done. Rename it to something that does convey that
</blockquote></details>

Done.
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 85 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-elh2jAAuvWU7cbNa8:-O-iNRj99cNkqcuC40yI:baliuhz) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L85)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why Does it have a B value? Sounds a bit weird
</blockquote></details>

Just using it as a B value placeholder so the compiler doesn't complain.
Implementation is fixed in the next PR.
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 156 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-elyVK3CNICKcRn4t5:-O-i8NdCBM6m2gEq5c9X:b-bw8e24) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L156)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this different than the Layer enum? Can they ever diverge?
</blockquote></details>

Updated
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 196 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-exIraDly1z4DPBrkZ:-O-iNxbTBAdZVuPSjkHd:b-h6ljcm) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_prover.rs#L196)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a doc about soundness assumptions.
For example, the input layer have been committed to the channel.
</blockquote></details>

Added. WDYT?
___
*[`crates/prover/src/core/lookups/gkr_verifier.rs` line 170 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-exiYa4Kc3GqKUXnrt:-O-i9ByGAF1qYVezIkkf:b-7ojrz5) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_verifier.rs#L170)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's the third time we have this enum. Do they need to be separated?
</blockquote></details>

Only two now. Layer is for the prover, Gate is is for the verifier
___
*[`crates/prover/src/core/lookups/gkr_verifier.rs` line 188 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-ey21053zqw37ouMzr:-O-iI84B8U74VMJVGpT2:b-bw8e14) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/gkr_verifier.rs#L188)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I mean, perhaps encapsulate this type inside GkrError
</blockquote></details>

Updated.
___
*[`crates/prover/src/core/lookups/utils.rs` line 173 at r12](https://reviewable.io/reviews/starkware-libs/stwo/581#-O-FMaG75ZoOkn4_leg7:-O-aCCrX0tWcnNdVwqb-:b-wa3qyf) ([raw file](https://github.com/starkware-libs/stwo/blob/30790f2913e412a63fb4aa7260652661f69bc087/crates/prover/src/core/lookups/utils.rs#L173)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you have that one:
https://github.com/starkware-libs/stwo/blob/9259c07ab65d09803f3b496fad16eba536406f89/crates/prover/src/core/utils.rs#L92
</blockquote></details>

It's a bit more than a random linear combination as it involves alpha and z. Also doesn't use SecureField


<!-- Sent from Reviewable.io -->

2024-06-20 13:29 UTC, spapinistarkware reviewed
> Reviewed 2 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-06-20 13:29 UTC, spapinistarkware approved these changes
> Reviewed 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-06-20 13:40 UTC, merged