Add SIMD backend arithmetic
starkware-libs/stwo pull request #592
Opened 2024-05-01 04:31 UTC by andrewmilson

2024-05-01 04:32 UTC, andrewmilson commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-01 13:49 UTC, spapinistarkware reviewed
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwnuIONCXagh8xvGHB_:-NwnuIONCXagh8xvGHBa:bkatinc) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L54)):*
> ```XML
>     /// Deinterleaves two vectors.
>     pub fn deinterleave(self, other: Self) -> (Self, Self) {
>         let (a, b) = self.0.deinterleave(other.0);
> ```

I thought I came up with this name!!


<!-- Sent from Reviewable.io -->

2024-05-01 14:03 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSGme5NlkQ2t_qaua:-NwoSGme5NlkQ2t_qaub:b-kxwdc2) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L226)):*
> ```XML
> 
>     // Each c_i contains |0|prod_lo|prod_hi|0|0|prod_lo|prod_hi|0|
>     let c0: u32x4 = unsafe { transmute(vqdmull_s32(a0, b0)) };
> ```

Can you put this in compiler explorer and check you get only the instruction you intended, and not some extra moves / swizzles?
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSTNgEAUl6KiO4JRk:-NwoSTNgEAUl6KiO4JRl:b-a9nco) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L236)):*
> ```XML
> 
>     // *_lo contain `|prod_lo|0|prod_lo|0|prod_lo0|0|prod_lo|0|`.
>     let mut c0_c1_lo: u32x4 = LoEvensConcatHiEvens::concat_swizzle(c0, c1);
> ```

Don't you have deinterleave for this?
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSboNAnsxP2dQPd5z:-NwoSboNAnsxP2dQPd6-:b-3epqjb) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L268)):*
> ```XML
>     let [a0, a1, a2, a3]: [v128; 4] = unsafe { transmute(a) };
> 
>     let b_double = b.0 << 1;
> ```

Is this the same as b.0+b.0? Couldn't that be more efficient?
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSqP94_DIjndh8cLz:-NwoSqP94_DIjndh8cM-:bjy6t1h) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L445)):*
> ```XML
>     PackedBaseField(prod_lows) + PackedBaseField(prod_highs)
> }
> ```

How can we test all of these architecture specific implementations?


<!-- Sent from Reviewable.io -->

2024-05-01 15:50 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwnuIONCXagh8xvGHB_:-NwodN_ICnFOy9Hd0oYO:b-cu736f) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L54)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I thought I came up with this name!!
</blockquote></details>

Lol. Funnily enough my VSCode spell checker doesn't think it's a word 😆
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSGme5NlkQ2t_qaua:-NwooaQs5ZeEnKXyWrZg:btglk4h) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L226)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you put this in compiler explorer and check you get only the instruction you intended, and not some extra moves / swizzles?
</blockquote></details>

All looks good: https://godbolt.org/z/nzjM4TY7M
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 236 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSTNgEAUl6KiO4JRk:-NwogUMW-NcrN5Y6G9RY:b-phrlao) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L236)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't you have deinterleave for this?
</blockquote></details>

True, thanks
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSboNAnsxP2dQPd5z:-Nwop4uo3TV1ii3FxEnJ:b-1nulqz) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L268)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this the same as b.0+b.0? Couldn't that be more efficient?
</blockquote></details>

Yes, updated
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSqP94_DIjndh8cLz:-Nwocv8j7eD84tQmktxX:biuq4yh) ([raw file](https://github.com/starkware-libs/stwo/blob/d2ca30c2ce0a93c4fb40470fce7db5cc53f43bc8/crates/prover/src/core/backend/simd/m31.rs#L445)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

How can we test all of these architecture specific implementations?
</blockquote></details>

I meant to add a TODO (added now) to test these platforms in the CI.

- Will make sure target feature neon is enabled on our mac tests.
- On avx512 machine plan to run tests once each for target features: `-avx2,-avx512,-simd128`, `+avx2,-avx512,-simd128`, `-avx2,+avx512,-simd128`, `-avx2,-avx512,+simd128` (wasm target wasm32-wasi)


<!-- Sent from Reviewable.io -->

2024-05-02 06:03 UTC, shaharsamocha7 requested changes
> Reviewed 5 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoP2V9EmVRUsFiRhJd:-NwoP2V9EmVRUsFiRhJe:b69071v) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L16)):*
> ```XML
> pub const LOG_N_LANES: u32 = 4;
> 
> pub const N_LANES: usize = 1 << LOG_N_LANES;
> ```

In the avx we stored only
`pub const K_BLOCK_SIZE: usize = 16;`



_Code quote:_
```XML
pub const LOG_N_LANES: u32 = 4;

pub const N_LANES: usize = 1 << LOG_N_LANES;
```
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSj5G1RvyDCZpfrz6:-NwoSj5G1RvyDCZpfrz7:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L76)):*
> ```XML
>     ///
>     /// Vector elements must be in the range `[0, P]`.
>     pub unsafe fn from_simd(v: Simd<u32, N_LANES>) -> Self {
> ```





_Suggestion:_
```XML
    pub unsafe fn from_simd_unchecked(v: Simd<u32, N_LANES>) -> Self {
```
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoTCja070E3UK3zgSG:-NwoTCja070E3UK3zgSH:b-4uyqc5) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L107)):*
> ```XML
>         // When c in [P,2P], then c-P in [0,P] which is always less than [P,2P].
>         // When c in [0,P-1], then c-P in [2^32-P,2^32-1] which is always greater than [0,P-1].
>         Self(Simd::simd_min(c, c - MODULUS))
> ```

Suggestion:
Can you call reduce instead?
and move the documentation there?



_Code quote:_
```XML
        // Apply min(c, c-P) to each word.
        // When c in [P,2P], then c-P in [0,P] which is always less than [P,2P].
        // When c in [0,P-1], then c-P in [2^32-P,2^32-1] which is always greater than [0,P-1].
        Self(Simd::simd_min(c, c - MODULUS))
```
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoTzunEEbGq2ulk_YG:-NwoTzunEEbGq2ulk_YH:b-54gdew) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L118)):*
> ```XML
> }
> 
> impl Mul for PackedBaseField {
> ```

Consider moving these _mul* implementations to a separated file



_Code quote:_
```XML
impl Mul for PackedBaseField {
```


<!-- Sent from Reviewable.io -->

2024-05-02 06:30 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSGme5NlkQ2t_qaua:-Nwrzao65Rx0tLVjfeEk:bmrgew) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L226)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

All looks good: https://godbolt.org/z/nzjM4TY7M
</blockquote></details>

Doesn't look good to me
[uAaA0MyaQJSyleLYTbSw1T4lKzcV4HZ3iwWQsSavZI9hJBAA%3D](https://godbolt.org/z/5nzEEsM1f)


<!-- Sent from Reviewable.io -->

2024-05-02 07:25 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSGme5NlkQ2t_qaua:-NwsBH2_-IQ5eWi8gbg0:bkm23sd) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L226)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Doesn't look good to me
[uAaA0MyaQJSyleLYTbSw1T4lKzcV4HZ3iwWQsSavZI9hJBAA%3D](https://godbolt.org/z/5nzEEsM1f)
</blockquote></details>

i.e. the issue is that you transmute, and move between representations that are not a full vector (u32x2).
Try to keep all the algorithm using full vectors.


<!-- Sent from Reviewable.io -->

2024-05-02 14:14 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSGme5NlkQ2t_qaua:-Nwtdk1s9bPiwck_OMta:bjc6z4n) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L226)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

i.e. the issue is that you transmute, and move between representations that are not a full vector (u32x2).
Try to keep all the algorithm using full vectors.
</blockquote></details>

I don't think your example is fair since [u32; 16] has different alignment. What is the issue here <https://godbolt.org/z/o9qE6bW86>?


<!-- Sent from Reviewable.io -->

2024-05-02 19:21 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoP2V9EmVRUsFiRhJd:-Nwtspta3aDsoqGpsMlr:bw3yx7a) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L16)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

In the avx we stored only
`pub const K_BLOCK_SIZE: usize = 16;`
</blockquote></details>

avx also has `VECS_LOG_SIZE = 4`
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoTCja070E3UK3zgSG:-NwujFoZ6F_1wKEFREaT:bbtioam) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L107)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Suggestion:
Can you call reduce instead?
and move the documentation there?
</blockquote></details>

The functionality is the same but the documentation is different. These docs are for reducing c in [0, 2P] to [0, P] but reduce docs are for [0, P] to [0, P)
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoTzunEEbGq2ulk_YG:-NwtqvYrDwrONL74smqD:b-1hzxw3) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L118)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider moving these _mul* implementations to a separated file
</blockquote></details>

What's the perceived benefit? To me these are all functions relating to m31 arithmetic so think they belong in this file. Also I'm generally in favour of larger files - the standard library has many examples of 3,000+ line files.
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 445 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSqP94_DIjndh8cLz:-NwtsXTw8rQRnJArQzvr:b-owqine) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L445)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I meant to add a TODO (added now) to test these platforms in the CI.

- Will make sure target feature neon is enabled on our mac tests.
- On avx512 machine plan to run tests once each for target features: `-avx2,-avx512,-simd128`, `+avx2,-avx512,-simd128`, `-avx2,+avx512,-simd128`, `-avx2,-avx512,+simd128` (wasm target wasm32-wasi)
</blockquote></details>

Can restrict the tests to `core::backend::simd`


<!-- Sent from Reviewable.io -->

2024-05-03 00:46 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSj5G1RvyDCZpfrz6:-NwvuZj02XgykcN32kA6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L76)):*
> ```XML
>     ///
>     /// Vector elements must be in the range `[0, P]`.
>     pub unsafe fn from_simd(v: Simd<u32, N_LANES>) -> Self {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 06:26 UTC, spapinistarkware reviewed
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/stwo/592#-NwoSGme5NlkQ2t_qaua:-NxBZkjE3p_JDKbsf4BT:b9d2dr6) ([raw file](https://github.com/starkware-libs/stwo/blob/c3c6fd293eaf7118f61d3e5f42d6dd10d9852a67/crates/prover/src/core/backend/simd/m31.rs#L226)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I don't think your example is fair since [u32; 16] has different alignment. What is the issue here <https://godbolt.org/z/o9qE6bW86>?
</blockquote></details>

Right, this seems fine. I was looking for the generated sqdmull.2d and sqdmull2.2d, wasn't sure if it was needed to be called explicitly.


<!-- Sent from Reviewable.io -->

2024-05-06 06:27 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/qm31.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxB_SGiAIeIe_K9V3bK:-NxB_SGiAIeIe_K9V3bL:b3kqx) ([raw file](https://github.com/starkware-libs/stwo/blob/b8a51617e6806b66a9d03c0b3adb4c7ed31ed017/crates/prover/src/core/backend/simd/qm31.rs#L16)):*
> ```XML
> /// SIMD implementation of [`QM31`].
> #[derive(Copy, Clone, Debug)]
> pub struct PackedSecureField(pub [PackedCM31; 2]);
> ```

.



_Suggestion:_
```XML
PackedQM31
```


<!-- Sent from Reviewable.io -->

2024-05-06 06:28 UTC, spapinistarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxB_dbjD2cQ_5WNczfy:-NxB_dbjD2cQ_5WNczfz:b-wbolmc) ([raw file](https://github.com/starkware-libs/stwo/blob/b8a51617e6806b66a9d03c0b3adb4c7ed31ed017/crates/prover/src/core/backend/simd/utils.rs#L4)):*
> ```XML
> 
> /// Used with [`Swizzle::concat_swizzle`] to interleave the low halves of vectors `lo` and `hi`.
> pub struct LoLoInterleaveHiLo;
> ```

Where is this used? Isn't it replaced by interleave and deinterleav()?


<!-- Sent from Reviewable.io -->

2024-05-06 14:52 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxB_dbjD2cQ_5WNczfy:-NxDKkv34pALlrq6ON75:b17yvmi) ([raw file](https://github.com/starkware-libs/stwo/blob/b8a51617e6806b66a9d03c0b3adb4c7ed31ed017/crates/prover/src/core/backend/simd/utils.rs#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Where is this used? Isn't it replaced by interleave and deinterleav()?
</blockquote></details>

It's used by `bit_reverse16`. `LoEvensConcatHiEvens` (now removed) was replaced by interleave and deinterleave


<!-- Sent from Reviewable.io -->

2024-05-06 20:07 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/qm31.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxB_SGiAIeIe_K9V3bK:-NxEW-f35aSpFPebMStt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b8a51617e6806b66a9d03c0b3adb4c7ed31ed017/crates/prover/src/core/backend/simd/qm31.rs#L16)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 11:00 UTC, shaharsamocha7 requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/cm31.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxHfba2DlpLY5h3Mj26:-NxHfba2DlpLY5h3Mj27:bj2k3c1) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/cm31.rs#L65)):*
> ```XML
>         let Self([a, b]) = self;
>         Self([a.double(), b.double()])
>     }
> ```

Do we need those?
We don't have them in the AVX512 impl



_Code quote:_
```XML
    /// Interleaves two vectors.
    pub fn interleave(self, other: Self) -> (Self, Self) {
        let Self([a_evens, b_evens]) = self;
        let Self([a_odds, b_odds]) = other;
        let (a_lhs, a_rhs) = a_evens.interleave(a_odds);
        let (b_lhs, b_rhs) = b_evens.interleave(b_odds);
        (Self([a_lhs, b_lhs]), Self([a_rhs, b_rhs]))
    }

    /// Deinterleaves two vectors.
    pub fn deinterleave(self, other: Self) -> (Self, Self) {
        let Self([a_self, b_self]) = self;
        let Self([a_other, b_other]) = other;
        let (a_evens, a_odds) = a_self.deinterleave(a_other);
        let (b_evens, b_odds) = b_self.deinterleave(b_other);
        (Self([a_evens, b_evens]), Self([a_odds, b_odds]))
    }

    /// Doubles each element in the vector.
    pub fn double(self) -> Self {
        let Self([a, b]) = self;
        Self([a.double(), b.double()])
    }
```
___
*[`crates/prover/src/core/backend/simd/qm31.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxHhG35-D0ywyepfv7E:-NxHhG35-D0ywyepfv7F:bg865ce) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/qm31.rs#L219)):*
> ```XML
>         iter.copied().sum()
>     }
> }
> ```

Why do we need both?



_Code quote:_
```XML
impl Sum for PackedQM31 {
    fn sum<I>(mut iter: I) -> Self
    where
        I: Iterator<Item = Self>,
    {
        let first = iter.next().unwrap_or_else(Self::zero);
        iter.fold(first, |a, b| a + b)
    }
}

impl<'a> Sum<&'a Self> for PackedQM31 {
    fn sum<I>(iter: I) -> Self
    where
        I: Iterator<Item = &'a Self>,
    {
        iter.copied().sum()
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-07 12:46 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/cm31.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxHfba2DlpLY5h3Mj26:-NxI3lYRDqGxMz-jTkGo:b-pz4wx3) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/cm31.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need those?
We don't have them in the AVX512 impl
</blockquote></details>

Interleave and deinterleave replace interleave_with and deinterleave_with. I added double since there is a an opportunity to have a more optimal implementation
___
*[`crates/prover/src/core/backend/simd/qm31.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxHhG35-D0ywyepfv7E:-NxI48Av1yy97FNBkk65:b-u4c0rx) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/qm31.rs#L219)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we need both?
</blockquote></details>

Just quality of life. It's nice to have the ability to just do thing.iter().sum(). Also it's consistent with the std library e.g. implements sum on usize and &usise


<!-- Sent from Reviewable.io -->

2024-05-07 13:17 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/cm31.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxHfba2DlpLY5h3Mj26:-NxIBeYiB6nCGvfl8ja1:b-cjinkb) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/cm31.rs#L65)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Interleave and deinterleave replace interleave_with and deinterleave_with. I added double since there is a an opportunity to have a more optimal implementation
</blockquote></details>

but in avx512 we only have those for base field. Do we also need it for CM31/QM31?


<!-- Sent from Reviewable.io -->

2024-05-07 16:01 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/cm31.rs` line 65 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxHfba2DlpLY5h3Mj26:-NxIm1lKEw_ZG9ExsaVe:bm77pyv) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/cm31.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

but in avx512 we only have those for base field. Do we also need it for CM31/QM31?
</blockquote></details>

Yes, not in the code yet but I'm using CM31/QM31 interleave, deinterleave and double for GKR


<!-- Sent from Reviewable.io -->

2024-05-08 07:09 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592#-:-NxM1GEr8QYQswDGWsNV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-05-08 07:11 UTC, shaharsamocha7 approved these changes
I didn't check the specific mul implementations.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592#-:-NxM1gtxCfNrTJVlVMi_:bbqbv6w)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-05-08 07:44 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxM95KR36eXallWtHDG:-NxM95KR36eXallWtHDH:b7wi2un) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/utils.rs#L6)):*
> ```XML
> pub struct LoLoInterleaveHiLo;
> 
> impl<const N: usize> Swizzle<N> for LoLoInterleaveHiLo {
> ```

Consider to call those structs as follows:
InterleaveLow
InterleaveHigh
InterleaveEvens
InterleaveOdds



_Code quote:_
```XML
LoLoInterleaveHiLo
```


<!-- Sent from Reviewable.io -->

2024-05-08 14:41 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 4 at r3](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxB_dbjD2cQ_5WNczfy:-NxNdKcoCuNJgPu-SfHu:b-xp8l5s) ([raw file](https://github.com/starkware-libs/stwo/blob/b8a51617e6806b66a9d03c0b3adb4c7ed31ed017/crates/prover/src/core/backend/simd/utils.rs#L4)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

It's used by `bit_reverse16`. `LoEvensConcatHiEvens` (now removed) was replaced by interleave and deinterleave
</blockquote></details>

🤦‍♂️ my bad you're right. `LoEvensConcatHiEvens` was replaced by deinterleave. `LoEvensConcatHiEvens` `LoLoInterleaveHiLo` was replaced by interleave. Updated


<!-- Sent from Reviewable.io -->

2024-05-08 15:52 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxM95KR36eXallWtHDG:-NxNtta8-ZOaHRx6eLDd:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/92fb94e15165aba1a78da1ee1a8750a4c761aafc/crates/prover/src/core/backend/simd/utils.rs#L6)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to call those structs as follows:
InterleaveLow
InterleaveHigh
InterleaveEvens
InterleaveOdds
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-12 10:36 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 263 at r6](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxgM_ZL3kCcdc6L5jjk:-NxgM_ZL3kCcdc6L5jjl:b-1eprpw) ([raw file](https://github.com/starkware-libs/stwo/blob/7c485c7736845a4de7539e73389e6a0ec423eab4/crates/prover/src/core/backend/simd/m31.rs#L263)):*
> ```XML
> }
> 
> /// Returns `a * b`.
> ```

I wonder if this function should be defined that way.
Is b_double defined correctly? (Values of PackedM31 should be in [0,P], no?)



_Suggestion:_
```XML
/// Returns `a * b_double`.
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxgLhJ03D2Uh92ty77V:-NxgLhJ1-pzMNJKE_NXa:b-gjj9wk) ([raw file](https://github.com/starkware-libs/stwo/blob/7c485c7736845a4de7539e73389e6a0ec423eab4/crates/prover/src/core/backend/simd/utils.rs#L17)):*
> ```XML
> }
> 
> const fn parity_interleave<const N: usize>(odd: bool) -> [usize; N] {
> ```

Consider adding doc test to understand the indices it returns



_Code quote:_
```XML
const fn parity_interleave<const N: usize>(odd: bool) -> [usize; N] {
```


<!-- Sent from Reviewable.io -->

2024-05-12 13:44 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 263 at r6](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxgM_ZL3kCcdc6L5jjk:-Nxh241EEk4iTuoms6qL:b1rdel4) ([raw file](https://github.com/starkware-libs/stwo/blob/7c485c7736845a4de7539e73389e6a0ec423eab4/crates/prover/src/core/backend/simd/m31.rs#L263)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I wonder if this function should be defined that way.
Is b_double defined correctly? (Values of PackedM31 should be in [0,P], no?)
</blockquote></details>

My bad. Removed
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/stwo/592#-NxgLhJ03D2Uh92ty77V:-Nxh1fH049JQ2co4L-Qm:bqohioq) ([raw file](https://github.com/starkware-libs/stwo/blob/7c485c7736845a4de7539e73389e6a0ec423eab4/crates/prover/src/core/backend/simd/utils.rs#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider adding doc test to understand the indices it returns
</blockquote></details>

I'd like to but these types are private and doc tests require public types.


<!-- Sent from Reviewable.io -->

2024-05-15 08:01 UTC, spapinistarkware approved these changes
> Reviewed 1 of 9 files at r1, 2 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-05-15 13:09 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/592#-:-NxwMjCN6K29FUFzjuYf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-05-15 13:09 UTC, merged