Blake xor table
starkware-libs/stwo pull request #764
Opened 2024-07-28 12:18 UTC by spapinistarkware

2024-07-28 12:18 UTC, spapinistarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/764?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#764** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/764?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#761** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-31 09:18 UTC, shaharsamocha7 requested changes
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O36UnOd2z0mPAki4mUP:-O36UnOd2z0mPAki4mUQ:bge0rjb) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/constraint_framework/logup.rs#L126)):*
> ```XML
>         shifted_secure_combination(values, EF::from(self.alpha), EF::from(self.z))
>     }
>     pub fn dummy() -> Self {
> ```

Can it be declared with #[cfg(test)]
It is a bit scary that we can use trivial interaction



_Code quote:_
```XML
pub fn dummy() -> Self {
```
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O36kkjgAJNP786jH-af:-O36kkjgAJNP786jH-ag:bb7phvt) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L11)):*
> ```XML
> //! The constant columns correspond only to the smaller table of the lower `ELEM_BITS - EXPAND_BITS`
> //! xors: (a_l, b_l, a_l^b_l).
> //! The restr of the lookups are computed based on these constant columns.
> ```

typo



_Suggestion:_
```XML
The rest of the lookups are computed based on these constant columns.
```
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O36lkxi5G197Nge8II6:-O36lkxi5G197Nge8II7:b-e4iblv) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L43)):*
> ```XML
>     /// 2^EXPAND_BITS columns.
>     pub mults: Vec<BaseColumn>,
> }
> ```

Can you elaborate on what each mult actually counts here?



_Code quote:_
```XML
pub struct XorAccumulator<const ELEM_BITS: u32, const EXPAND_BITS: u32> {
    /// 2^EXPAND_BITS columns.
    pub mults: Vec<BaseColumn>,
}
```
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O373ylx-CxO-ailQsRn:-O373ylx-CxO-ailQsRo:b2nhexc) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L87)):*
> ```XML
>     fn evaluate<E: EvalAtRow>(&self, mut eval: E) -> E {
>         let [is_first] = eval.next_interaction_mask(2, [0]);
>         let blake_eval = XorTableEval::<'_, _, ELEM_BITS, EXPAND_BITS> {
> ```

Fix



_Suggestion:_
```XML
     let xor_eval = XorTableEval::<'_, _, ELEM_BITS, EXPAND_BITS> {
```


<!-- Sent from Reviewable.io -->

2024-07-31 09:56 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/xor_table.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37CU_Q4ADZbv7RN1nY:-O37CU_R2Ipt0zczm47W:b-hjzqd5) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L106)):*
> ```XML
> {
>     pub fn eval(mut self) -> E {
>         let [a] = self.eval.next_interaction_mask(2, [0]);
> ```

This refers to the constant column, right?
Can you give a,b,c more indicative names?
Also, how would it work if you have more constant columns that are not relevant for xor?



_Code quote:_
```XML
        let [a] = self.eval.next_interaction_mask(2, [0]);
```
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37CvIu4m73_W_X-WCO:-O37CvIu4m73_W_X-WCP:b-1pkn2q) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L141)):*
> ```XML
> }
> 
> pub fn generate_trace<const ELEM_BITS: u32, const EXPAND_BITS: u32>(
> ```

Can you move this and get_interaction_trace in another file?



_Code quote:_
```XML
pub fn generate_trace<const ELEM_BITS: u32, const EXPAND_BITS: u32>(
```


<!-- Sent from Reviewable.io -->

2024-07-31 09:58 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/xor_table.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37DKKY60UiJJy3TFS5:-O37DKKY60UiJJy3TFS6:b-n1bsc7) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L281)):*
> ```XML
> 
> #[test]
> fn test_xor_table() {
> ```

Rename to test_xor_trace

Do we want another test that actually prove?



_Code quote:_
```XML
#[test]
fn test_xor_table() {
```


<!-- Sent from Reviewable.io -->

2024-07-31 10:25 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/xor_table.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37CU_Q4ADZbv7RN1nY:-O37J0OG82eIN6za0ghE:bsv3doi) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L106)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This refers to the constant column, right?
Can you give a,b,c more indicative names?
Also, how would it work if you have more constant columns that are not relevant for xor?
</blockquote></details>

I this I got confused, but still why it get next_interaction_mask(**2**,...)


<!-- Sent from Reviewable.io -->

2024-08-01 07:02 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O36UnOd2z0mPAki4mUP:-O37dox_17DhIIJW3LGZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/constraint_framework/logup.rs#L126)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can it be declared with #[cfg(test)]
It is a bit scary that we can use trivial interaction
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O36lkxi5G197Nge8II6:-O37eD1W7_JlEh4tT1G2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L43)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you elaborate on what each mult actually counts here?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O373ylx-CxO-ailQsRn:-O37eG10DZNoySmmqcl-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L87)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37CU_Q4ADZbv7RN1nY:-O37fdzl2nVf-BllqZty:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L106)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I this I got confused, but still why it get next_interaction_mask(**2**,...)
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37CvIu4m73_W_X-WCO:-O3BjH8M1asCEyQcG_N3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L141)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you move this and get_interaction_trace in another file?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/stwo/764#-O37DKKY60UiJJy3TFS5:-O3BixUSBpOSzSwzsjaw:b-av1sog) ([raw file](https://github.com/starkware-libs/stwo/blob/9a159ef3bf23b39ac89cda61f5cb349d6fb74030/crates/prover/src/examples/blake/xor_table.rs#L281)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename to test_xor_trace

Do we want another test that actually prove?
</blockquote></details>

1. Don't think it just tests the generation. It also tests the constraints.
2. No need. That test wouldn't be testing anything regarding XOR, it would be testing the prover.


<!-- Sent from Reviewable.io -->

2024-08-01 13:09 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 3 files at r3, 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D06fgC6hdCmonM76Q:-O3D06fgC6hdCmonM76R:b46ogxg) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/constraints.rs#L17)):*
> ```XML
>     pub fn eval(mut self) -> E {
>         // al, bl are the constant columns for the inputs: All pairs of elements in [0,
>         // 2^LIMB_BITS).
> ```

Do we actually need both al, bl in the constant tree?
This is the same sequential column.



_Code quote:_
```XML
        // al, bl are the constant columns for the inputs: All pairs of elements in [0,
        // 2^LIMB_BITS).
```
___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D0T1i5vwpM927XrGO:-O3D0T1i5vwpM927XrGP:booqwe9) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/constraints.rs#L41)):*
> ```XML
>                 self.logup.push_lookup(
>                     &mut self.eval,
>                     (-multiplicity).into(),
> ```

should we explain why this comes with a minus sign?



_Code quote:_
```XML
(-multiplicity).into(),
```
___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D0a8XAx3MOldBOmb3:-O3D0a8XAx3MOldBOmb4:bh3o6fy) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/constraints.rs#L49)):*
> ```XML
>         self.logup.finalize(&mut self.eval);
> 
>         self.eval
> ```

remove empty line



_Suggestion:_
```XML
        self.logup.finalize(&mut self.eval);
        self.eval
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D0mKO6xVHKUEebZmb:-O3D0mKO6xVHKUEebZmc:bxw9vho) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L21)):*
> ```XML
> pub struct XorTableLookupData<const ELEM_BITS: u32, const EXPAND_BITS: u32> {
>     pub xor_accum: XorAccumulator<ELEM_BITS, EXPAND_BITS>,
> }
> ```

Consider to rename to MultiplicityAccumulator
We can use the exact same thing for RangeCheckUnit and all the other mult things, no?



_Code quote:_
```XML
pub struct XorTableLookupData<const ELEM_BITS: u32, const EXPAND_BITS: u32> {
    pub xor_accum: XorAccumulator<ELEM_BITS, EXPAND_BITS>,
}
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3Ct2kd4rwTN3h9HSki:-O3Ct2keAcU0ZPw741Mp:bcukgsa) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L47)):*
> ```XML
> /// Returns the interaction trace, the constant trace, and the claimed sum.
> #[allow(clippy::type_complexity)]
> pub fn gen_interaction_trace<const ELEM_BITS: u32, const EXPAND_BITS: u32>(
> ```

To match with generate_trace



_Suggestion:_
```XML
pub fn generate_interaction_trace<const ELEM_BITS: u32, const EXPAND_BITS: u32>(
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D172L79k6OFkZ__k6:-O3D172L79k6OFkZ__k7:b-5xcey7) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L52)):*
> ```XML
> ) -> (
>     ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
>     ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
> ```

Why interaction trace returns also the constant trace?



_Code quote:_
```XML
    ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
    ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D1J3x5-D9zqe0Bd_Y:-O3D1J3yEpNiQvLKAV2i:b-svhgjy) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L77)):*
> ```XML
>         let bh1 = i1 as u32 & ((1 << EXPAND_BITS) - 1);
> 
>         // Each column has 2^(2*LIMB_BITS) rows, in packs of LOG_LANES.
> ```

Packed in `N_LANES`



_Code quote:_
```XML
in packs of LOG_LANES.
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 107 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D1XSd9f_npuG9WeBv:-O3D1XSd9f_npuG9WeBw:bc0wra5) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L107)):*
> ```XML
>     }
> 
>     // If there is an odd number of columns, handle the last one.
> ```

Is that correct?



_Suggestion:_
```XML
    // If there is an odd number of lookup expressions, handle the last one.
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D1sG7-wdhEvWFikZo:-O3D1sG878nQwFxzuWr0:b-59sq46) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L149)):*
> ```XML
>         })
>         .collect();
>     let mut constant_trace = [a_col, b_col, c_col]
> ```

Can you  move to another function?



_Code quote:_
```XML
    // Generate the constant columns. In reality, these should be generated before the proof
    // even began.
    let a_col: BaseColumn = (0..(1 << (column_bits::<ELEM_BITS, EXPAND_BITS>())))
        .map(|i| BaseField::from_u32_unchecked((i >> limb_bits) as u32))
        .collect();
    let b_col: BaseColumn = (0..(1 << (column_bits::<ELEM_BITS, EXPAND_BITS>())))
        .map(|i| BaseField::from_u32_unchecked((i & ((1 << limb_bits) - 1)) as u32))
        .collect();
    let c_col: BaseColumn = (0..(1 << (column_bits::<ELEM_BITS, EXPAND_BITS>())))
        .map(|i| {
            BaseField::from_u32_unchecked(((i >> limb_bits) ^ (i & ((1 << limb_bits) - 1))) as u32)
        })
        .collect();
    let mut constant_trace = [a_col, b_col, c_col]
```
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3Bz6NOEk6sdJ4auOZQ:-O3Bz6NOEk6sdJ4auOZR:b-gc1p5y) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/mod.rs#L36)):*
> ```XML
> /// Accumulator that keeps track of the number of times each input has been used.
> pub struct XorAccumulator<const ELEM_BITS: u32, const EXPAND_BITS: u32> {
>     /// 2^(2*EXPAND_BITS) multiplicity columns. Index (al, bl) fo column (ah, bh) is the number of
> ```

of column



_Code quote:_
```XML
fo column
```
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D2Paf5lbkIvmzwPvJ:-O3D2Paf5lbkIvmzwPvK:bsv2jix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/mod.rs#L52)):*
> ```XML
> }
> impl<const ELEM_BITS: u32, const EXPAND_BITS: u32> XorAccumulator<ELEM_BITS, EXPAND_BITS> {
>     pub fn add_input(&mut self, a: u32x16, b: u32x16) {
> ```

The indexing of the mult column is not clear.
Consider give better names, or add a test that explains it



_Code quote:_
```XML
  [...]

2024-08-04 06:47 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: 6 of 9 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D06fgC6hdCmonM76Q:-O3R55P-4BxrO6oVU1da:b-otj4sw) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/constraints.rs#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we actually need both al, bl in the constant tree?
This is the same sequential column.
</blockquote></details>

They are spaced differentlly. One is
0000111122223333
The other is
0123012301230123
___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D0a8XAx3MOldBOmb3:-O3R5XUn7Zeomch_h0zj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/constraints.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D0mKO6xVHKUEebZmb:-O3R5_Rz2ISrsKjHLcLS:bpule72) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename to MultiplicityAccumulator
We can use the exact same thing for RangeCheckUnit and all the other mult things, no?
</blockquote></details>

Premature abstraction. When we add it, we can change the name.
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3Ct2kd4rwTN3h9HSki:-O3R5g5rESdCi-1yz6EA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L47)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

To match with generate_trace
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D1J3x5-D9zqe0Bd_Y:-O3R6niVCPwe9wXFShU6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Packed in `N_LANES`
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 149 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D1sG7-wdhEvWFikZo:-O3R6spX75pHfc2WH4_Z:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L149)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you  move to another function?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3Bz6NOEk6sdJ4auOZQ:-O3R6x0X9LmiRvq61GMb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/mod.rs#L36)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

of column
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D2Paf5lbkIvmzwPvJ:-O3R7SZTBUKrhcoXLpSZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/mod.rs#L52)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The indexing of the mult column is not clear.
Consider give better names, or add a test that explains it
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D2hZb17WsmBpFXV8T:-O3R7Xkk5PMv0ine6JXG:b-yqli3r) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/mod.rs#L89)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

IMO this should be in the constraint file,
and rename it to component.rs
</blockquote></details>

Noted. I'd rather keep this here, since in other components we might have a long list of actual constraints, and that file will get overloaded. It is possible to add a component.rs file just for the component, don't think it's necessary.


<!-- Sent from Reviewable.io -->

2024-08-04 08:28 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764#-:-O3RVK9hCIhY0M7jk4vj:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D06fgC6hdCmonM76Q:-O3RMyn_DCusYslwuvcJ:b-s5d5b4) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/constraints.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

They are spaced differentlly. One is
0000111122223333
The other is
0123012301230123
</blockquote></details>

I see.
We need a way to have a view on what each constant column is.
It is not clear from here that this is the structure of al, bl.
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D0mKO6xVHKUEebZmb:-O3RNZXG8yLmcVSaJRxq:b-9u2cnb) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/gen.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Premature abstraction. When we add it, we can change the name.
</blockquote></details>

ok, but I do think we should use the same code for rc_unit and maybe all the "multiplicity & constant" components
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3D2hZb17WsmBpFXV8T:-O3RUsjI8lKJSsA4eBG9:b14waae) ([raw file](https://github.com/starkware-libs/stwo/blob/73ba6c44fe4c3a3d94ffe8d475dc1f49e090ce6c/crates/prover/src/examples/blake/xor_table/mod.rs#L89)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Noted. I'd rather keep this here, since in other components we might have a long list of actual constraints, and that file will get overloaded. It is possible to add a component.rs file just for the component, don't think it's necessary.
</blockquote></details>

I see your point, but let's discuss that so all components have the same structure.
___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3RUgDj8H4sn4RljF1l:-O3RUgDkE5hTSMUshJdx:buni46u) ([raw file](https://github.com/starkware-libs/stwo/blob/89854bb26f7256798d4882d9d0c3ee0c423e0c85/crates/prover/src/examples/blake/xor_table/mod.rs#L10)):*
> ```XML
> //! 2^(ELEM_BITS - EXPAND_BITS).
> //! The constant columns correspond only to the smaller table of the lower `ELEM_BITS - EXPAND_BITS`
> //! xors: (a_l, b_l, a_l^b_l).
> ```

What are their sizes?
`2 ^ 2* (ELEM_BITS - EXPAND_BITS)`?



_Code quote:_
```XML
//! The constant columns correspond only to the smaller table of the lower `ELEM_BITS - EXPAND_BITS`
//! xors: (a_l, b_l, a_l^b_l).
```


<!-- Sent from Reviewable.io -->

2024-08-04 10:00 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/764)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/xor_table/mod.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/stwo/764#-O3RUgDj8H4sn4RljF1l:-O3RpE1pCBuAwzxj9Abi:b2jtivd) ([raw file](https://github.com/starkware-libs/stwo/blob/89854bb26f7256798d4882d9d0c3ee0c423e0c85/crates/prover/src/examples/blake/xor_table/mod.rs#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What are their sizes?
`2 ^ 2* (ELEM_BITS - EXPAND_BITS)`?
</blockquote></details>

Well, the entire component is of the same length, so yes. I wrote it about the mul columns a line above


<!-- Sent from Reviewable.io -->

2024-08-04 10:00 UTC, merged