Blake round
starkware-libs/stwo pull request #767
Opened 2024-07-29 14:12 UTC by spapinistarkware

2024-07-29 14:13 UTC, spapinistarkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/767?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#767** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/767?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#765** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/765?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#764** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/764?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#761** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-04 14:50 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SpyHB1tGKtDTn-A4W:-O3SpyHB1tGKtDTn-A4X:b-aokxw8) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/mod.rs#L1)):*
> ```XML
> #![allow(unused)]
> ```

Add module documentation
You had something that pointed to the paper.



_Code quote:_
```XML
#![allow(unused)]
```
___
*[`crates/prover/src/examples/blake/mod.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SnQU_4LlP4uGiY41M:-O3SnQU_4LlP4uGiY41N:b666vu9) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/mod.rs#L48)):*
> ```XML
>     fn draw(channel: &mut Blake2sChannel) -> Self {
>         Self {
>             xor12: LookupElements::draw(channel, 3),
> ```

make constant



_Code quote:_
```XML
3
```
___
*[`crates/prover/src/examples/blake/mod.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Snrv0Dj8aVcNRQb_C:-O3Snrv0Dj8aVcNRQb_D:b-4lw63n) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/mod.rs#L64)):*
> ```XML
>             4 => &self.xor4,
>             _ => panic!("Invalid w"),
>         }
> ```

Consider to store xor\d in array and have here a general implementation
Same for the accums



_Code quote:_
```XML
        match w {
            12 => &self.xor12,
            9 => &self.xor9,
            8 => &self.xor8,
            7 => &self.xor7,
            4 => &self.xor4,
            _ => panic!("Invalid w"),
        }
```
___
*[`crates/prover/src/examples/blake/mod.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SoW4R1dRlgV3Jizbu:-O3SoW4S08pYNzW2aKCO:bo36mie) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/mod.rs#L69)):*
> ```XML
> 
> #[derive(Clone, Copy, Debug)]
> struct Fu32<F>
> ```

Isn't that specific for M31?



_Code quote:_
```XML
struct Fu32<F>
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SpkWJ63xUOzDEtzKV:-O3SpkWJ63xUOzDEtzKW:bedayl) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L10)):*
> ```XML
> use crate::examples::blake::Fu32;
> 
> const I16: BaseField = BaseField::from_u32_unchecked(1 << 15);
> ```

Took me some time to understand Inv16.. (rename or document)



_Code quote:_
```XML
const I16: BaseField
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 33 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Sq4L9-5RXXqnI7HSG:-O3Sq4L9-5RXXqnI7HSH:bctsztj) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L33)):*
> ```XML
>         self.g(7, v.get_many_mut([3, 4, 9, 14]).unwrap(), m[14], m[15]);
> 
>         self.logup.push_lookup(
> ```

Comment:
// Yield



_Code quote:_
```XML
        self.logup.push_lookup(
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Spa6iCN4Fft9EEgAH:-O3Spa6iCN4Fft9EEgAI:bfezlp) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L53)):*
> ```XML
>         Fu32 { l, h }
>     }
>     fn g(&mut self, _round: u32, v: [&mut Fu32<E::F>; 4], m0: Fu32<E::F>, m1: Fu32<E::F>) {
> ```

Shouldn't you use it?



_Code quote:_
```XML
_round: u32
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqLJw0mmSOhun3sO4:-O3SqLJw0mmSOhun3sO5:boasi7o) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L95)):*
> ```XML
>             carry_l
>                 * (carry_l - E::F::from(BaseField::from_u32_unchecked(1 << 0)))
>                 * (carry_l - E::F::from(BaseField::from_u32_unchecked(1 << 1))),
> ```

Consider to extract to is_triplet function



_Code quote:_
```XML
            carry_l
                * (carry_l - E::F::from(BaseField::from_u32_unchecked(1 << 0)))
                * (carry_l - E::F::from(BaseField::from_u32_unchecked(1 << 1))),
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqbJ49UfzvjNxYpeu:-O3SqbJ49UfzvjNxYpev:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L116)):*
> ```XML
>     }
> 
>     /// Checks that a, b are in range, and computes their xor rotate.
> ```





_Suggestion:_
```XML
    /// Checks that a, b are in range, and computes their xor rotate right by `r` bits.
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqnsO04Blp2XsSCug:-O3SqnsO04Blp2XsSCuh:b-y89i3t) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L142)):*
> ```XML
>         let (bhl, bhh) = self.split_unchecked(b.h, 8);
> 
>         // These also guarantee that all elements are in range.
> ```

This comment should be in the xor doc.



_Code quote:_
```XML
// These also guarantee that all elements are in range.
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqwwkE8xM9Z7khQA0:-O3SqwwkE8xM9Z7khQA1:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/constraints.rs#L154)):*
> ```XML
>     }
> 
>     /// Checks that a,b in in [0,2^w) and computes their xor.
> ```





_Suggestion:_
```XML
/// Checks that a,b are in [0,2^w) and computes their xor.
```
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SrB083zzMOlfJ_yEJ:-O3SrB09AW73BJefOL2-:b-kzxhlg) ([raw file](https://github.com/starkware-libs/stwo/blob/34c742f18927e33308785ead4375a63a1d3d109b/crates/prover/src/examples/blake/round/gen.rs#L24)):*
> ```XML
> 
> pub struct BlakeLookupData {
>     xor_lookups: Vec<(u32, [BaseColumn; 3])>,
> ```

document everywhere



_Code quote:_
```XML
xor_lookups: Vec<(u32, [BaseColumn; 3])>,
```


<!-- Sent from Reviewable.io -->

2024-08-05 07:09 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SpyHB1tGKtDTn-A4W:-O3WB9RC6wTEKUERCCyc:b-qo3pad) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add module documentation
You had something that pointed to the paper.
</blockquote></details>

Which paper?
___
*[`crates/prover/src/examples/blake/mod.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SnQU_4LlP4uGiY41M:-O3WDhCj57TDoghMZlDr:bgrshp2) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

make constant
</blockquote></details>

Did better
___
*[`crates/prover/src/examples/blake/mod.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Snrv0Dj8aVcNRQb_C:-O3WDsUiAQ_HqgnCraa2:b-kxi8n) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to store xor\d in array and have here a general implementation
Same for the accums
</blockquote></details>

What would I have in the unused slots?
___
*[`crates/prover/src/examples/blake/mod.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SoW4R1dRlgV3Jizbu:-O3WE2V68Y5SeaWf6rl5:b-ldlfi1) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L69)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Isn't that specific for M31?
</blockquote></details>

Yes, but F could be packed.
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Spa6iCN4Fft9EEgAH:-O3WESPn4ZD4DlH4mzpN:b-8qjsbg) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/constraints.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Shouldn't you use it?
</blockquote></details>

Nope, but I removed it. It is only used to select the message, but I'm already passing the selecetd messages to the function.
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqLJw0mmSOhun3sO4:-O3WEZlh7fQjjrFZ1Ur6:bfjt3yc) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/constraints.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to extract to is_triplet function
</blockquote></details>

Noted. It is only used here, in these few lines in this relatively short fucntion. Way too early IMO to extract a function. It would also make the function harder to read (anyone would definitely dive into is_triplet). But I did extract a constant.
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqbJ49UfzvjNxYpeu:-O3WFLuOCkX7Rs-p_TYT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/constraints.rs#L116)):*
> ```XML
>     }
> 
>     /// Checks that a, b are in range, and computes their xor rotate.
> ```

Done.
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SqwwkE8xM9Z7khQA0:-O3WFcXA4cxk84J4Lr-h:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/constraints.rs#L154)):*
> ```XML
>     }
> 
>     /// Checks that a,b in in [0,2^w) and computes their xor.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-08-05 09:59 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SrB083zzMOlfJ_yEJ:-O3WybaO4eNAfXP-xaMo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/gen.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

document everywhere
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-05 12:04 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 9 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XPsKs3uEz0q-G_hb2:-O3XPsKs3uEz0q-G_hb3:bgjb770) ([raw file](https://github.com/starkware-libs/stwo/blob/2baab80529c2c9ac986e41f830a49991d7fd28bb/crates/prover/src/constraint_framework/logup.rs#L147)):*
> ```XML
>             - EF::from(self.z)
>     }
>     #[cfg(test)]
> ```

can you re-add here?



_Code quote:_
```XML
#[cfg(test)]
```
___
*[`crates/prover/src/examples/blake/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SpyHB1tGKtDTn-A4W:-O3XPPfd5yjXcmyZmZyC:b-rm5zkk) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Which paper?
</blockquote></details>

I'm not sure, but we had a page that explained the blake function flow. (wikipedia maybe?)
I think that a reference to this could be good.
___
*[`crates/prover/src/examples/blake/mod.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Snrv0Dj8aVcNRQb_C:-O3XOnFGBLYn8A5pdTmA:b-mmrt22) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L64)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What would I have in the unused slots?
</blockquote></details>

Panic if key is not in dict?
I meant dict not an array


<!-- Sent from Reviewable.io -->

2024-08-05 12:10 UTC, shaharsamocha7 commented
*[`crates/prover/src/examples/blake/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SpyHB1tGKtDTn-A4W:-O3XRhqn-WHb-7ONUZb1:bipwkl2) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm not sure, but we had a page that explained the blake function flow. (wikipedia maybe?)
I think that a reference to this could be good.
</blockquote></details>

maybe here
https://en.wikipedia.org/wiki/BLAKE_(hash_function)


<!-- Sent from Reviewable.io -->

2024-08-05 12:29 UTC, shaharsamocha7 requested changes
> Reviewed 3 of 9 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 6 of 9 files reviewed, 11 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SrB083zzMOlfJ_yEJ:-O3XUUorCMOy1Y-IUSio:bysovmt) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/gen.rs#L24)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't understand what the xor_lookups means
Specifically it is hard for me to understand what xor() func does.
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XQssEDiekFc-Yzzet:-O3XQssF3SorzbHJhOWZ:b-7pn3ar) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L67)):*
> ```XML
> }
> impl<'a> TraceGeneratorRow<'a> {
>     fn append_felt(&mut self, val: u32x16) {
> ```

Do we want to assert/debug_assert here that those are in renge [0,P)?



_Code quote:_
```XML
fn append_felt(&mut self, val: u32x16) {
```
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XS-nO9JgxaCZa0Qf6:-O3XS-nO9JgxaCZa0Qf7:b-tdtw85) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L132)):*
> ```XML
>     }
> 
>     /// Splits a felt at r.
> ```

Consider to write why you only append the high part.



_Code quote:_
```XML
    /// Splits a felt at r.
```
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 150 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XSVTqAU7H-ZorV8U9:-O3XSVTrC1m3mEwPpT5J:b-5qymex) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L150)):*
> ```XML
>         let (bhl, bhh) = self.split(b >> 16, r);
> 
>         let _xorll = self.xor(r, all, bll);
> ```

Remove the return value or 

add an assert that it is correct.
assert_eq(cr, build(xor_ll, xor_lh, ..)



_Code quote:_
```XML
let _xorll = self.xor(r, all, bll);
```
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 171 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XSkB0C64fVEnL4Qkh:-O3XSkB16CA8obYzzbHK:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L171)):*
> ```XML
>         let _xorlh = self.xor(8, alh, blh);
>         let _xorhl = self.xor(8, ahl, bhl);
>         let _xorhh = self.xor(8, ahh, bhh);
> ```

same



_Code quote:_
```XML
        let _xorll = self.xor(8, all, bll);
        let _xorlh = self.xor(8, alh, blh);
        let _xorhl = self.xor(8, ahl, bhl);
        let _xorhh = self.xor(8, ahh, bhh);
```
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 176 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XSyHOBeVXRnjpfA8N:-O3XSyHOBeVXRnjpfA8O:b-sz6ojb) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L176)):*
> ```XML
>     }
> 
>     /// Checks that a, b are in [0, 2^w) and computes their xor.
> ```

Can you state the upper bound on w?
It doesn't work for every xor as you append `c` as felt



_Code quote:_
```XML
    /// Checks that a, b are in [0, 2^w) and computes their xor.
```
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 273 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XVECWBvB-0kkR5LyU:-O3XVECWBvB-0kkR5LyV:bb967iu) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L273)):*
> ```XML
>         let p = round_lookup_elements.combine(
>             &lookup_data
>                 .round_lookups
> ```

why don't you batch those in chunks of two?



_Code quote:_
```XML
            &lookup_data
                .round_lookups
```
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XVVwL7Tu9f5D2Qggw:-O3XVVwL7Tu9f5D2Qggx:b-q8oves) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/mod.rs#L21)):*
> ```XML
>     };
>     component.evaluate(InfoEvaluator::default())
> }
> ```

Don't we have a generic impl?



_Code quote:_
```XML
pub fn blake_round_info() -> InfoEvaluator {
    let component = BlakeRoundComponent {
        log_size: 1,
        xor_lookup_elements: BlakeXorElements::dummy(),
        round_lookup_elements: RoundElements::dummy(),
        claimed_sum: SecureField::zero(),
    };
    component.evaluate(InfoEvaluator::default())
}
```


<!-- Sent from Reviewable.io -->

2024-08-05 14:23 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 5 of 9 files reviewed, 10 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XPsKs3uEz0q-G_hb2:-O3XbEQEDu3wPPBEoHtV:b3sttqo) ([raw file](https://github.com/starkware-libs/stwo/blob/2baab80529c2c9ac986e41f830a49991d7fd28bb/crates/prover/src/constraint_framework/logup.rs#L147)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you re-add here?
</blockquote></details>

I used it for the info(), which is trace generation to get the number of columns.
___
*[`crates/prover/src/examples/blake/mod.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SpyHB1tGKtDTn-A4W:-O3Xbli0CrtFQ6clFs4C:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe here
https://en.wikipedia.org/wiki/BLAKE_(hash_function)
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/mod.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Snrv0Dj8aVcNRQb_C:-O3XuR2U8yaVSpO_Lfar:ba9gsea) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/mod.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Panic if key is not in dict?
I meant dict not an array
</blockquote></details>

I think match is more straight forward than a dict, and the compiler will have an easier time optimizing it out.
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3SrB083zzMOlfJ_yEJ:-O3XupP4D2Sq_sOLVr9f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4400c3461ea6d6f7b7f09d9e6d0b31a3c2328bc/crates/prover/src/examples/blake/round/gen.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't understand what the xor_lookups means
Specifically it is hard for me to understand what xor() func does.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XQssEDiekFc-Yzzet:-O3XlbiEB9OlY0vX-QeX:bwqizku) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L67)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to assert/debug_assert here that those are in renge [0,P)?
</blockquote></details>

Nah...
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 132 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XS-nO9JgxaCZa0Qf6:-O3Xs8wb0L9ZysMMmA1e:bq3cdpc) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L132)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to write why you only append the high part.
</blockquote></details>

I added a comment above the struct that point tot he constraints, so that you can look at both.
I think writing here everythin about the constraints is duplication.
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 150 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XSVTqAU7H-ZorV8U9:-O3XsdYCA3KQZq2ChlI4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L150)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove the return value or 

add an assert that it is correct.
assert_eq(cr, build(xor_ll, xor_lh, ..)
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 176 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XSyHOBeVXRnjpfA8N:-O3Xu-O83VRUsXuLZrsK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L176)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you state the upper bound on w?
It doesn't work for every xor as you append `c` as felt
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 273 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XVECWBvB-0kkR5LyU:-O3Xu6nl4Tw9FXeH6r8b:bno7h6j) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/gen.rs#L273)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why don't you batch those in chunks of two?
</blockquote></details>

It's the remainder. A single lookup.
All the previous ones (even number) were already batched.
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XVVwL7Tu9f5D2Qggw:-O3XuJ0yCE80VeUCZePr:b-f6oa7y) ([raw file](https://github.com/starkware-libs/stwo/blob/050ea88075ca5db3250aa7321dee92642d68210f/crates/prover/src/examples/blake/round/mod.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't we have a generic impl?
</blockquote></details>

Nope. We need to instantiate the component somehow, and that is not something provided by FrameworkComponent.


<!-- Sent from Reviewable.io -->

2024-08-05 15:02 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 9 files at r3, 1 of 2 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XPsKs3uEz0q-G_hb2:-O3Y0oSH9Dav0RfeN-v1:butqp42) ([raw file](https://github.com/starkware-libs/stwo/blob/2baab80529c2c9ac986e41f830a49991d7fd28bb/crates/prover/src/constraint_framework/logup.rs#L147)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I used it for the info(), which is trace generation to get the number of columns.
</blockquote></details>

Let's recall to change poseidon accordingly, and also think of the correct way to retreive N_COLUMNS
Can merge it for now
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 28 at r6](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XzRndC3FgrPm7TbMZ:-O3XzRndC3FgrPm7TbM_:b-bu4fda) ([raw file](https://github.com/starkware-libs/stwo/blob/fd67e73c1774621b5cd6127e3cbc195717579716/crates/prover/src/examples/blake/round/gen.rs#L28)):*
> ```XML
>     xor_lookups: Vec<(u32, [BaseColumn; 3])>,
>     /// A column of round lookup values (v_in, v_out, m).
>     round_lookups: [BaseColumn; 16 * 3 * 2],
> ```

We are going to have BlakeLookupData for the scheduler, no?



_Suggestion:_
```XML
pub struct BlakeRoundLookupData {
    /// A vector of (w, [a_col, b_col, c_col]) for each xor lookup.
    /// w is the xor width. c_col is the xor col of a_col and b_col.
    xor_lookups: Vec<(u32, [BaseColumn; 3])>,
    /// A column of round lookup values (v_in, v_out, m).
    round_lookup: [BaseColumn; 16 * 3 * 2],
```
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Y1vz97Vl1oBEjt7hO:-O3Y1vzA4VEiAtUzi3_1:b23aaao) ([raw file](https://github.com/starkware-libs/stwo/blob/fd67e73c1774621b5cd6127e3cbc195717579716/crates/prover/src/examples/blake/round/mod.rs#L88)):*
> ```XML
> 
>         let xor_lookup_elements = BlakeXorElements::dummy();
>         let round_lookup_elements = RoundElements::dummy();
> ```

Can you use non dummy elements here?



_Code quote:_
```XML
        let xor_lookup_elements = BlakeXorElements::dummy();
        let round_lookup_elements = RoundElements::dummy();
```


<!-- Sent from Reviewable.io -->

2024-08-05 15:05 UTC, spapinistarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 28 at r6](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3XzRndC3FgrPm7TbMZ:-O3Y3OwO4nmggoIa1rYi:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fd67e73c1774621b5cd6127e3cbc195717579716/crates/prover/src/examples/blake/round/gen.rs#L28)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We are going to have BlakeLookupData for the scheduler, no?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/stwo/767#-O3Y1vz97Vl1oBEjt7hO:-O3Y3cXYCCF2p6Cdbng-:b-4pqn07) ([raw file](https://github.com/starkware-libs/stwo/blob/fd67e73c1774621b5cd6127e3cbc195717579716/crates/prover/src/examples/blake/round/mod.rs#L88)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you use non dummy elements here?
</blockquote></details>

I think it's ok for tests.


<!-- Sent from Reviewable.io -->

2024-08-05 15:17 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/767#-:-O3Y6RwS1lQiD3J3Qrn3:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)



<!-- Sent from Reviewable.io -->

2024-08-05 16:42 UTC, merged