Add constraint for Logup claimed cumsum
starkware-libs/stwo pull request #830
Opened 2024-09-10 13:52 UTC by shaharsamocha7

Add optional constraint for logup claimed sum
The constraint applies only in case that the claimed_sum is not the total sum
Uses for padding components with default rows

2024-09-10 13:53 UTC, shaharsamocha7 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/830?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#830** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/830?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#829** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/829?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#825** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/825?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#818** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/818?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-19 03:39 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/stwo/830#-O77Lwlq0bTtGuHhD8bm:-O77Lwlq0bTtGuHhD8bn:bpigmyb) ([raw file](https://github.com/starkware-libs/stwo/blob/da54d68e0d4feee3edbea715321edf69184874b7/crates/prover/src/constraint_framework/logup.rs#L84)):*
> ```XML
>             Some((claimed_sum, claimed_row_index)) => {
>                 let [cur_cumsum, prev_row_cumsum, claimed_cumsum] = eval
>                     .next_extension_interaction_mask(self.interaction, [0, -1, claimed_row_index]);
> ```

It's more efficient using `is_first` column and doing the constraint with `cur_cumsum` and a row selector


<!-- Sent from Reviewable.io -->

2024-09-22 09:38 UTC, Alon-Ti requested changes
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/830#-O7O4xgwBL7c1IRrHsy_:-O7O4xgwBL7c1IRrHsya:b-36hxm6) ([raw file](https://github.com/starkware-libs/stwo/blob/da54d68e0d4feee3edbea715321edf69184874b7/crates/prover/src/constraint_framework/logup.rs#L104)):*
> ```XML
> 
>         // Constrain that the claimed_sum in case that it is not equal to the total_sum.
>         if let Some((claimed_cumsum, claimed_sum)) = claimed_cumsum {
> ```

Move this to the `match` above.


<!-- Sent from Reviewable.io -->

2024-09-22 10:24 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/stwo/830#-O77Lwlq0bTtGuHhD8bm:-O7OFawuE5RO3eTCNTWs:b-7yd1q4) ([raw file](https://github.com/starkware-libs/stwo/blob/cef3cc6832ae907f1cc0f6f98cf0d71bd994bbe6/crates/prover/src/constraint_framework/logup.rs#L84)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

It's more efficient using `is_first` column and doing the constraint with `cur_cumsum` and a row selector
</blockquote></details>

Added a TODO.
___
*[`crates/prover/src/constraint_framework/logup.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/830#-O7O4xgwBL7c1IRrHsy_:-O7OFePiDjtOVGL5BQep:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cef3cc6832ae907f1cc0f6f98cf0d71bd994bbe6/crates/prover/src/constraint_framework/logup.rs#L104)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Move this to the `match` above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-22 22:05 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/stwo/830#-O7Ql5kq8tqwZhN0QI-I:-O7Ql5kq8tqwZhN0QI-J:b-7wii6) ([raw file](https://github.com/starkware-libs/stwo/blob/f6fc394c39773ca3da1e3baea746c5ed8d012a45/crates/prover/src/constraint_framework/logup.rs#L26)):*
> ```XML
> /// Represents the value of the prefix sum column at some index.
> /// Should be used to eliminate padded rows for the logup sum.
> pub type ClaimedPrefixSum = (SecureField, isize);
> ```

Would there ever be a negative index?



_Suggestion:_
```XML
usize
```


<!-- Sent from Reviewable.io -->

2024-09-23 10:51 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/stwo/830#-O7Ql5kq8tqwZhN0QI-I:-O7TVFKZ7fDDz756rzh-:b-9y9o96) ([raw file](https://github.com/starkware-libs/stwo/blob/f6fc394c39773ca3da1e3baea746c5ed8d012a45/crates/prover/src/constraint_framework/logup.rs#L26)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Would there ever be a negative index?
</blockquote></details>

You can also feed negative numbers if you want (as the domain is cyclic)
I can change it to usize, but there would be a cast afterwords because `next_extension_interaction_mask` gets a list of isize.
Should I make the change?


<!-- Sent from Reviewable.io -->

2024-09-23 21:52 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/stwo/830#-O7Ql5kq8tqwZhN0QI-I:-O7VqZGv2CAdjUf6c4EH:b-5n8h74) ([raw file](https://github.com/starkware-libs/stwo/blob/f6fc394c39773ca3da1e3baea746c5ed8d012a45/crates/prover/src/constraint_framework/logup.rs#L26)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can also feed negative numbers if you want (as the domain is cyclic)
I can change it to usize, but there would be a cast afterwords because `next_extension_interaction_mask` gets a list of isize.
Should I make the change?
</blockquote></details>

Given it's an index I think it should be usize. Offsets make sense as isize so I think it's better to be usize here and to cast to isize when it's needed as an offset


<!-- Sent from Reviewable.io -->

2024-09-24 08:46 UTC, Alon-Ti approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830#-:-O7YCXCb8bXtEzFsYcKQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-09-24 10:57 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @andrewmilson)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/stwo/830#-O7Ql5kq8tqwZhN0QI-I:-O7YfM5-52xodmV-Z9rU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f6fc394c39773ca3da1e3baea746c5ed8d012a45/crates/prover/src/constraint_framework/logup.rs#L26)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Given it's an index I think it should be usize. Offsets make sense as isize so I think it's better to be usize here and to cast to isize when it's needed as an offset
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-25 03:34 UTC, andrewmilson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/830#-:-O7bEeWn5Uhxh1Ugfjqh:bnfp4nl)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)



<!-- Sent from Reviewable.io -->

2024-09-25 07:04 UTC, merged