Update toolchain
starkware-libs/stwo pull request #847
Opened 2024-09-22 10:04 UTC by andrewmilson

2024-09-25 08:09 UTC, alonh5 requested changes
> Reviewed 4 of 38 files at r1, 2 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/847)* status: 8 of 44 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/Cargo.toml` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cCr84Cuvmt9wBY0nj:-O7cCr84Cuvmt9wBY0nk:b-ckkv15) ([raw file](https://github.com/starkware-libs/stwo/blob/6c25d630fff6bf4341c77aee76fd5fdd398965da/crates/prover/Cargo.toml#L57)):*
> ```TOML
> rust-2018-idioms = "deny"
> unused = "deny"
> ```

Rebase and remove:
```
[package.metadata.cargo-machete]
ignored = ["downcast-rs"]
```
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cDSvg-Xs60gVkKW1a:-O7cDSvg-Xs60gVkKW1b:bg6gjhw) ([raw file](https://github.com/starkware-libs/stwo/blob/6c25d630fff6bf4341c77aee76fd5fdd398965da/crates/prover/src/core/backend/cpu/quotients.rs#L80)):*
> ```XML
> /// Precomputes the complex conjugate line coefficients for each column in each sample batch.
> ///
> /// For the `i`-th (in a sample batch) column's numerator term `alpha^i * (c * F(p) - (a * p.y +
> ```

Why am I seeing changes in comments and other changes in the code? Is it somehow related to the toolchain update?


<!-- Sent from Reviewable.io -->

2024-09-25 08:28 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/847)* status: 6 of 44 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/Cargo.toml` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cCr84Cuvmt9wBY0nj:-O7cHliXBilhqKFvrOdC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6c25d630fff6bf4341c77aee76fd5fdd398965da/crates/prover/Cargo.toml#L57)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Rebase and remove:
```
[package.metadata.cargo-machete]
ignored = ["downcast-rs"]
```
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cDSvg-Xs60gVkKW1a:-O7cF7lAAevRPw2oquAx:b-lylexz) ([raw file](https://github.com/starkware-libs/stwo/blob/6c25d630fff6bf4341c77aee76fd5fdd398965da/crates/prover/src/core/backend/cpu/quotients.rs#L80)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why am I seeing changes in comments and other changes in the code? Is it somehow related to the toolchain update?
</blockquote></details>

The new toolchain was throwing errors for comments.
Mainly complaining the summaries were too long and needing a empty line in places.


<!-- Sent from Reviewable.io -->

2024-09-25 08:50 UTC, alonh5 requested changes
> Reviewed 16 of 38 files at r1, 4 of 7 files at r2, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/847)* status: all files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`.github/workflows/ci.yaml` line 163 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cIXrjEKo4A2Zzzxcr:-O7cIXrjEKo4A2Zzzxcs:bvm7z6v) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/.github/workflows/ci.yaml#L163)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v4
> <<<<<<< HEAD
> ```

Resolve.



_Code quote:_
```YAML
<<<<<<< HEAD
```
___
*[`crates/prover/src/lib.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cIq381MeAXyQDX57W:-O7cIq381MeAXyQDX57X:b-v3tv0v) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/lib.rs#L1)):*
> ```XML
> #![allow(incomplete_features)]
> ```

Can you pleae explain the changes here?
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 288 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cLpmc3eH-sU3Wxtkh:-O7cLpmc3eH-sU3Wxtki:b3wkycv) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/backend/simd/m31.rs#L288)):*
> ```XML
> }
> 
> cfg_if::cfg_if! {
> ```

Is this also something that the new toolchain required?
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMClL8KngLsXDmIit:-O7cMClL8KngLsXDmIiu:b-r4jzu) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/backend/simd/lookups/gkr.rs#L28)):*
> ```XML
> 
>         // Start DP with CPU backend to avoid dealing with instances smaller than a SIMD vector.
>         let (y_rem, y_last_chunk) = y.split_last_chunk::<{ LOG_N_LANES as usize }>().unwrap();
> ```

How did you catch this? Did tests fail?
___
*[`crates/prover/src/core/pcs/mod.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMO5Y1SVyJUSagjN2:-O7cMO5Y1SVyJUSagjN3:b-tv6gxv) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/pcs/mod.rs#L39)):*
> ```XML
>             pow_bits: 5,
>             // fri_config: FriConfig::new(0, 1, 3),
>             fri_config: FriConfig::new(0, 1, 50),
> ```

On purpose?



_Code quote:_
```XML
            // fri_config: FriConfig::new(0, 1, 3),
            fri_config: FriConfig::new(0, 1, 50),
```
___
*[`crates/prover/src/core/vcs/blake2s_ref.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMaxf4YKMA7jht6nT:-O7cMaxf4YKMA7jht6nU:b-312bld) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/vcs/blake2s_ref.rs#L34)):*
> ```XML
> #[inline(always)]
> fn rot16(x: u32) -> u32 {
>     x.rotate_left(16)
> ```

Why is this left and all the others right? is it because for 16 it's identical?


<!-- Sent from Reviewable.io -->

2024-09-25 09:55 UTC, andrewmilson reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/847)* status: 41 of 44 files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`.github/workflows/ci.yaml` line 163 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cIXrjEKo4A2Zzzxcr:-O7cQP1-3wYIMdAdSVGV:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/.github/workflows/ci.yaml#L163)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Resolve.
</blockquote></details>

Done.
___
*[`crates/prover/src/lib.rs` line 1 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cIq381MeAXyQDX57W:-O7cQRlsEBXXMID1Hmrk:b-uoohjk) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/lib.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you pleae explain the changes here?
</blockquote></details>

`stdarch_x86_avx512` replaces `stdsimd` as the feature to use the avx512 intrinsics.
Added as `cfg_attr` since `stdarch_x86_avx512` feature only exists on x86
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 288 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cLpmc3eH-sU3Wxtkh:-O7cR2Cs4jJf5vbAVCMz:b-x42h3w) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/backend/simd/m31.rs#L288)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this also something that the new toolchain required?
</blockquote></details>

Not entirely but made sense to combine the change.
The error the toolchain had was about Swizzle, InterleaveEvens, InterleaveOdds being unused on non avx2/avx512
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMClL8KngLsXDmIit:-O7cPz5lBuzDANgv5Do3:b-j3mh2v) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/backend/simd/lookups/gkr.rs#L28)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How did you catch this? Did tests fail?
</blockquote></details>

Yes exactly.
No compile issue so was a bit perplexed at the test failures initially.
___
*[`crates/prover/src/core/pcs/mod.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMO5Y1SVyJUSagjN2:-O7cQGQa1Q5fcdsJdLit:b-jktf5b) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/pcs/mod.rs#L39)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

On purpose?
</blockquote></details>

My bad. Thanks
___
*[`crates/prover/src/core/vcs/blake2s_ref.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMaxf4YKMA7jht6nT:-O7cRecB7Dy-qnhfgTU6:b-m6k053) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/vcs/blake2s_ref.rs#L34)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is this left and all the others right? is it because for 16 it's identical?
</blockquote></details>

Oh funny, didn't notice this. Yeah I guess they are.

Rust analyser detected the bit shifts as a rotate and offered a quick fix which I applied.
Just changed it to `rotate_right` to be consistent.


<!-- Sent from Reviewable.io -->

2024-09-25 10:05 UTC, alonh5 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/847#-:-O7cd4158fnqLoaEtkGD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMClL8KngLsXDmIit:-O7ccH548djACnsIQgnp:b41u26c) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/backend/simd/lookups/gkr.rs#L28)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Yes exactly.
No compile issue so was a bit perplexed at the test failures initially.
</blockquote></details>

Weird they would change the order like that.
___
*[`crates/prover/src/core/vcs/blake2s_ref.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/stwo/847#-O7cMaxf4YKMA7jht6nT:-O7ccTBF5kfpHolj66Sf:b5jujpq) ([raw file](https://github.com/starkware-libs/stwo/blob/101a6c47d74b976e5b40c8a50cf99e05600fdec7/crates/prover/src/core/vcs/blake2s_ref.rs#L34)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Oh funny, didn't notice this. Yeah I guess they are.

Rust analyser detected the bit shifts as a rotate and offered a quick fix which I applied.
Just changed it to `rotate_right` to be consistent.
</blockquote></details>

Great thanks :)


<!-- Sent from Reviewable.io -->

2024-10-22 11:57 UTC, alonh5 reviewed
Can this PR be closed?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/847#-:-O9o4bdq3ohiJa1I4GAl:b-z9hhx5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-11-05 06:23 UTC, ShuangWu121 commented
Hi, would the toolchain be updated later though? it is a bit hard to integrate stwo to other projects due to the toolchain "nightly-2024-01-04", would be nice to have a newer version. :)

2024-11-17 16:45 UTC, ShuangWu121 commented
Hi! Nice this PR is opened again! Great job!

Our repo now is using this branch (andrew/dev/update-toolchain) due to the old tool-chain of dev branch is not compatible with our project, so we really look forward for this PR to be merged.
But if it is not happening soon, would be possible to keep this branch updated with the dev branch? I see recently there are new features of preprocessed columns are added on dev,  we'd really wish to use this new feature from this branch ^^

2025-11-20 08:46 UTC, closed without merging