Add constants for interactions.
starkware-libs/stwo pull request #864
Opened 2024-11-03 12:13 UTC by ilyalesokhin-starkware

2024-11-03 12:13 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo/864)
<!-- Reviewable:end -->

2024-11-03 13:50 UTC, ohad-starkware requested changes
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/864)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo/864#-OAmHGn9-vYTN7qbCJ7o:-OAmHGn9-vYTN7qbCJ7p:b-7ilvhb) ([raw file](https://github.com/starkware-libs/stwo/blob/42cce623d7c2fc93736a0616ca5e126a3b909eea/crates/prover/src/constraint_framework/mod.rs#L28)):*
> ```XML
> use crate::core::fields::FieldExpOps;
> 
> pub const ORIGIANL_TRACE_IDX: usize = 0;
> ```

typo


<!-- Sent from Reviewable.io -->

2024-11-03 14:17 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/864#-:-OAmNkeD1MM0RTfV197X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-11-04 08:34 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/864)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo/864#-OAmHGn9-vYTN7qbCJ7o:-OAqHXkQDh4IWRFXJzN0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/42cce623d7c2fc93736a0616ca5e126a3b909eea/crates/prover/src/constraint_framework/mod.rs#L28)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-05 06:26 UTC, merged