Add gen_preprocessed_columns.
starkware-libs/stwo pull request #891
Opened 2024-11-18 07:36 UTC by ilyalesokhin-starkware

2024-11-18 07:36 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo/891)
<!-- Reviewable:end -->

2024-11-24 12:34 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/891)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/stwo/891#-OCT81eP3hv8YZyJYgkl:-OCT81eP3hv8YZyJYgkm:bdglipk) ([raw file](https://github.com/starkware-libs/stwo/blob/31e1f3cee874c8ae4d627d8766bc56be03ba6fc8/crates/prover/src/constraint_framework/component.rs#L83)):*
> ```XML
> 
>     /// Create a new `TraceLocationAllocator` with fixed preprocessed columns setup.
>     pub fn new_with_preproccessed_columnds(preprocessed_columns: &[PreprocessedColumn]) -> Self {
> ```

typo, can you fix?



_Suggestion:_
```XML
pub fn new_with_preproccessed_columns
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/stwo/891#-OCT8AjWAzFIfnnLsX8R:-OCT8AjWAzFIfnnLsX8S:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/31e1f3cee874c8ae4d627d8766bc56be03ba6fc8/crates/prover/src/constraint_framework/component.rs#L100)):*
> ```XML
> 
>     // validates that `self.preprocessed_columns` contains is consistent with
>     // `preprocessed_columns`.
> ```





_Suggestion:_
```XML
    // validates that `self.preprocessed_columns` is consistent with
    // `preprocessed_columns`.
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/stwo/891#-OCT90VB48uAtpU_vyxz:-OCT90VB48uAtpU_vyy-:b-v2ai0m) ([raw file](https://github.com/starkware-libs/stwo/blob/31e1f3cee874c8ae4d627d8766bc56be03ba6fc8/crates/prover/src/constraint_framework/component.rs#L102)):*
> ```XML
>     // `preprocessed_columns`.
>     pub fn validate_preprocessed_columns(&self, preprocessed_columns: &[PreprocessedColumn]) {
>         assert_eq!(preprocessed_columns.len(), self.preprocessed_columns.len());
> ```

why do you have this assert?
I'm not sure I understand this function 

I would imagine that this function need to check that your columns are in the tree somewhere



_Code quote:_
```XML
assert_eq!(preprocessed_columns.len(), self.preprocessed_columns.len());
```


<!-- Sent from Reviewable.io -->

2024-11-25 06:43 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/891)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/stwo/891#-OCT90VB48uAtpU_vyxz:-OCX2O9-0UgFamVo5JM4:bmv4yo1) ([raw file](https://github.com/starkware-libs/stwo/blob/31e1f3cee874c8ae4d627d8766bc56be03ba6fc8/crates/prover/src/constraint_framework/component.rs#L102)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why do you have this assert?
I'm not sure I understand this function 

I would imagine that this function need to check that your columns are in the tree somewhere
</blockquote></details>

it checks that the columns were assigned as expected.
___
*[`crates/prover/src/constraint_framework/component.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/stwo/891#-OCT8AjWAzFIfnnLsX8R:-OCX2LCE9dOWjExE2mvH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/31e1f3cee874c8ae4d627d8766bc56be03ba6fc8/crates/prover/src/constraint_framework/component.rs#L100)):*
> ```XML
> 
>     // validates that `self.preprocessed_columns` contains is consistent with
>     // `preprocessed_columns`.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-11-25 07:35 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/891#-:-OCXEr-E1rxbHLDt7pUB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-11-25 09:19 UTC, merged