Add secure powers generation for simd
starkware-libs/stwo pull request #930
Opened 2024-12-10 11:17 UTC by Gali-StarkWare

2024-12-10 11:17 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo/930)
<!-- Reviewable:end -->

2024-12-10 11:17 UTC, Gali-StarkWare commented
* **#930** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/930?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/930?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-10 11:25 UTC, ohad-starkware reviewed
Perhaps I didn't explain properly
the function should take alpha, n_powers and return Vec<M31>, that is the n_powers powers of alpha (exclusive) : 0, a, a^2....a^(n-1)
use larger vectors to perform multiple operations at a time

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930#-:-ODkImip7OLUq3c5q-R_:b-za60sf)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-12-10 13:02 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkaa1S4F_I25gCqsp9:-ODkaZmvBq0ZBV6LqmH8:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L62)):*
> ```XML
> // TODO(Gali): Remove #[allow(dead_code)].
> #[allow(dead_code)]
> pub fn generate_secure_powers_for_simd(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
> ```





_Suggestion:_
```XML
pub fn generate_secure_powers_simd(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkd0LP6hNmOaOh5Bro:-ODkd0LP6hNmOaOh5Brp:b26skqm) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L63)):*
> ```XML
> #[allow(dead_code)]
> pub fn generate_secure_powers_for_simd(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
>     let step_arr: [SecureField; N_LANES] = (0..N_LANES)
> ```

that logic is already written in the CPU function, use it?
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkcrjB0yW2ogLhJhp-:-ODkcrjB0yW2ogLhJhp0:b-7w4z8o) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L69)):*
> ```XML
>             Some(res)
>         })
>         .collect::<Vec<SecureField>>()
> ```

less noise



_Suggestion:_
```XML
.collect_vec()
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkaeGJEa5qz9v3Us9v:-ODkaeGJEa5qz9v3Us9w:bbuewvv) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L71)):*
> ```XML
>         .collect::<Vec<SecureField>>()
>         .try_into()
>         .expect("Failed generating secure powers.");
> ```

I think it's alright to .unwrap() here, you won't fail the try_into...
non - blocking 
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkbIXR0gCxfuVTYWst:-ODkbIXR0gCxfuVTYWsu:b1dh1zt) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L77)):*
> ```XML
>     let step_felt = step_arr[N_LANES - 1] * felt;
> 
>     let mut packed_powers_vec = Vec::new();
> ```

this is a good place to use vec::with_capacity
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkbPRWBIGjYC41cTSr:-ODkbPRWBIGjYC41cTSs:b-whh1kq) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L80)):*
> ```XML
>     let mut curr_power: usize = 0;
> 
>     while curr_power < n_powers {
> ```

consider using scan land collect ike you did above, easier to read
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkb-wG19ORpzLHN17v:-ODkb-wG19ORpzLHN17w:b-5yofod) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L81)):*
> ```XML
> 
>     while curr_power < n_powers {
>         let base_packed_felt = PackedSecureField::from_array([base_felt; N_LANES]);
> ```

I think you can avoid ::from_array inside the loop, this is a load and is somewhat expensive
perhaps define the step as Simd([a^16; 16]), and multiply the current value with it each time (your step is a small register)
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkccbf415fHPRIVSW9:-ODkccbf415fHPRIVSWA:b-7hsrch) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L81)):*
> ```XML
> 
>     while curr_power < n_powers {
>         let base_packed_felt = PackedSecureField::from_array([base_felt; N_LANES]);
> ```

also you can use broadcast to get [value; N_LANE] cheaper
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdUAYCTk6oa6AWUfy:-ODkdUAYCTk6oa6AWUfz:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L87)):*
> ```XML
>     }
> 
>     let powers_vec: Vec<SecureField> = packed_powers_vec
> ```





_Suggestion:_
```XML
    let secure_powers = packed_powers_vec
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdb2-BXlHMl0Zk6XL:-ODkdb2-BXlHMl0Zk6XM:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L88)):*
> ```XML
> 
>     let powers_vec: Vec<SecureField> = packed_powers_vec
>         .iter()
> ```





_Suggestion:_
```XML
.into_iter()
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdjUS9JHsNMaqkU2m:-ODkdjUS9JHsNMaqkU2n:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L90)):*
> ```XML
>         .iter()
>         .flat_map(|x| x.to_array().to_vec())
>         .collect();
> ```





_Suggestion:_
```XML
collect_vec();
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdEzu8iRLAVj1Iynj:-ODkdEzu8iRLAVj1Iynk:b8cuvkw) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L92)):*
> ```XML
>         .collect();
> 
>     powers_vec[0..n_powers].to_vec()
> ```

you're doing 2 copies here, I think you can reduce that to 0 (trim the front/back...?)



_Code quote:_
```XML
    let powers_vec: Vec<SecureField> = packed_powers_vec
        .iter()
        .flat_map(|x| x.to_array().to_vec())
        .collect();

    powers_vec[0..n_powers].to_vec()
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkc5I18ltZMZjrGijE:-ODkc5I18ltZMZjrGijF:behay9v) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L129)):*
> ```XML
>     fn generate_secure_powers_works() {
>         let felt = qm31!(1, 2, 3, 4);
>         let n_powers = 10;
> ```

if you had a bug (you don't) with n > 16 this test would not catch it, use a bigger number.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdzx-8jsf_SDtx-Jo:-ODkdzx-8jsf_SDtx-Jp:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L134)):*
> ```XML
> 
>         assert_eq!(powers.len(), n_powers);
>         assert_eq!(powers[0], SecureField::one());
> ```





_Suggestion:_
```XML
        let cpu_powers = generate_secure_powers(felt, n_powers)
        
        let powers = generate_secure_powers_for_simd(felt, n_powers);

        assert_eq!(powers, cpu_powers);
```
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 140 at r2](https://reviewable.io/reviews/starkware- [...]

2024-12-10 13:04 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkeqt39yIdVO39dlCY:-ODkeqt39yIdVO39dlCZ:b-8694mj) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L127)):*
> ```XML
> 
>     #[test]
>     fn generate_secure_powers_works() {
> ```

rename the tests


<!-- Sent from Reviewable.io -->

2024-12-10 14:35 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkd0LP6hNmOaOh5Bro:-ODkhWoH1sBins8K7wY_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L63)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

that logic is already written in the CPU function, use it?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkcrjB0yW2ogLhJhp-:-ODkhgOH8xoyItFR5Xmk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L69)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

less noise
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkbIXR0gCxfuVTYWst:-ODkjrkRDknr5GWn4490:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L77)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this is a good place to use vec::with_capacity
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkbPRWBIGjYC41cTSr:-ODkvUIq4O0KxgTNrdq3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L80)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

consider using scan land collect ike you did above, easier to read
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkb-wG19ORpzLHN17v:-ODkwphQA7kO_WzhiLdZ:b1ppm86) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L81)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I think you can avoid ::from_array inside the loop, this is a load and is somewhat expensive
perhaps define the step as Simd([a^16; 16]), and multiply the current value with it each time (your step is a small register)
</blockquote></details>

Done. Swapped base-step variables names as well
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkccbf415fHPRIVSW9:-ODkzk2QANjZ9mXDUXo5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L81)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

also you can use broadcast to get [value; N_LANE] cheaper
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdEzu8iRLAVj1Iynj:-ODklxr2AGTUAg_qgMGL:b-o3ears) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L92)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you're doing 2 copies here, I think you can reduce that to 0 (trim the front/back...?)
</blockquote></details>

Done.  Not sure that I got it
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkeqt39yIdVO39dlCY:-ODkp9Q-CAz_fTy6Oe1b:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L127)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

rename the tests
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkc5I18ltZMZjrGijE:-ODkoDQK-48uzlFUT5ZQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L129)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

if you had a bug (you don't) with n > 16 this test would not catch it, use a bigger number.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkc0JwDnpKUhO3rAUa:-ODkoQ4mEW_SBPtKCdc2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L140)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I don't think this edge case is of concern, remove.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkaa1S4F_I25gCqsp9:-ODkgdu90jQy6U5fbMK5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L62)):*
> ```XML
> // TODO(Gali): Remove #[allow(dead_code)].
> #[allow(dead_code)]
> pub fn generate_secure_powers_for_simd(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdUAYCTk6oa6AWUfy:-ODklDgKDxFYwXtS9aAZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L87)):*
> ```XML
>     }
> 
>     let powers_vec: Vec<SecureField> = packed_powers_vec
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdb2-BXlHMl0Zk6XL:-ODkl7cdBvHv_eSFlY51:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L88)):*
> ```XML
> 
>     let powers_vec: Vec<SecureField> = packed_powers_vec
>         .iter()
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdjUS9JHsNMaqkU2m:-ODkl6ZJ9pp2DW_MQX1J:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L90)):*
> ```XML
>         .iter()
>         .flat_map(|x| x.to_array().to_vec())
>         .collect();
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdzx-8jsf_SDtx-Jo:-ODkorcd-cKh_lhaeFaV:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L134)):*
> ```XML
> 
>         assert_eq!(powers.len(), n_powers);
>         assert_eq!(powers[0], SecureField::one());
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 14:54 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-ODl332D2iTyoC6eVHIN:bxn4346) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
> ```XML
>     fn generate_secure_powers_simd_returns_the_same_as_cpu() {
>         let felt = qm31!(1, 2, 3, 4);
>         let n_powers = 30;
> ```

bigger?


<!-- Sent from Reviewable.io -->

2024-12-10 15:04 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODkdEzu8iRLAVj1Iynj:-ODl4CzJ8Dhjlz3wvvA0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/06768d9394b2939cd28209ce539257ffe236d8a1/crates/prover/src/core/backend/simd/utils.rs#L92)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

the collect_vec().into_iter() is redundant, you already have an iterator (scan), that collect is a copy for nothing
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl2tAs98WBR3rrhB2s:-ODl4Bg_Cwna2ev07mRj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L85)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this invoked a heap allocation for every vector :(
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl2Xm76lVrc9VMo5xo:-ODl5McMA-INJh8wDIMJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L85)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

x.to_array() is a copy, use transmute?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-ODl4Puj-J_onF3MAfs2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

bigger?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl0WYX895aOOd63u2L:-ODl3cTn11KL5KkvlDGF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L64)):*
> ```XML
> #[allow(dead_code)]
> pub fn generate_secure_powers_simd(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
>     let base_arr: [SecureField; N_LANES] =
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl1NzK6qgsItYduC2e:-ODl3vPS71Bfdoxigtb1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L75)):*
> ```XML
>     } else {
>         (n_powers / N_LANES) + 1
>     };
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl0E5p3OW4tnPz4z9d:-ODl4NhD9LZ-7CB5OEfF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L119)):*
> ```XML
> 
>     #[test]
>     fn generate_secure_powers_simd_returns_the_same_as_cpu() {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 15:10 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl2Xm76lVrc9VMo5xo:-ODl6asX2uGq6H_OHlqB:b-acndr5) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L85)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry the transmute is a lie I forgot were in the extension field


<!-- Sent from Reviewable.io -->

2024-12-10 15:20 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl0dKuCgDRWt8B6g67:-ODl7FP8ASE8u8mEOPIE:b-qiyzqr) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L69)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

style
non-blocking
</blockquote></details>

alternatively 
`let felt_pows = PackedSecureField::from_array(generate_secure_powers(felt, N_LANES).try_into().unwrap());`
`let felt_pow_n_lanes = PackedSecureField::broadcast(base_arr[N_LANES - 1] * felt);`
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl1NzK6qgsItYduC2e:-ODl7ko9C62G8JGyRCci:bsffh51) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L75)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

there is a function
`n_powers.div_ceil(N_LANES)`
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl0E5p3OW4tnPz4z9d:-ODl81Yb9vrVczrr1ptd:b1s25in) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L119)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

To be more explicit:
Test name should describe what the test is checking rather than the implementation itself.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl8jEiBfWEgqsJCR77:-ODl8jEiBfWEgqsJCR78:bsgb4j3) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L125)):*
> ```XML
>         let cpu_powers = generate_secure_powers(felt, n_powers);
>         let powers = generate_secure_powers_simd(felt, n_powers);
>         assert_eq!(powers, cpu_powers);
> ```

Add a new line here
https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/



_Suggestion:_
```XML
        let powers = generate_secure_powers_simd(felt, n_powers);
        
        assert_eq!(powers, cpu_powers);
```


<!-- Sent from Reviewable.io -->

2024-12-10 15:52 UTC, Gali-StarkWare reviewed
Also changed some variables' names, LMK if it's better

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930#-:-ODlFjXiA_0bokXEQ5sM:bg354n8)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl1NzK6qgsItYduC2e:-ODlDJ3e6e68aVzo3FKF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L75)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

there is a function
`n_powers.div_ceil(N_LANES)`
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl2Xm76lVrc9VMo5xo:-ODlDKrB-K4QHsj0C4Kv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L85)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

sorry the transmute is a lie I forgot were in the extension field
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl0E5p3OW4tnPz4z9d:-ODlDeYvD1cSY0dT_x6V:bn83cee) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L119)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

To be more explicit:
Test name should describe what the test is checking rather than the implementation itself.
</blockquote></details>

I thought that specifying that we want the same functionality as the of the other function is good for future changes (if we'll ever change one of them to do something different), but I guess there's no point doing that..
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 125 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl8jEiBfWEgqsJCR77:-ODlDY5N3AavBNAcbYys:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L125)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a new line here
https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-15 06:39 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-OE817an7KsPvWH6vOrn:b-6qosul) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Actually why n_powers is so large?
we don't want this test to take too much time.

If so, maybe there are edge cases where n_powers is small.
</blockquote></details>

I thougth something like a 100, larger than two SIMD vectors ant not a multiple of 16
there is an edge case for <16 and 0, My thoughts were that you are already using the CPU function in your implementation, so comparing against that can be redundant when the function is simple.
I'm not sure so wait for Shahar's input on this.


<!-- Sent from Reviewable.io -->

2024-12-15 07:12 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-OE88lW14fcFstEgkVgr:bh64q62) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I thougth something like a 100, larger than two SIMD vectors ant not a multiple of 16
there is an edge case for <16 and 0, My thoughts were that you are already using the CPU function in your implementation, so comparing against that can be redundant when the function is simple.
I'm not sure so wait for Shahar's input on this.
</blockquote></details>

100 is fine IMO.
I would also check <16 but it's nice to have.
non-blocking


<!-- Sent from Reviewable.io -->

2024-12-16 06:53 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl0E5p3OW4tnPz4z9d:-OEDDlLQ9XlFG1rz7dNX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L119)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The function purpose is to generate_secure_powers (with simd).
It will still exists if we deleted the cpu implementation.

The way you chose to test it is by checking equivalency to the cpu function.
Problem with adding it to the test name is that implementations tend to change (without changing the test name) while the purpose is more solid.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-OEDE06311tficYfybwJ:b-xel3c9) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

100 is fine IMO.
I would also check <16 but it's nice to have.
non-blocking
</blockquote></details>

Should I add the <16 check in the same test or in a new one? Based on the test's naming and the discussion above it should be in the same test, just making sure


<!-- Sent from Reviewable.io -->

2024-12-16 07:35 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-OEDNgHFC_9c-Gt96pP4:b-t15f9b) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Should I add the <16 check in the same test or in a new one? Based on the test's naming and the discussion above it should be in the same test, just making sure
</blockquote></details>

The way I see it you can either adapt the test such that 
`n_powers_vec = [16, 100]`

or split it to two tests
`test_generate_secure_powers_simd_small`
`test_generate_secure_powers_simd_large`

In this specific case I would go with option 1, but your call


<!-- Sent from Reviewable.io -->

2024-12-16 07:45 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r3](https://reviewable.io/reviews/starkware-libs/stwo/930#-ODl332D2iTyoC6eVHIM:-OEDQ9GRByrkWkC5CBuq:bxck1v4) ([raw file](https://github.com/starkware-libs/stwo/blob/c35fcd7c6df5e3a4228e7d923e5d89fa49a3e3d1/crates/prover/src/core/backend/simd/utils.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The way I see it you can either adapt the test such that 
`n_powers_vec = [16, 100]`

or split it to two tests
`test_generate_secure_powers_simd_small`
`test_generate_secure_powers_simd_large`

In this specific case I would go with option 1, but your call
</blockquote></details>

Done. Also added 0


<!-- Sent from Reviewable.io -->

2024-12-16 08:29 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDKZ0v0ENSOpkp7G3r:-OEDKZ0v0ENSOpkp7G3s:bt8p3c3):*
please squash the commits 


<!-- Sent from Reviewable.io -->

2024-12-16 08:31 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/stwo/930#-OED_iEY1ILIhsuOg3Yk:-OED_iEY1ILIhsuOg3Yl:b-mv1umo) ([raw file](https://github.com/starkware-libs/stwo/blob/83f46038dca52b7e47c479912b9ef870bf048219/crates/prover/src/core/backend/simd/utils.rs#L114)):*
> ```XML
>         let n_powers_vec = [0, 16, 100];
> 
>         let cpu_powers_vec: Vec<Vec<SecureField>> = n_powers_vec
> ```

you're doing 3 separate tests, have 3 corresponding asserts 
so if one fails you know which of the edge cases are failing 


<!-- Sent from Reviewable.io -->

2024-12-16 08:43 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDKZ0v0ENSOpkp7G3r:-OEDccLf8diCOdlT024b:b-896fix):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

please squash the commits
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/stwo/930#-OED_iEY1ILIhsuOg3Yk:-OEDbGt64gqPNajem8qs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/83f46038dca52b7e47c479912b9ef870bf048219/crates/prover/src/core/backend/simd/utils.rs#L114)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you're doing 3 separate tests, have 3 corresponding asserts 
so if one fails you know which of the edge cases are failing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-16 08:48 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 126 at r8](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDcYBzB0nFTqO6GSR3:-OEDcYBzB0nFTqO6GSR4:b-3kx7e6) ([raw file](https://github.com/starkware-libs/stwo/blob/60828bf7fe0d3c9ee4b78ac6e6bb67c1d38e8251/crates/prover/src/core/backend/simd/utils.rs#L126)):*
> ```XML
>         assert_eq!(simd_powers_vec[0], cpu_powers_vec[0]);
>         assert_eq!(simd_powers_vec[1], cpu_powers_vec[1]);
>         assert_eq!(simd_powers_vec[2], cpu_powers_vec[2]);
> ```

That code is not robust in the sense that if you will want to add another test case you'll also have to make the change here.
We don't want to limit our code for no reason

I put a suggestion for refactor, LMK what you think



_Suggestion:_
```XML
        n_powers_vec.iter().for_each(|&n_powers| {
            let expected = generate_secure_powers(felt, n_powers);
            let actual = generate_secure_powers_simd(felt, n_powers);

            assert_eq!(expected, actual);
        });
```


<!-- Sent from Reviewable.io -->

2024-12-16 08:53 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDKZ0v0ENSOpkp7G3r:-OEDefroABt5YGytRYJQ:b-ob93xc):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

are you sure? 
I expected a single line commit message
___
*[`crates/prover/src/core/backend/simd/utils.rs` line 126 at r8](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDcYBzB0nFTqO6GSR3:-OEDewo2BmePGOf8Gd1j:bekcp88) ([raw file](https://github.com/starkware-libs/stwo/blob/60828bf7fe0d3c9ee4b78ac6e6bb67c1d38e8251/crates/prover/src/core/backend/simd/utils.rs#L126)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

That code is not robust in the sense that if you will want to add another test case you'll also have to make the change here.
We don't want to limit our code for no reason

I put a suggestion for refactor, LMK what you think
</blockquote></details>

i'd also add n_powers to the panic message


<!-- Sent from Reviewable.io -->

2024-12-16 09:02 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 126 at r8](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDcYBzB0nFTqO6GSR3:-OEDekBE2p0QOUde7Zxn:b1jt3oz) ([raw file](https://github.com/starkware-libs/stwo/blob/60828bf7fe0d3c9ee4b78ac6e6bb67c1d38e8251/crates/prover/src/core/backend/simd/utils.rs#L126)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

i'd also add n_powers to the panic message
</blockquote></details>

I think so too. Added these asserts because Ohad requested to and I do agree with him that it will be easier to debug his way. Should have thought of a better way to do so. This way is nicer - it's both generic in terms of the number of test cases and will fail the specific test case.


<!-- Sent from Reviewable.io -->

2024-12-16 09:30 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEDKZ0v0ENSOpkp7G3r:-OEDnNdF3EfpBMki5s8X:b-896fix):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

are you sure? 
I expected a single line commit message
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-16 11:04 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/930#-:-OEE7w5-B0OYn4yK8TVE:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`crates/prover/src/core/backend/simd/utils.rs` line 121 at r13](https://reviewable.io/reviews/starkware-libs/stwo/930#-OEE7YVo7FEf7dfZer9c:-OEE7YVp330xBtAComlk:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/3a203f69ef55610cb5adeb744dd11ba3b2fd7b50/crates/prover/src/core/backend/simd/utils.rs#L121)):*
> ```XML
>             assert_eq!(
>                 expected, actual,
>                 "Error generating secure powers in n_powers = {}.",
> ```




<!-- Sent from Reviewable.io -->

2024-12-18 10:58 UTC, Gali-StarkWare commented
### Merge activity

* **Dec 18, 5:58 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/930).

2024-12-18 10:59 UTC, merged