example lookup data
starkware-libs/stwo pull request #944
Opened 2024-12-23 11:08 UTC by ohad-starkware

2024-12-23 11:08 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo/944)
<!-- Reviewable:end -->

2024-12-23 11:09 UTC, ohad-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/944?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#944** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/944?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/944?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#943** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/943?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#942** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/942?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-26 12:00 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/944)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF0zmIRDvvmOBVp12aG:-OF0zmIRDvvmOBVp12aH:b-5njxgc) ([raw file](https://github.com/starkware-libs/stwo/blob/9ce7a418339cdc1eaa29e8cb3f55175cb0420837/crates/air_utils/src/trace/examle_lookup_data.rs#L14)):*
> ```XML
>     pub unsafe fn uninitialized(log_size: u32) -> Self {
>         let length = 1 << log_size;
>         let n_simd_elems = length / N_LANES;
> ```

safe_div



_Code quote:_
```XML
let n_simd_elems = length / N_LANES;
```
___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1n9yi7jTJVkva5qMa:-OF1n9yi7jTJVkva5qMb:bqquqvn) ([raw file](https://github.com/starkware-libs/stwo/blob/8a54efe07f71b5346a8f956a3fa4030a68d04375/crates/air_utils/src/trace/examle_lookup_data.rs#L6)):*
> ```XML
> use stwo_prover::core::backend::simd::m31::{PackedM31, N_LANES};
> 
> pub struct LookupData {
> ```

I think this struct should be documented.
Write explicitly that lu0, lu1 are assumed to be of the same length



_Code quote:_
```XML
pub struct LookupData {
```
___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1mbNU9nRrzIzkBU1j:-OF1mbNV-kSc6CoPXdH7:b-2d7hjp) ([raw file](https://github.com/starkware-libs/stwo/blob/8a54efe07f71b5346a8f956a3fa4030a68d04375/crates/air_utils/src/trace/examle_lookup_data.rs#L8)):*
> ```XML
> pub struct LookupData {
>     pub lu0: Vec<[PackedM31; 2]>,
>     pub lu1: Vec<[PackedM31; 4]>,
> ```

Consider to change field0 to be a single felt



_Suggestion:_
```XML
    pub field0: Vec<PackedM31>,
    pub field1: Vec<[PackedM31; 2]>,
```
___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1nNCL61Wavk5Tj7Rl:-OF1nNCL61Wavk5Tj7Rm:bmzb98v) ([raw file](https://github.com/starkware-libs/stwo/blob/8a54efe07f71b5346a8f956a3fa4030a68d04375/crates/air_utils/src/trace/examle_lookup_data.rs#L11)):*
> ```XML
> }
> impl LookupData {
>     /// # Safety
> ```

Please add why this is safe (you only write to the struct without reading)



_Code quote:_
```XML
/// # Safety
```
___
*[`crates/air_utils/src/trace/mod.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1pX4ZEX6hXSv5DV7v:-OF1pX4ZEX6hXSv5DV7w:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo/blob/9ce7a418339cdc1eaa29e8cb3f55175cb0420837/crates/air_utils/src/trace/mod.rs#L3)):*
> ```XML
> pub mod component_trace;
> mod row_iterator;
> pub mod examle_lookup_data;
> ```

rename



_Suggestion:_
```XML
pub mod example_lookup_data;
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1paGh2QWj49IcQ5uH:-OF1paGh2QWj49IcQ5uI:b-dvqwll) ([raw file](https://github.com/starkware-libs/stwo/blob/9ce7a418339cdc1eaa29e8cb3f55175cb0420837/crates/air_utils/src/trace/component_trace.rs#L4)):*
> ```XML
> use itertools::Itertools;
> use rayon::iter::plumbing::{bridge, Consumer, Producer, ProducerCallback, UnindexedConsumer};
> use rayon::prelude::*;
> ```

cfg parallel?



_Code quote:_
```XML
use itertools::Itertools;
use rayon::iter::plumbing::{bridge, Consumer, Producer, ProducerCallback, UnindexedConsumer};
use rayon::prelude::*;
```


<!-- Sent from Reviewable.io -->

2024-12-26 13:02 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/944)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 14 at r4](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF0zmIRDvvmOBVp12aG:-OF22Kie2wa6RbtX3A3R:b-4y3tps) ([raw file](https://github.com/starkware-libs/stwo/blob/9ce7a418339cdc1eaa29e8cb3f55175cb0420837/crates/air_utils/src/trace/examle_lookup_data.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

safe_div
</blockquote></details>

you got something better
___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1n9yi7jTJVkva5qMa:-OF20D60DYnp2_yBaVQz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8a54efe07f71b5346a8f956a3fa4030a68d04375/crates/air_utils/src/trace/examle_lookup_data.rs#L6)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think this struct should be documented.
Write explicitly that lu0, lu1 are assumed to be of the same length
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1mbNU9nRrzIzkBU1j:-OF20Fd7DRU4MTfDMq6X:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/8a54efe07f71b5346a8f956a3fa4030a68d04375/crates/air_utils/src/trace/examle_lookup_data.rs#L8)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to change field0 to be a single felt
</blockquote></details>

done
___
*[`crates/air_utils/src/trace/examle_lookup_data.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1nNCL61Wavk5Tj7Rl:-OF21xQh6UXqyvzV6iWA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8a54efe07f71b5346a8f956a3fa4030a68d04375/crates/air_utils/src/trace/examle_lookup_data.rs#L11)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please add why this is safe (you only write to the struct without reading)
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/mod.rs` line 3 at r4](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1pX4ZEX6hXSv5DV7v:-OF22hQ_0sSZj2-SJaPl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9ce7a418339cdc1eaa29e8cb3f55175cb0420837/crates/air_utils/src/trace/mod.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/component_trace.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/stwo/944#-OF1paGh2QWj49IcQ5uH:-OF22iF--SsuPuwSXUmw:b-3obdby) ([raw file](https://github.com/starkware-libs/stwo/blob/9ce7a418339cdc1eaa29e8cb3f55175cb0420837/crates/air_utils/src/trace/component_trace.rs#L4)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

cfg parallel?
</blockquote></details>

I believe this is premature 
introducing this cfg for stwo-cairo will add a lot of noise and it's harder to debug 


<!-- Sent from Reviewable.io -->

2024-12-26 14:12 UTC, closed without merging