Add Seq type and packed_at func to PreprocessedColumn
starkware-libs/stwo pull request #951
Opened 2024-12-26 09:34 UTC by Gali-StarkWare

2024-12-26 09:34 UTC, reviewable-StarkWare commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo/951)
<!-- Reviewable:end -->

2024-12-26 09:34 UTC, Gali-StarkWare commented
* **#951** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/951?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/951?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-26 11:34 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 165 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jbm9CW3G7C6uHOzd:-OF1jbm9CW3G7C6uHOze:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L165)):*
> ```XML
>             );
>         }
>     }
> ```





_Suggestion:_
```XML
        let log_size = 8;
        let is_first = super::PreprocessedColumn::IsFirst(log_size);
        let expected_not_first = [BaseField::zero(); N_LANES];

        assert_eq!(packed_at(0).to_array()[0], BaseField::one());
        for i in 1..N_LANES {
            assert_eq!(packed_0.to_array()[i], BaseField::zero());
        }
        for i in 1..log_size {
            assert_eq!(
                is_first.packed_at(i as usize).to_array(),
                expected_not_first
            );
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-12-26 11:35 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1i3726O3aCqWxAEs7:-OF1i3726O3aCqWxAEs8:b-9j0h89) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L122)):*
> ```XML
> 
>     #[test]
>     fn test_gen_seq() {
> ```

this might be controversial - 
gen_seq is so simple, that what you're testing here is actually basefield::from_iter.
I would not unit test function at all. 
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1iqku7oMCHCFLeoT-:-OF1iqku7oMCHCFLeoT0:b-tuyokd) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L123)):*
> ```XML
>     #[test]
>     fn test_gen_seq() {
>         let log_size = 8;
> ```

consider defning this as a const on the module level (mod tests) 
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1ixNh8N83X-0tDKsl:-OF1ixNh8N83X-0tDKsm:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L134)):*
> ```XML
>     fn test_packed_at_seq() {
>         let log_size = 8;
>         let seq = super::PreprocessedColumn::Seq(8);
> ```





_Suggestion:_
```XML
log_size
```
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1j0yQ0c8gaQaKtf_6:-OF1j0yQ0c8gaQaKtf_7:b-choqci) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L138)):*
> ```XML
>         for i in 0..(1 << log_size) / N_LANES {
>             let packed = seq.packed_at(i);
>             for j in 0..N_LANES {
> ```

use std::array::from_fn to build the array and use assert_eq! on the arrays
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OF1jROD-9xULP3K5nqP:b-7l1fw2) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
> ```XML
>         for i in 1..N_LANES {
>             assert_eq!(packed_0.to_array()[i], BaseField::zero());
>         }
> ```

use .to_cpu() and all()



_Code quote:_
```XML
        for i in 1..N_LANES {
            assert_eq!(packed_0.to_array()[i], BaseField::zero());
        }
```
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1k--B8JXPm4TlQsbX:-OF1k--B8JXPm4TlQsbY:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L164)):*
> ```XML
>                 expected_not_first
>             );
>         }
> ```





_Suggestion:_
```XML
        for i in 1..log_size {
            assert_eq!(
                is_first.packed_at(i as usize).to_array(),
                [M31::zero(); N_LANES]
            );
        }
```


<!-- Sent from Reviewable.io -->

2024-12-26 11:40 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1kgfMEZugJzk7NByQ:-OF1kgfMEZugJzk7NByR:b-npn3qp) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L41)):*
> ```XML
>                     .unwrap();
>                 PackedM31::from_array(row)
>             }
> ```

the constant should sit somewhere else
that collect<Vec<>> is very bad for performance, try to avoid mallocing in loops 



_Suggestion:_
```XML
            PreprocessedColumn::Seq(log_size) => {
                assert!(vec_row <= (1 << log_size) / N_LANES);
                let value = PackedM31::broadcast(vec_row * N_LANES) + INC;
            }
            
            const INC = Simd::from_array([0..16]);
```


<!-- Sent from Reviewable.io -->

2024-12-26 11:41 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1kgfMEZugJzk7NByQ:-OF1lPkJA0ByHYzMglmt:b6i5ke1) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L41)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

the constant should sit somewhere else
that collect<Vec<>> is very bad for performance, try to avoid mallocing in loops
</blockquote></details>

https://github.com/starkware-libs/stwo-cairo/blob/fa8c976dd315771bd4f3f0a151e5df796f5d3f12/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L13-L15


<!-- Sent from Reviewable.io -->

2024-12-26 15:37 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1kgfMEZugJzk7NByQ:-OF2SEme7j544MHTCBAG:b-ahy4o2) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L41)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

https://github.com/starkware-libs/stwo-cairo/blob/fa8c976dd315771bd4f3f0a151e5df796f5d3f12/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L13-L15
</blockquote></details>

Done. I put it next to the declaration of N_LANES, tell me what you think.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1i3726O3aCqWxAEs7:-OF2XAUOEbdQSdhT1kIv:bh72mk8) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L122)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this might be controversial - 
gen_seq is so simple, that what you're testing here is actually basefield::from_iter.
I would not unit test function at all.
</blockquote></details>

@shaharsamocha7  I tend to agree, what do you say?
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1iqku7oMCHCFLeoT-:-OF2bFZ94u8zVZICk_T8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L123)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

consider defning this as a const on the module level (mod tests)
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OF2UKLc3nHdHWRdNymL:b4tam5t) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

use .to_cpu() and all()
</blockquote></details>

Reorganised the tests, what do you think? 
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1ixNh8N83X-0tDKsl:-OF2SaadAalx1nhKlbq9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L134)):*
> ```XML
>     fn test_packed_at_seq() {
>         let log_size = 8;
>         let seq = super::PreprocessedColumn::Seq(8);
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-26 17:22 UTC, ohad-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1kgfMEZugJzk7NByQ:-OF2x5vPEJoyvbzHjgpE:bvmgzgn) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L41)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done. I put it next to the declaration of N_LANES, tell me what you think.
</blockquote></details>

I hate it.
it's only used here for now, so let it be here.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1i3726O3aCqWxAEs7:-OF2xMI05lCefgB87BA9:b7oiie) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L122)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

@shaharsamocha7  I tend to agree, what do you say?
</blockquote></details>

doesn't matter, it will be 2 against 1...
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OF2xlZZ8H5N-y7iZGXH:b-z4m662) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Reorganised the tests, what do you think?
</blockquote></details>

if what you're testing is packed_at, using seq is good enough. genrally I wouldnt test a function indexes a collection with a collection that has very low entropy. 
also, you're using generate_seq, why not array::from_fn? it's a bit more code but more simple as you don't need to trust the seq logic (or go look at the code when reading the test)
same for is_first, but unuse that in this test.
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF2yusE5LIl7ZnHJOWJ:-OF2yusE5LIl7ZnHJOWK:b-l4mocu) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/core/backend/simd/m31.rs#L23)):*
> ```XML
> pub const MODULUS: Simd<u32, N_LANES> = Simd::from_array([P; N_LANES]);
> 
> pub const INC: PackedM31 = unsafe {
> ```

remove, and un-pub this const. it's a utility you're using for a specific function, no one from the outside needs to know about it.
also rename to the name I linked at you above. Otherwise shahar will block 
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF2xJaB29RF35HlXNKs:-OF2xJaB29RF35HlXNKt:b-co43pp) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L88)):*
> ```XML
> }
> 
> // TODO(Gali): Move inside the impl of PreprocessedColumn.
> ```

why not now?


<!-- Sent from Reviewable.io -->

2024-12-29 06:46 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1i3726O3aCqWxAEs7:-OFG8OMu8uNfd9xD_prA:bjb5c62) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L122)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

doesn't matter, it will be 2 against 1...
</blockquote></details>

I'm in favour of keeping the test.

Do we need to assert the entire column or can we tests a specific arbitrary index
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF2yusE5LIl7ZnHJOWJ:-OFG9LeYAJ6eUeuxo809:b32v57) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/core/backend/simd/m31.rs#L23)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove, and un-pub this const. it's a utility you're using for a specific function, no one from the outside needs to know about it.
also rename to the name I linked at you above. Otherwise shahar will block
</blockquote></details>

+1
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFG8mY02_3uiphcnN8w:-OFG8mY02_3uiphcnN8x:b-d1bwct) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L17)):*
> ```XML
>     IsFirst(u32),
>     Seq(u32),
>     Plonk(usize),
> ```

Reorder alphabetically

Not directly related, but can you write a short documentation to each variant? - this can be done in another pr.



_Code quote:_
```XML
    XorTable(u32, u32, usize),
    IsFirst(u32),
    Seq(u32),
    Plonk(usize),
```
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFG8GgME8qk3gDYPWxs:-OFG8GgNE_tBJXZ5mxTj:b-eovn8f) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L130)):*
> ```XML
>         let expected_is_first = super::gen_is_first::<SimdBackend>(LOG_SIZE).to_cpu();
>         let seq = super::PreprocessedColumn::Seq(LOG_SIZE);
>         let expected_seq = super::gen_seq::<SimdBackend>(LOG_SIZE).to_cpu();
> ```

This seems like two different tests..



_Code quote:_
```XML
        let is_first = super::PreprocessedColumn::IsFirst(LOG_SIZE);
        let expected_is_first = super::gen_is_first::<SimdBackend>(LOG_SIZE).to_cpu();
        let seq = super::PreprocessedColumn::Seq(LOG_SIZE);
        let expected_seq = super::gen_seq::<SimdBackend>(LOG_SIZE).to_cpu();
```


<!-- Sent from Reviewable.io -->

2024-12-29 09:56 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1kgfMEZugJzk7NByQ:-OFGR8__0tZQ9P6IoGO6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L41)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I hate it.
it's only used here for now, so let it be here.
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1i3726O3aCqWxAEs7:-OFGUOb3A2vJKnJioxE7:b-wi1tg4) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L122)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm in favour of keeping the test.

Do we need to assert the entire column or can we tests a specific arbitrary index
</blockquote></details>

We could, I thought this way will be 100% sound, and it doesn't take long to check 256 numbers.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OFGoMhA2NjJv6F0CA3s:bktdz3j) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

if what you're testing is packed_at, using seq is good enough. genrally I wouldnt test a function indexes a collection with a collection that has very low entropy. 
also, you're using generate_seq, why not array::from_fn? it's a bit more code but more simple as you don't need to trust the seq logic (or go look at the code when reading the test)
same for is_first, but unuse that in this test.
</blockquote></details>

Done with from_fn. So you think I should remove all tests? And why not in is_first?
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFG8mY02_3uiphcnN8w:-OFGQoeIC3X0zB9Sj1II:b-hmq0b9) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Reorder alphabetically

Not directly related, but can you write a short documentation to each variant? - this can be done in another pr.
</blockquote></details>

Done. Sure. BTW, I see that there is also gen_is_ste_with_offset. Should it be added to the enum as well?
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF2xJaB29RF35HlXNKs:-OFGRaBo6rYGhAu1mXid:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L88)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why not now?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFG8GgME8qk3gDYPWxs:-OFGV8jS6F9FXZLeK_Wx:b-nakpf4) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L130)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This seems like two different tests..
</blockquote></details>

Yes, it was originally. But then I remembered what you said about tests and that they should independent of their implementation, so I thought maybe to have 1 test for packed_at and to test there for everything. If we switch to multiple tests, we can identify bugs more easily. So each test should have asserts relating to only one variable/logical process?
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF2yusE5LIl7ZnHJOWJ:-OFGicBL3Qjr5pBF2iBu:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/core/backend/simd/m31.rs#L23)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 11:12 UTC, shaharsamocha7 requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: all files reviewed, 8 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFG8GgME8qk3gDYPWxs:-OFH58EDBZxr8Z03judW:bssiyzp) ([raw file](https://github.com/starkware-libs/stwo/blob/158455b2d8238c2062713f9f6ca760304a97dbb3/crates/prover/src/constraint_framework/preprocessed_columns.rs#L130)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Yes, it was originally. But then I remembered what you said about tests and that they should independent of their implementation, so I thought maybe to have 1 test for packed_at and to test there for everything. If we switch to multiple tests, we can identify bugs more easily. So each test should have asserts relating to only one variable/logical process?
</blockquote></details>

`Each test should have asserts relating to only one variable/logical process?`
This is the concept of unit testing.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFH68sx0Yi7i1ubi6CR:-OFH68sx0Yi7i1ubi6CS:b-hbz6of) ([raw file](https://github.com/starkware-libs/stwo/blob/be05b1ac03a6f904ca200272ecf36c977606077e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L25)):*
> ```XML
>     IsFirst(u32),
>     Plonk(usize),
>     /// A column with sequence of numbers from 0 to 2^log_size - 1.
> ```

Suggestion:



_Suggestion:_
```XML
/// A column with the numbers [0..2^log_size).
```
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFH60eQEXFxqYUZwWTQ:-OFH60eR8eBofBNokS9-:b-wgr7pi) ([raw file](https://github.com/starkware-libs/stwo/blob/be05b1ac03a6f904ca200272ecf36c977606077e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L62)):*
> ```XML
>     }
> 
>     pub fn gen_preprocessed_column<B: Backend>(
> ```

Document this function



_Code quote:_
```XML
pub fn gen_preprocessed_column<B: Backend>(
```


<!-- Sent from Reviewable.io -->

2024-12-29 11:17 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: all files reviewed, 6 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFH60eQEXFxqYUZwWTQ:-OFH7bBr3CGjI2xLhMq8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/be05b1ac03a6f904ca200272ecf36c977606077e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L62)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document this function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 12:03 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHI0RMBOyuv_NTYe-u:-OFHI0RMBOyuv_NTYe-v:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L22)):*
> ```XML
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> pub enum PreprocessedColumn {
>     /// A column with a single one at the first position, and zeros elsewhere.
> ```





_Suggestion:_
```XML
/// A column with `1` at the first position, and `0` elsewhere.
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:04 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHICJC4OfKbszNg2M6:-OFHICJC4OfKbszNg2M7:b-1fsgtl) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L22)):*
> ```XML
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> pub enum PreprocessedColumn {
>     /// A column with a single one at the first position, and zeros elsewhere.
> ```

maybe even 
because it is clearly a column



_Suggestion:_
```XML
/// `1` at the first position, `0` elsewhere.
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:05 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIePZA3yk_4-2tqHZ:-OFHIePZA3yk_4-2tqH_:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L44)):*
> ```XML
>         match self {
>             PreprocessedColumn::IsFirst(log_size) => {
>                 assert!(vec_row <= (1 << log_size) / N_LANES);
> ```





_Suggestion:_
```XML
assert!(vec_row < (1 << log_size) / N_LANES);
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:05 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIi5L7RkASbwWH-Kt:-OFHIi5L7RkASbwWH-Ku:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L54)):*
> ```XML
>             }
>             PreprocessedColumn::Seq(log_size) => {
>                 assert!(vec_row <= (1 << log_size) / N_LANES);
> ```





_Suggestion:_
```XML
ssert!(vec_row < (1 << log_size) / N_LANES);
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:07 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIph82Js2hAw7vn8Q:-OFHIph82Js2hAw7vn8R:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L48)):*
> ```XML
>                     let mut res = [M31::zero(); N_LANES];
>                     res[0] = M31::one();
>                     PackedM31::from_array(res)
> ```





_Suggestion:_
```XML

                    PackedM31::from_simd_unchecked(Simd::from_array(
                        std::array::from_fn(|i| if i == 0 {1} else 0)))
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:09 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHJVDO6TmwswKd5HR2:-OFHJVDO6TmwswKd5HR3:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L154)):*
> ```XML
>     fn test_packed_at_seq() {
>         let seq = super::PreprocessedColumn::Seq(LOG_SIZE);
>         let expected_seq = std::array::from_fn::<_, { 1 << LOG_SIZE }, _>(|i| M31::from(i as u32));
> ```





_Suggestion:_
```XML
 let expected_seq = std::array::from_fn
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:09 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1i3726O3aCqWxAEs7:-OFHJIkM9WWCMMZXXnxM:bkan174) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L122)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

We could, I thought this way will be 100% sound, and it doesn't take long to check 256 numbers.
</blockquote></details>

im fine with either 


<!-- Sent from Reviewable.io -->

2024-12-29 12:21 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHICJC4OfKbszNg2M6:-OFHJm3QAp7_bW8nKKl4:b-kvan7e) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L22)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

maybe even 
because it is clearly a column
</blockquote></details>

I actually like the first suggestion better, to match the description of seq.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHI0RMBOyuv_NTYe-u:-OFHJlnFC11jr1qmyW6x:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L22)):*
> ```XML
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> pub enum PreprocessedColumn {
>     /// A column with a single one at the first position, and zeros elsewhere.
> ```

Done.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIePZA3yk_4-2tqHZ:-OFHKFQ1A26d9iDWIc3y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L44)):*
> ```XML
>         match self {
>             PreprocessedColumn::IsFirst(log_size) => {
>                 assert!(vec_row <= (1 << log_size) / N_LANES);
> ```

Done.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIph82Js2hAw7vn8Q:-OFHKotR7T1UOpBxJa4a:b-n6vf3n) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L48)):*
> ```XML
>                     let mut res = [M31::zero(); N_LANES];
>                     res[0] = M31::one();
>                     PackedM31::from_array(res)
> ```

Done. What do you think about having a PackedM31::from_array()?
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 54 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIi5L7RkASbwWH-Kt:-OFHKFzF5v05lBhsexx9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L54)):*
> ```XML
>             }
>             PreprocessedColumn::Seq(log_size) => {
>                 assert!(vec_row <= (1 << log_size) / N_LANES);
> ```

Done.
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHJVDO6TmwswKd5HR2:-OFHLkcX8LJ3Pdi1PpGP:b-3t5qqb) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L154)):*
> ```XML
>     fn test_packed_at_seq() {
>         let seq = super::PreprocessedColumn::Seq(LOG_SIZE);
>         let expected_seq = std::array::from_fn::<_, { 1 << LOG_SIZE }, _>(|i| M31::from(i as u32));
> ```

It can't infer alone the length of the array, is this better?



_Code snippet:_
```XML
let expected_seq: [M31; 1 << LOG_SIZE] = std::array::from_fn(|i| M31::from(i as u32));
```


<!-- Sent from Reviewable.io -->

2024-12-29 12:29 UTC, shaharsamocha7 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: all files reviewed, 9 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIph82Js2hAw7vn8Q:-OFHO6Sv-ZweXHdy4y_K:b2nign6) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L48)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done. What do you think about having a PackedM31::from_array()?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-12-29 13:36 UTC, ohad-starkware commented
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHJVDO6TmwswKd5HR2:-OFHcMhv79iPiqWC0Ni5:b10157k) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L154)):*
> ```
> [_; 1 << LOG_SIZE]
> ```


<!-- Sent from Reviewable.io -->

2024-12-29 13:36 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: all files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OFHcRtO9W6Jx1Zg8hbV:b-2pdyae) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done with from_fn. So you think I should remove all tests? And why not in is_first?
</blockquote></details>

i didnt understand the question
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHIph82Js2hAw7vn8Q:-OFH_4w3DXaOUFAo0DyP:bldwuen) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

yes
</blockquote></details>

we have it, but it's from a M31 array


<!-- Sent from Reviewable.io -->

2024-12-29 13:45 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OFHeEUJ34rb5SoQ1o9Y:b3wdmgd) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
> same for is\_first, but unuse that in this test.
why not change it here as well?

> if what you're testing is packed\_at, using seq is good enough.
Are you saying this test is redundant?
___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 154 at r4](https://reviewable.io/reviews/starkware-libs/stwo/951#-OFHJVDO6TmwswKd5HR2:-OFHdFpBAdLCBorsJQsF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e72d0454858498613c02710d91f6f7619d97541d/crates/prover/src/constraint_framework/preprocessed_columns.rs#L154)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

> ```
> [_; 1 << LOG_SIZE]
> ```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 14:18 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/preprocessed_columns.rs` line 158 at r1](https://reviewable.io/reviews/starkware-libs/stwo/951#-OF1jROD-9xULP3K5nqO:-OFHlwYh1WhXII6tifDH:b5mrnnm) ([raw file](https://github.com/starkware-libs/stwo/blob/3ddeb3440689e0684f729faae9b7a8f96b4dfd8e/crates/prover/src/constraint_framework/preprocessed_columns.rs#L158)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

> same for is\_first, but unuse that in this test.
why not change it here as well?

> if what you're testing is packed\_at, using seq is good enough.
Are you saying this test is redundant?
</blockquote></details>

current situation is fine


<!-- Sent from Reviewable.io -->

2024-12-29 14:28 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/951#-:-OFHoOO655Wjis4nJHdY:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-12-29 19:42 UTC, merged